<?php

/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Open Software License (OSL 3.0)
 * @package    Mage_Reports
 */

use Carbon\Carbon;

/**
 * Abstract report aggregate resource model
 *
 * @package    Mage_Reports
 */
abstract class Mage_Reports_Model_Resource_Report_Abstract extends Mage_Core_Model_Resource_Db_Abstract
{
    /**
     * Flag object
     *
     * @var Mage_Reports_Model_Flag
     */
    protected $_flag     = null;

    /**
     * Retrieve flag object
     *
     * @return Mage_Reports_Model_Flag
     */
    protected function _getFlag()
    {
        if ($this->_flag === null) {
            $this->_flag = Mage::getModel('reports/flag');
        }

        return $this->_flag;
    }

    /**
     * Saves flag
     *
     * @param  string                                      $code
     * @param  mixed                                       $value
     * @return Mage_Reports_Model_Resource_Report_Abstract
     * @throws Throwable
     */
    protected function _setFlagData($code, $value = null)
    {
        $this->_getFlag()
            ->setReportFlagCode($code)
            ->unsetData()
            ->loadSelf();

        if ($value !== null) {
            $this->_getFlag()->setFlagData($value);
        }

        $time = Varien_Date::toTimestamp(true);
        // touch last_update
        $this->_getFlag()->setLastUpdate($this->formatDate($time));

        $this->_getFlag()->save();

        return $this;
    }

    /**
     * Retrieve flag data
     *
     * @param  string $code
     * @return mixed
     */
    protected function _getFlagData($code)
    {
        $this->_getFlag()
            ->setReportFlagCode($code)
            ->unsetData()
            ->loadSelf();

        return $this->_getFlag()->getFlagData();
    }

    /**
     * Truncate table
     *
     * @param  string                                      $table
     * @return Mage_Reports_Model_Resource_Report_Abstract
     */
    protected function _truncateTable($table)
    {
        if ($this->_getWriteAdapter()->getTransactionLevel() > 0) {
            $this->_getWriteAdapter()->delete($table);
        } else {
            $this->_getWriteAdapter()->truncateTable($table);
        }

        return $this;
    }

    /**
     * Clear report table by specified date range.
     * If specified source table parameters,
     * condition will be generated by source table subselect.
     *
     * @param  string                                      $table
     * @param  null|string                                 $dateFrom
     * @param  null|string                                 $dateTo
     * @param  null|string|Zend_Db_Select                  $subSelect
     * @param  bool                                        $doNotUseTruncate
     * @return Mage_Reports_Model_Resource_Report_Abstract
     */
    protected function _clearTableByDateRange(
        $table,
        $dateFrom = null,
        $dateTo = null,
        $subSelect = null,
        $doNotUseTruncate = false
    ) {
        if ($dateFrom === null && $dateTo === null && !$doNotUseTruncate) {
            $this->_truncateTable($table);
            return $this;
        }

        if ($subSelect !== null) {
            $deleteCondition = $this->_makeConditionFromDateRangeSelect($subSelect, 'period');
        } else {
            $condition = [];
            if ($dateFrom !== null) {
                $condition[] = $this->_getWriteAdapter()->quoteInto('period >= ?', $dateFrom);
            }

            if ($dateTo !== null) {
                $condition[] = $this->_getWriteAdapter()->quoteInto('period <= ?', $dateTo);
            }

            $deleteCondition = implode(' AND ', $condition);
        }

        $this->_getWriteAdapter()->delete($table, $deleteCondition);
        return $this;
    }

    /**
     * Generate table date range select
     *
     * @param  string            $table
     * @param  string            $column
     * @param  string            $whereColumn
     * @param  null|string       $dateFrom
     * @param  null|string       $dateTo
     * @param  array             $additionalWhere
     * @param  string            $alias
     * @return Varien_Db_Select
     * @throws Zend_Db_Exception
     */
    protected function _getTableDateRangeSelect(
        $table,
        $column,
        $whereColumn,
        $dateFrom = null,
        $dateTo = null,
        $additionalWhere = [],
        $alias = 'date_range_table'
    ) {
        $adapter = $this->_getReadAdapter();
        $select  = $adapter->select()
            ->from(
                [$alias => $table],
                $adapter->getDatePartSql(
                    $this->getStoreTZOffsetQuery([$alias => $table], $alias . '.' . $column, $dateFrom, $dateTo),
                ),
            )
            // phpcs:ignore Ecg.Sql.SlowQuery.SlowSql
            ->distinct(true);

        if ($dateFrom !== null) {
            $select->where($alias . '.' . $whereColumn . ' >= ?', $dateFrom);
        }

        if ($dateTo !== null) {
            $select->where($alias . '.' . $whereColumn . ' <= ?', $dateTo);
        }

        if ($additionalWhere !== []) {
            foreach ($additionalWhere as $condition) {
                if (is_array($condition) && count($condition) == 2) {
                    $condition = $adapter->quoteInto($condition[0], $condition[1]);
                } elseif (is_array($condition)) { // Invalid condition
                    continue;
                }

                $condition = str_replace('{{table}}', $adapter->quoteIdentifier($alias), $condition);
                $select->where($condition);
            }
        }

        return $select;
    }

    /**
     * Make condition for using in where section
     * from select statement with single date column
     *
     * @param  string|Zend_Db_Select $select
     * @param  string                $periodColumn
     * @return false|string
     */
    protected function _makeConditionFromDateRangeSelect($select, $periodColumn)
    {
        static $selectResultCache = [];
        $cacheKey = (string) $select;

        if (!array_key_exists($cacheKey, $selectResultCache)) {
            try {
                $selectResult = [];
                $query = $this->_getReadAdapter()->query($select);
                while ($date = $query->fetchColumn()) {
                    $selectResult[] = $date;
                }
            } catch (Exception) {
                $selectResult = false;
            }

            $selectResultCache[$cacheKey] = $selectResult;
        } else {
            $selectResult = $selectResultCache[$cacheKey];
        }

        if ($selectResult === false) {
            return false;
        }

        $whereCondition = [];
        $adapter = $this->_getReadAdapter();
        foreach ($selectResult as $date) {
            $date = substr($date, 0, 10); // to fix differences in oracle
            $whereCondition[] = $adapter->prepareSqlCondition($periodColumn, ['like' => $date]);
        }

        $whereCondition = implode(' OR ', $whereCondition);
        if ($whereCondition == '') {
            $whereCondition = '1=0';  // FALSE condition!
        }

        return $whereCondition;
    }

    /**
     * Generate table date range select
     *
     * @param  string           $table
     * @param  string           $relatedTable
     * @param  array            $joinCondition
     * @param  string           $column
     * @param  string           $whereColumn
     * @param  null|string      $dateFrom
     * @param  null|string      $dateTo
     * @param  array            $additionalWhere
     * @param  string           $alias
     * @param  string           $relatedAlias
     * @return Varien_Db_Select
     * @SuppressWarnings("PHPMD.ExcessiveParameterList")
     */
    protected function _getTableDateRangeRelatedSelect(
        $table,
        $relatedTable,
        $joinCondition,
        $column,
        $whereColumn,
        $dateFrom = null,
        $dateTo = null,
        $additionalWhere = [],
        $alias = 'date_range_table',
        $relatedAlias = 'related_date_range_table'
    ) {
        $adapter = $this->_getReadAdapter();
        $joinConditionSql = [];

        foreach ($joinCondition as $fkField => $pkField) {
            $joinConditionSql[] = sprintf('%s.%s = %s.%s', $alias, $fkField, $relatedAlias, $pkField);
        }

        $select = $adapter->select()
            ->from(
                [$alias => $table],
                $adapter->getDatePartSql(
                    $adapter->quoteIdentifier($alias . '.' . $column),
                ),
            )
            ->joinInner(
                [$relatedAlias => $relatedTable],
                implode(' AND ', $joinConditionSql),
                [],
            )
            // phpcs:ignore Ecg.Sql.SlowQuery.SlowSql
            ->distinct();

        if ($dateFrom !== null) {
            $select->where($relatedAlias . '.' . $whereColumn . ' >= ?', $dateFrom);
        }

        if ($dateTo !== null) {
            $select->where($relatedAlias . '.' . $whereColumn . ' <= ?', $dateTo);
        }

        if ($additionalWhere !== []) {
            foreach ($additionalWhere as $condition) {
                if (is_array($condition) && count($condition) == 2) {
                    $condition = $adapter->quoteInto($condition[0], $condition[1]);
                } elseif (is_array($condition)) { // Invalid condition
                    continue;
                }

                $condition = str_replace(
                    ['{{table}}', '{{related_table}}'],
                    [
                        $adapter->quoteIdentifier($alias),
                        $adapter->quoteIdentifier($relatedAlias),
                    ],
                    $condition,
                );
                $select->where($condition);
            }
        }

        return $select;
    }

    /**
     * Check range dates and transforms it to strings
     *
     * @param  mixed                                       $dateFrom
     * @param  mixed                                       $dateTo
     * @return Mage_Reports_Model_Resource_Report_Abstract
     */
    protected function _checkDates(&$dateFrom, &$dateTo)
    {
        if ($dateFrom !== null) {
            $dateFrom = $this->formatDate($dateFrom);
        }

        if ($dateTo !== null) {
            $dateTo = $this->formatDate($dateTo);
        }

        return $this;
    }

    /**
     * Retrieve query for attribute with timezone conversion
     *
     * @param  array|string                          $table
     * @param  string                                $column
     * @param  null|string                           $dateFrom
     * @param  null|string                           $dateTo
     * @param  null|int|Mage_Core_Model_Store|string $store
     * @return string
     * @throws Zend_Db_Exception
     */
    public function getStoreTZOffsetQuery($table, $column, $dateFrom = null, $dateTo = null, $store = null)
    {
        $column = $this->_getWriteAdapter()->quoteIdentifier($column);

        if (is_null($dateFrom)) {
            $selectOldest = $this->_getWriteAdapter()->select()
                ->from(
                    $table,
                    ["MIN($column)"],
                );
            $dateFrom = $this->_getWriteAdapter()->fetchOne($selectOldest);
        }

        $periods = $this->_getTZOffsetTransitions(
            Mage::app()->getLocale()->storeDate($store)->toString(Zend_Date::TIMEZONE_NAME),
            $dateFrom,
            $dateTo,
        );
        if ($periods === []) {
            return $column;
        }

        $query = '';
        $periodsCount = count($periods);

        $index = 0;
        foreach ($periods as $offset => $timestamps) {
            $subParts = [];
            foreach ($timestamps as $timestamp) {
                $subParts[] = "($column between {$timestamp['from']} and {$timestamp['to']})";
            }

            $then = $this->_getWriteAdapter()
                ->getDateAddSql($column, $offset, Varien_Db_Adapter_Interface::INTERVAL_SECOND);

            $query .= (++$index == $periodsCount) ? $then : 'CASE WHEN ' . implode(' OR ', $subParts) . " THEN $then ELSE ";
        }

        return $query . str_repeat('END ', count($periods) - 1);
    }

    /**
     * Retrieve transitions for offsets of given timezone
     *
     * @param  string $timezone
     * @param  mixed  $dateFrom
     * @param  mixed  $dateTo
     * @return array
     */
    protected function _getTZOffsetTransitions($timezone, $dateFrom = null, $dateTo = null)
    {
        $tzTransitions = [];
        try {
            if (!empty($dateFrom)) {
                $dateFrom = new Zend_Date($dateFrom, Varien_Date::DATETIME_INTERNAL_FORMAT);
                $dateFrom = $dateFrom->getTimestamp();
            }

            $dateTo = new Zend_Date($dateTo, Varien_Date::DATETIME_INTERNAL_FORMAT);
            $nextPeriod = $this->_getWriteAdapter()->formatDate($dateTo->toString(Varien_Date::DATETIME_INTERNAL_FORMAT));
            $dateTo = $dateTo->getTimestamp();

            $dateTimeObject = new Zend_Date('c');
            $dtz = new DateTimeZone($timezone);
            $transitions = array_reverse($dtz->getTransitions());
            foreach ($transitions as $transition) {
                if (!$this->_isValidTransition($transition, $dateTo)) {
                    continue;
                }

                $dateTimeObject->set($transition['time']);
                $transition['time'] = $this->_getWriteAdapter()
                    ->formatDate($dateTimeObject->toString(Varien_Date::DATETIME_INTERNAL_FORMAT));
                $tzTransitions[$transition['offset']][] = ['from' => $transition['time'], 'to' => $nextPeriod];

                if (!empty($dateFrom) && $transition['ts'] < $dateFrom) {
                    break;
                }

                $nextPeriod = $transition['time'];
            }
        } catch (Exception $exception) {
            $this->_logException($exception);
        }

        return $tzTransitions;
    }

    /**
     * Logs the exceptions
     *
     * @param Exception $exception
     */
    protected function _logException($exception)
    {
        Mage::logException($exception);
    }

    /**
     * Verifies the transition and the "to" timestamp
     *
     * @param  array      $transition
     * @param  int|string $timestamp
     * @return bool
     */
    protected function _isValidTransition($transition, $timestamp)
    {
        $result         = true;
        $transTimestamp = $transition['ts'];
        $transTime      = $transition['time'];
        $transYear      = Carbon::createFromTimeString($transTime)->format('Y');

        if ($transYear > 10000 || $transYear < -10000) {
            $result = false;
        } elseif ($transTimestamp > $timestamp) {
            $result = false;
        }

        return $result;
    }

    /**
     * Retrieve store timezone offset from UTC in the form acceptable by SQL's CONVERT_TZ()
     *
     * @param  null|bool|int|Mage_Core_Model_Store|string $store
     * @return string
     */
    protected function _getStoreTimezoneUtcOffset($store = null)
    {
        return Mage::app()->getLocale()->storeDate($store)->toString(Zend_Date::GMT_DIFF_SEP);
    }

    /**
     * Retrieve date in UTC timezone
     *
     * @param  null|string         $date
     * @return null|Zend_Date
     * @throws Zend_Date_Exception
     */
    protected function _dateToUtc($date)
    {
        if ($date === null) {
            return null;
        }

        $dateUtc = new Zend_Date($date);
        $dateUtc->setTimezone('Etc/UTC');
        return $dateUtc;
    }
}
