<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Checkout_Block_Multishipping_Billing_Items
 * @var Mage_Checkout_Block_Multishipping_Billing_Items $this
 */
?>
<?php if ($this->getQuote()->hasVirtualItems()): ?>
    <div class="col2-set">
        <h2 class="legend"><?php echo $this->__('Other Items in Your Order') ?></h2>
        <div class="col-1 col-narrow"></div>
        <div class="col-2 col-wide">
            <h3><?php echo $this->__('Items') ?> <span class="separator">|</span> <a href="<?php echo $this->getVirtualProductEditUrl() ?>"><?php echo $this->__('Edit Items') ?></a></h3>
            <table class="data-table" id="unavailable-shipping-table">
                <col />
                <col width="1" />
                <thead>
                    <tr>
                        <th><?php echo $this->__('Product Name') ?></th>
                        <th class="a-center"><?php echo $this->__('Qty') ?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->getVirtualQuoteItems() as $_item): ?>
                    <tr>
                        <td><?php echo $this->getItemHtml($_item) ?></td>
                        <td class="a-center"><?php echo $_item->getQty() ?></td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
            <script type="text/javascript">decorateTable('unavailable-shipping-table')</script>
        </div>
    </div>
<?php endif ?>
