<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <title><?php echo Mage::helper('adminhtml')->__('Log into OpenMage Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('boxes.css') ?>" media="all" />
    <link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/captcha.js') ?>"></script>
</head>
<body id="page-login">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="<?php echo $this->getUrl('adminhtml') ?>" id="loginForm">
                <div class="login-form">
                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                    <h2><?php echo Mage::helper('adminhtml')->__('Log in to Admin Panel') ?></h2>
                    <div id="messages">
                        <?php echo $this->getMessagesBlock()->toHtml() ?>
                    </div>
                    <div class="input-box input-left">
                        <label for="username"><?php echo Mage::helper('adminhtml')->__('User Name:') ?></label><br />
                        <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" autofocus="autofocus" />
                    </div>
                    <div class="input-box input-right">
                        <label for="login"><?php echo Mage::helper('adminhtml')->__('Password:') ?></label><br />
                        <input type="password" id="login" name="login[password]" value="" class="required-entry input-text" />
                    </div>
                    <?php echo $this->getChildHtml('form.additional.info') ?>
                    <div class="clear"></div>
                    <div class="form-buttons">
                        <a class="left" href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/index/forgotpassword', ['_nosecret' => true]) ?>"><?php echo Mage::helper('adminhtml')->__('Forgot your password?') ?></a>
                        <button type="submit" class="form-button"><span><span><span><?php echo Mage::helper('adminhtml')->__('Login') ?></span></span></span></button>
                    </div>
                </div>
                <p class="legal"><?php echo Mage::helper('adminhtml')->__('Powered by OpenMage') ?></p>
            </form>
            <div class="bottom"></div>
            <script type="text/javascript">
                var loginForm = new varienForm('loginForm');
            </script>
        </div>
    </div>
</body>
</html>
