<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_System_Design_Edit $this */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="icon-head head-products"><?php echo $this->getHeader() ?></h3></td>
            <td class="form-buttons">
            <?php echo $this->getChildHtml('back_button') ?>
            <?php if($this->getDesignChangeId()): ?>
                <?php echo $this->getChildHtml('delete_button') ?>
            <?php endif ?>
            <?php echo $this->getChildHtml('save_button') ?>
            </td>
        </tr>
    </table>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="design_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
    var designForm = new varienForm('design_edit_form');
</script>
