<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_System_Design $this */
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('catalog')->__('Design') ?></h3></td>
        <td class="form-buttons">
            <?php echo $this->getChildHtml('add_new_button') ?>
        </td>
    </tr>
</table>
</div>
<div>
    <?php echo $this->getChildHtml('grid') ?>
</div>
