<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
    /* @var $this Mage_ConfigurableSwatches_Block_Catalog_Media_Js_Abstract */
?>

<script type="text/javascript">
    if(!(typeof $j == 'function' && $j === jQuery)) {
        ConfigurableMediaImages.init('<?php echo $this->getImageType(); ?>');
        <?php foreach ($this->getProductImageFallbacks() as $imageFallback): ?>
        ConfigurableMediaImages.setImageFallback(<?php echo $imageFallback['product']->getId(); ?>, JSON.parse('<?php echo $imageFallback['image_fallback']; ?>'));
        <?php endforeach ?>
        document.dispatchEvent(new Event('configurable-media-images-init'));
    } else {
        // compatibility with rwd theme ProductMediaManager in app.js
        $j(document).on('product-media-loaded', function() {
            ConfigurableMediaImages.init('<?php echo $this->getImageType(); ?>');
            <?php foreach ($this->getProductImageFallbacks() as $imageFallback): ?>
            ConfigurableMediaImages.setImageFallback(<?php echo $imageFallback['product']->getId(); ?>, $j.parseJSON('<?php echo $imageFallback['image_fallback']; ?>'));
            <?php endforeach ?>
            $j(document).trigger('configurable-media-images-init', ConfigurableMediaImages);
        });
    }
</script>
