#!/usr/bin/env php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$mtfRoot = dirname(__DIR__);
$mtfRoot = str_replace('\\', '/', $mtfRoot);
define('MTF_PHPUNIT_FILE', $mtfRoot . DIRECTORY_SEPARATOR . 'phpunit.xml');
include $mtfRoot . '/vendor/magento/mtf/utils/mtf';