<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
function install()
{
    $('run_iframe').src = '<?php echo $this->getUrl('*/*/install', array('do'=>'run')) ?>?id=<?php echo urlencode($this->getRequest()->getParam('id')) ?>';
    $('run_iframe').style.display = 'block';
}

function upgrade()
{
    $('run_iframe').src = '<?php echo $this->getUrl('*/*/upgrade', array('do'=>'run')) ?>?id=<?php echo urlencode($this->getRequest()->getParam('id')) ?>';
    $('run_iframe').style.display = 'block';
}
</script>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Actions") ?></h4>
    </div>
    <fieldset>
        <legend><?php echo $this->__("Actions") ?></legend>
        <?php echo $this->getActionButtonHtml() ?><br/>
        <iframe id="run_iframe" src="<?php echo $this->getUrl('*/*/install') ?>?id=<?php echo urlencode($this->getRequest()->getParam('id')) ?>" frameborder=0 style="display:none; width:100%; height:400px;"></iframe>
    </fieldset>
</div>