<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Catalog_Product_View_Profile
 * @var Mage_Payment_Block_Catalog_Product_View_Profile $this 
 */
?>
<dl>
<?php foreach($this->getScheduleInfo() as $term => $definitions): ?>
    <dt><?php echo $this->escapeHtml($term); ?></dt>
<?php foreach ($definitions as $definition):?>
    <dd><?php echo $this->escapeHtml($definition)?></dd>
<?php endforeach ?>
<?php endforeach ?>
</dl>
