<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Catalog_Product_View_Profile
 * @var Mage_Payment_Block_Catalog_Product_View_Profile $this 
 */
?>
<dl>
<?php foreach($this->getScheduleInfo() as $term => $definitions): ?>
    <dt><?php echo $this->escapeHtml($term); ?></dt>
<?php foreach ($definitions as $definition):?>
    <dd><?php echo $this->escapeHtml($definition)?></dd>
<?php endforeach ?>
<?php endforeach ?>
</dl>
