<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Catalog_Product_View_Profile
 * @var Mage_Payment_Block_Catalog_Product_View_Profile $this 
 */
?>
<dl>
<?php foreach($this->getScheduleInfo() as $term => $definitions): ?>
    <dt><?php echo $this->escapeHtml($term); ?></dt>
<?php foreach ($definitions as $definition):?>
    <dd><?php echo $this->escapeHtml($definition)?></dd>
<?php endforeach ?>
<?php endforeach ?>
</dl>
