<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php /** @var Mage_Sales_Block_Recurring_Profile_View $this */?>
<?php if ($this->getIsAddress()):?>

<?php foreach ($this->getRenderedInfo() as $row):?>
<address><?php echo nl2br($this->escapeHtml($this->getObjectData($row, 'value')))?></address>
<?php endforeach ?>

<?php else: ?>

<table cellspacing="0" class="form-list">
<tbody>
<?php foreach ($this->getRenderedInfo() as $row):?>
<?php $isAmount = $this->getObjectData($row, 'is_amount');?>
    <tr>
    <td class="label"><label><?php echo $this->escapeHtml($this->getObjectData($row, 'label'))?></label></td>
    <td<?php echo $isAmount ? ' class="a-right"' : ''?>>
        <strong><?php echo $this->renderRowValue($row) ?></strong>
    </td>
    </tr>
<?php endforeach ?>
</tbody>
</table>
<?php endif ?>
