<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * Urlrewrites edit container
 *
 * @see Mage_Adminhtml_Block_Urlrewrite_Edit
 * @var Mage_Adminhtml_Block_Urlrewrite_Edit $this
 */
?>
<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="content-buttons form-buttons"><?php echo $this->getButtonsHtml() ?></p>
</div>

<?php echo $this->getChildHtml() ?>

<?php if ($this->getChild('form')): ?>
<script type="text/javascript">
    var editForm = new varienForm('edit_form', '<?php echo $this->getValidationUrl() ?>');
</script>
<?php endif ?>
