<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Urlrewrites edit mode selector
 *
 * @see Mage_Adminhtml_Block_Urlrewrite_Selector
 * @var Mage_Adminhtml_Block_Urlrewrite_Selector $this 
 */
?>
<div class="entry-edit">
<div class="fieldset">

<table cellspacing="0" class="form-list">
    <tr>
        <td class="label"><?php echo $this->getSelectorLabel() ?></td>
        <td class="value">
            <?php $url = Mage::helper('adminhtml')->getUrl('*/*/*')?>
            <select class="select" onchange="window.location = this.value;">
            <?php foreach ($this->getModes() as $mode => $label): ?>
                <option <?php echo ($this->isMode($mode) ? 'selected="selected" ' :'' ) ?>value="<?php echo $url . $mode ?>"><?php echo $label ?></option>
            <?php endforeach ?>
            </select>
        </td>
    </tr>
</table>
</div>
</div>
