<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * Urlrewrites edit mode selector
 *
 * @see Mage_Adminhtml_Block_Urlrewrite_Selector
 * @var Mage_Adminhtml_Block_Urlrewrite_Selector $this 
 */
?>
<div class="entry-edit">
<div class="fieldset">

<table cellspacing="0" class="form-list">
    <tr>
        <td class="label"><?php echo $this->getSelectorLabel() ?></td>
        <td class="value">
            <?php $url = Mage::helper('adminhtml')->getUrl('*/*/*')?>
            <select class="select" onchange="window.location = this.value;">
            <?php foreach ($this->getModes() as $mode => $label): ?>
                <option <?php echo ($this->isMode($mode) ? 'selected="selected" ' :'' ) ?>value="<?php echo $url . $mode ?>"><?php echo $label ?></option>
            <?php endforeach ?>
            </select>
        </td>
    </tr>
</table>
</div>
</div>
