<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php if( $this->getRating() && $this->getRating()->getSize()): ?>
    <div class="ratings-container">
        <?php foreach ($this->getRating() as $_rating): ?>
        <?php if($_rating->getPercent()): ?>
            <div class="ratings">
               <?php echo $this->escapeHtml($_rating->getRatingCode()) ?>
                <div class="rating-box">
                    <div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
                </div>
            </div>
        <?php endif ?>
        <?php endforeach ?>
    </div>
<?php else: ?>
    <?php echo Mage::helper('rating')->__("Rating isn't Available") ?>
<?php endif ?>
