<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if( $this->getRating() && $this->getRating()->getSize()): ?>
    <div class="ratings-container">
        <?php foreach ($this->getRating() as $_rating): ?>
        <?php if($_rating->getPercent()): ?>
        	<div class="ratings">
        	   <?php echo $_rating->getRatingCode() ?>
        		<div class="rating-box">
        			<div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
        		</div>
        	</div>
        <?php endif; ?>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <?php echo Mage::helper('rating')->__("Rating isn't Available") ?>
<?php endif; ?>
