<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Review_Rating_Summary $this */
?>
<?php if($this->getRatingSummary()->getCount()): ?>
    <div class="rating-box">
        <div class="rating" style="width:<?php echo ceil($this->getRatingSummary()->getSum() / ($this->getRatingSummary()->getCount())) ?>%;"></div>
    </div>
<?php else: ?>
    <?php echo Mage::helper('rating')->__("Rating isn't Available") ?>
<?php endif ?>
