<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2019-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Paygate_Block_Authorizenet_Info_Cc
 * @var Mage_Paygate_Block_Authorizenet_Info_Cc $this
 */
?>

<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;
?>

<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>{{pdf_row_separator}}
<?php foreach ($cards as $key => $card): ?>
    <?php if ($showCount): ?>
       <?php echo sprintf($this->__('Credit Card %s'), $key + 1); ?>
       {{pdf_row_separator}}
    <?php endif ?>

    <?php foreach ($card as $_label => $_value):?>
        <?php echo $_label ?>: <?php echo implode(' ', $this->getValueAsArray($_value))?>{{pdf_row_separator}}
     <?php endforeach ?>
<?php endforeach ?>
