<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   default
 * @package    default_default
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset id="order_history_block">
    <?php if ($this->canAddComment()):?>
    <div id="history_form" class="order-history-form">
        <div><?php echo Mage::helper('sales')->__('Add Order Comments') ?></div>
        <span class="field-row">
            <label class="normal" for="history_status"><?php echo Mage::helper('sales')->__('Status') ?></label><br/>
            <select name="history[status]" class="select" id="history_status">
            <?php foreach ($this->getStatuses() as $_code=>$_label): ?>
                <option value="<?php echo $_code ?>"<?php if($_code==$this->getOrder()->getStatus()): ?> selected="selected"<?php endif; ?>><?php echo $_label ?></option>
            <?php endforeach; ?>
            </select>
        </span>
        <span class="field-row">
            <label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Comment') ?></label>
            <textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
        </span>
        <div class="f-left">
            <input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1" />
            <label class="normal" for="history_notify"><?php echo Mage::helper('sales')->__('Notify Customer') ?></label>
        </div>
        <div class="f-right">
            <?php echo $this->getChildHtml('submit_button') ?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
    <?php endif;?>
    <ul class="note-list">
    <?php foreach ($this->getOrder()->getStatusHistoryCollection(true) as $_history): ?>
        <li>
            <strong><?php echo $this->helper('core')->formatDate($_history->getCreatedAt(), 'medium') ?></strong>
            <?php echo $this->helper('core')->formatTime($_history->getCreatedAt(), 'medium') ?><span class="separator">|</span><strong><?php echo $_history->getStatusLabel() ?></strong><br/><small><?php echo $this->helper('sales')->__('Customer') ?>
            <strong class="subdue">
                <?php if ($_history->getIsCustomerNotified()): ?>
                <?php echo $this->helper('sales')->__('Notified') ?>
                <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                <?php else: ?>
                <?php echo $this->helper('sales')->__('Not Notified') ?>
                <?php endif; ?>
            </strong></small>
            <?php if($_history->getComment()): ?>
                <br/><?php echo $_history->getComment() ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">
    if($('order_status'))$('order_status').update('<?php echo $this->getOrder()->getStatusLabel() ?>');
    </script>
</fieldset>
