<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div id="order_history_block">
    <?php if ($this->canAddComment()):?>
    <div id="history_form" class="order-history-form">
        <div><?= Mage::helper('sales')->__('Add Order Comments') ?></div>
        <span class="field-row">
            <label class="normal" for="history_status"><?= Mage::helper('sales')->__('Status') ?></label><br/>
            <select name="history[status]" class="select" id="history_status">
            <?php foreach ($this->getStatuses() as $_code=>$_label): ?>
                <option value="<?= $_code ?>"<?php if($_code==$this->getOrder()->getStatus()): ?> selected="selected"<?php endif ?>><?= $_label ?></option>
            <?php endforeach ?>
            </select>
        </span>
        <span class="field-row">
            <label class="normal" for="history_comment"><?= Mage::helper('sales')->__('Comment') ?></label>
            <textarea name="history[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
        </span>
        <div class="f-left">
            <?php if ($this->canSendCommentEmail()): ?>
                <input name="history[is_customer_notified]" type="checkbox" id="history_notify" value="1" /><label class="normal" for="history_notify"> <?= Mage::helper('sales')->__('Notify Customer by Email') ?></label><br />
            <?php endif ?>
            <input name="history[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?= Mage::helper('sales')->__('Visible on Frontend') ?></label>
        </div>
        <div class="f-right">
            <?= $this->getChildHtml('submit_button') ?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
    <?php endif ?>
    <ul class="note-list">
    <?php foreach ($this->getOrder()->getStatusHistoryCollection(true) as $_item): ?>
        <li>
            <strong><?= $this->helper('core')->formatDate($_item->getCreatedAtDate(), 'medium') ?></strong>
            <?= $this->helper('core')->formatTime($_item->getCreatedAtDate(), 'medium') ?><span class="separator">|</span><strong><?= $_item->getStatusLabel() ?></strong><br/><small><?= $this->helper('sales')->__('Customer') ?>
            <strong class="subdue">
                <?php if ($this->isCustomerNotificationNotApplicable($_item)): ?>
                <?= $this->helper('sales')->__('Notification Not Applicable') ?>
                <?php elseif ($_item->getIsCustomerNotified()): ?>
                <?= $this->helper('sales')->__('Notified') ?>
                <img src="<?= $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                <?php else: ?>
                <?= $this->helper('sales')->__('Not Notified') ?>
                <?php endif ?>
            </strong></small>
            <?php if ($_item->getComment()): ?>
                <br/><?= $this->escapeHtml($_item->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>
            <?php endif ?>
        </li>
    <?php endforeach ?>
    </ul>
    <script type="text/javascript">
        if ($('order_status')) $('order_status').update('<?= $this->jsQuoteEscape($this->getOrder()->getStatusLabel()) ?>');
    </script>
</div>
