<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php $_shippingCarrier = $this->getOrder()->getShippingCarrier(); ?>
<?php if ($_shippingCarrier && $_shippingCarrier->isTrackingAvailable()): ?>
<span class="field-row" id="order_tracking_info">
<table cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td><label for="tracking_number"><?php echo Mage::helper('sales')->__('Tracking Number') ?></label></td>
        <td width="100%">
            <?php $_numbers = $this->getOrder()->getTrackingNumbers(); ?>
            <?php if ($_numbers): ?>
                <?php foreach ($_numbers as $_number): ?>
                    <a href="#" onclick="<?php echo $this->getViewLinkHtml($_number) ?>"><?php echo $_number ?></a>
                    <a href="#" onclick="<?php echo $this->getRemoveLinkHtml($_number) ?>"><?php echo Mage::helper('sales')->__('Delete') ?></a><br/>
                    <span id="order_tracking_info_response_<?php echo $_number ?>"></span>
                <?php endforeach ?>
            <?php endif ?>
            <input class="input-text" type="text" id="tracking_number" name="tracking_number" value="" style="width:120px;"/>
            <?php echo $this->getSaveButtonHtml() ?>
        </td>
    </tr>
</table>
</span>
<?php endif ?>
