<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Centinel_Block_Logo
 * @var Mage_Centinel_Block_Logo $this
 */
?>
<li class="centinel-logos" id="<?php echo $this->getCode() ?>_centinel_logo">
    <label><?php echo $this->__('To ensure the security of your transactions') ?></label>
    <div class="input-box">
        <a href="#" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Verified by Visa')) ?> " onclick="popWin('<?php echo $this->helper('centinel')->getVisaLearnMorePageUrl()?>', 'verifiedByVisa', 'width=815,height=600,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><img src="<?php echo $this->getSkinUrl('images/centinel/vbv_ltbg_71x57.png'); ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Verified by Visa')) ?>" /></a>
        <a href="#" title="<?php echo Mage::helper('core')->quoteEscape($this->__('MasterCard SecureCode')); ?>" onclick="popWin('<?php echo $this->helper('centinel')->getMastercardLearnMorePageUrl()?>', 'secureCode', 'width=600,height=403,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><img src="<?php echo $this->getSkinUrl('images/centinel/sc_learn_62x34.png'); ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('MasterCard SecureCode')) ?>" /></a>
    </div>
</li>
