<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php /** @var Mage_Catalog_Block_Product_View_Options_Type_Default $this */ ?>
<?php $option = $this->getOption(); ?>
<dt>
    <label><?php echo $this->escapeHtml($option->getTitle()) ?></label>
</dt>
