authors:
  kiatng:
    name: Ng Kiat Siong
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/1106470
  sreichel:
    name: Sven Reichel
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/5022236
