authors:
  openmage_community:
    name: OpenMage
    description: Community
    avatar: https://avatars.githubusercontent.com/u/57708
  colinmollenhour:
    name: Colin Mollenhour
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/38738
  fballiano :
    name: Fabrizio Balliano
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/909743
  Flyingmana:
    name: Daniel Fahlke
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/237319
  kiatng:
    name: Ng Kiat Siong
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/1106470
  robertrogge:
    name: Robert Rogge
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/673488
  sreichel:
    name: Sven Reichel
    description: Maintainer
    avatar: https://avatars.githubusercontent.com/u/5022236
