<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="col2-set">
    <div class="col-1">
        <div class="inner-head">
            <h5><?php echo $this->__('Contact Information') ?></h5>
            <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
        </div>
        <p>
            <?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br />
            <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
            <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
        </p>
    </div>

    <div class="col-2">
        <div class="inner-head">
            <h5><?php echo $this->__('Newsletters') ?></h5>
            <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
        </div>
        <p>
            <?php if( $this->getIsSubscribed() ): ?>
                <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
            <?php else: ?>
                <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
            <?php endif; ?>
        </p>
    </div>
</div>
<br />
