<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @var Mage_Adminhtml_Block_Tax_Rate_Toolbar_Add $this
 * @var string $header
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-tax"><?php echo $header ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getChildHtml('addButton') ?>
            </td>
        </tr>
    </table>
</div>
