<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Adminhtml_Block_Tax_Rate_Toolbar_Save $this
 * @var string $header
 * @var Mage_Adminhtml_Block_Tax_Rate_Form $form
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-tax"><?php echo $header ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml(); ?>
                <?php echo $this->getResetButtonHtml(); ?>
                <?php echo $this->getDeleteButtonHtml(); ?>
                <?php echo $this->getSaveButtonHtml(); ?>
            </td>
        </tr>
    </table>
</div>
<?php if( $form ): ?>
<?php echo $form->toHtml(); ?>
<script type="text/javascript">
    var wigetForm = new varienForm('<?php echo $form->getForm()->getId() ?>');
</script>
<?php endif ?>
