<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @var Mage_Adminhtml_Block_Tax_Rate_Toolbar_Save $this
 * @var string $header
 * @var Mage_Adminhtml_Block_Tax_Rate_Form $form
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-tax"><?php echo $header ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml(); ?>
                <?php echo $this->getResetButtonHtml(); ?>
                <?php echo $this->getDeleteButtonHtml(); ?>
                <?php echo $this->getSaveButtonHtml(); ?>
            </td>
        </tr>
    </table>
</div>
<?php if( $form ): ?>
<?php echo $form->toHtml(); ?>
<script type="text/javascript">
    var wigetForm = new varienForm('<?php echo $form->getForm()->getId() ?>');
</script>
<?php endif ?>
