<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * "Grant Access" button
 *
 * @var $this Mage_Oauth_Block_Authorize
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="login-form">
            <h1><?= $this->__('Confirmation Of Authorization') ?></h1>
            <?= $this->getMessagesBlock()->toHtml() ?>
            <?php if (!$this->getHasException()): ?>
                <p><?= $this->__('Give the verifier code to application administrator') ?></p>
                <p style="font-size: 14px;"><?= $this->__('Verifier code: %s', $this->getVerifier()) ?></p>
            <?php endif ?>
        </div>
        <p class="legal"><?= $this->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')) ?></p>
        <div class="bottom"></div>
    </div>
</div>
