<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * "Grant Access" button
 *
 * @var Mage_Oauth_Block_Authorize $this
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="login-form">
            <h1><?php echo $this->__('Confirmation Of Authorization') ?></h1>
            <?php echo $this->getMessagesBlock()->toHtml() ?>
            <?php if (!$this->getHasException()): ?>
                <p><?php echo $this->__('Give the verifier code to application administrator') ?></p>
                <p style="font-size: 14px;"><?php echo $this->__('Verifier code: %s', $this->getVerifier()) ?></p>
            <?php endif ?>
        </div>
        <p class="legal"><?php echo $this->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', \Carbon\Carbon::now()->format('Y')) ?></p>
        <div class="bottom"></div>
    </div>
</div>
