<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * "Grant Access" button
 *
 * @see Mage_Oauth_Block_Authorize
 */
?>
<?php /** @var $this Mage_Core_Block_Template */ ?>
<div class="login-container">
    <div class="login-box">
        <div class="login-form">
            <h1><?php echo $this->__('Rejection Of Authorization') ?></h1>
            <?php echo $this->getMessagesBlock()->toHtml() ?>
        </div>
        <p class="legal"><?php echo $this->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')) ?></p>
        <div class="bottom"></div>
    </div>
</div>
