<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Create_Comment $this */
 ?>
<!--<h4 class="icon-head fieldset-legend <?php echo $this->getHeaderCssClass() ?>"><?php echo $this->getHeaderText() ?></h4>-->
<label for="order-comment"><?php echo Mage::helper('sales')->__('Order Comments') ?></label><br />
<textarea style="width:98%; height:8em;" id="order-comment" name="order[comment][customer_note]" rows="2" cols="15"><?php echo $this->getCommentNote() ?></textarea>
<script type="text/javascript">order.commentFieldsBind('order-comment')</script>
