<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Create_Items $this */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-cart"><?php echo $this->getHeaderText() ?></h4>
        <div class="form-buttons"><?php echo $this->getButtonsHtml() ?></div>
    </div>
    <?php echo $this->getChildHtml() ?>
</div>
