<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Template $this */
 ?>
<script type="text/javascript">
    order.sidebarHide();
    Event.observe(window, 'load',  function() {
        if (window.productConfigure) {
            productConfigure.addListType('product_to_add', {
                urlFetch: '<?php echo $this->getUrl('*/sales_order_create/configureProductToAdd') ?>'
            });
            productConfigure.addListType('quote_items', {
                urlFetch: '<?php echo $this->getUrl('*/sales_order_create/configureQuoteItems') ?>'
            });
        }
    });
</script>
