<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
 ?>
<script type="text/javascript">
    order.sidebarHide();
    Event.observe(window, 'load',  function() {
        if (window.productConfigure) {
            productConfigure.addListType('product_to_add', {
                urlFetch: '<?php echo $this->getUrl('*/sales_order_create/configureProductToAdd') ?>'
            });
            productConfigure.addListType('quote_items', {
                urlFetch: '<?php echo $this->getUrl('*/sales_order_create/configureQuoteItems') ?>'
            });
        }
    });
</script>
