<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @var Mage_Page_Block_Template_Links $this
 */
?>
<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
<div class="links">
    <?php if($this->getTitle()): ?>
    <div class="block-title"><strong><span><?= $this->__($this->getTitle()) ?></span></strong></div>
    <?php endif ?>
    <ul<?php if($this->getName()): ?> id="<?= $this->getName() ?>"<?php endif ?>>
        <?php foreach($_links as $_link): ?>
            <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
                <?= $_link->toHtml() ?>
            <?php else: ?>
                <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif ?><?php if($_link->getIsLast()): ?> last<?php endif ?>"<?php endif ?> <?= $_link->getLiParams() ?>><?= $_link->getBeforeText() ?><a href="<?= $_link->getUrl() ?>" title="<?= $_link->getTitle() ?>" <?= $_link->getAParams() ?>><?= $_link->getLabel() ?></a><?= $_link->getAfterText() ?></li>
            <?php endif ?>
        <?php endforeach ?>
    </ul>
</div>
<?php endif ?>
