<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_Catalog_Block_Product_View_Additional
 * @var Mage_Catalog_Block_Product_View_Additional $this
 */
?>
<?php foreach ($this->getChildHtmlList() as $_html): ?>
    <?php echo $_html ?>
<?php endforeach ?>
