<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Catalog_Block_Product_View_Additional
 * @var Mage_Catalog_Block_Product_View_Additional $this
 */
?>
<?php foreach ($this->getChildHtmlList() as $_html): ?>
    <?php echo $_html ?>
<?php endforeach ?>
