<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/** @var Mage_Catalog_Block_Product_View_Options $this */
?>

<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()) ?>
<?php if (count($_options)):?>
    <script type="text/javascript">
    //<![CDATA[
    var optionFileUpload = {
        productForm : document.getElementById('product_addtocart_form'),
        formAction : '',
        formElements : {},
        upload : function(element){
            this.formElements = this.productForm.querySelectorAll('input, select, textarea, button');
            this.removeRequire(element.getAttribute('id').replace('option_', ''));

            template = '<iframe id="upload_target" name="upload_target" style="width:0; height:0; border:0;"><\/iframe>';

            document.getElementById('option_'+element.getAttribute('id').replace('option_', '')+'_uploaded_file').insertAdjacentHTML('afterend', template);

            this.formAction = this.productForm.action;

            var baseUrl = '<?php echo $this->getUrl('*/product/upload') ?>';
            var urlExt = 'option_id/'+element.getAttribute('id').replace('option_', '');

            this.productForm.action = parseSidUrl(baseUrl, urlExt);
            this.productForm.target = 'upload_target';
            this.productForm.submit();
            this.productForm.target = '';
            this.productForm.action = this.formAction;
        },
        removeRequire : function(skipElementId){
            for(var i=0; i<this.formElements.length; i++){
                if (this.formElements[i].getAttribute('id') != 'option_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
                    this.formElements[i].disabled='disabled';
                }
            }
        },
        addRequire : function(skipElementId){
            for(var i=0; i<this.formElements.length; i++){
                if (this.formElements[i].getAttribute('name') != 'options_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
                    this.formElements[i].disabled='';
                }
            }
        },
        uploadCallback : function(data){
            this.addRequire(data.optionId);
            document.getElementById('upload_target').remove();

            if (data.error) {

            } else {
                document.getElementById('option_'+data.optionId+'_uploaded_file').value = data.fileName;
                document.getElementById('option_'+data.optionId+'_file').value = '';
                document.getElementById('option_'+data.optionId+'_file').style.display = 'none';
                document.getElementById('option_'+data.optionId+'').style.display = 'none';
                template = '<div id="option_'+data.optionId+'_file_box"><a href="#"><img src="var/options/'+data.fileName+'" alt=""><\/a><a href="#" onclick="optionFileUpload.removeFile('+data.optionId+')" title="Remove file" \/>Remove file<\/a>';

                document.getElementById('option_'+data.optionId+'_uploaded_file').insertAdjacentHTML('afterend', template);
            }
        },
        removeFile : function(optionId)
        {
            document.getElementById('option_'+optionId+'_uploaded_file').value= '';
            document.getElementById('option_'+optionId+'_file').style.display = '';
            document.getElementById('option_'+optionId+'').style.display = '';

            document.getElementById('option_'+optionId+'_file_box').remove();
        }
    }
    var optionTextCounter = {
        count : function(field,cntfield,maxlimit){
            if (field.value.length > maxlimit){
                field.value = field.value.substring(0, maxlimit);
            } else {
                cntfield.innerHTML = maxlimit - field.value.length;
            }
        }
    }

    Product.Options = function() {
        this.initialize.apply(this, arguments);
    };
    Product.Options.prototype = {
        initialize : function(config) {
            this.config = config;
            this.reloadPrice();
            document.addEventListener('DOMContentLoaded', this.reloadPrice.bind(this));
        },
        reloadPrice : function() {
            var config = this.config;
            var skipIds = [];
            document.querySelectorAll('body .product-custom-option').forEach(function(element){
                var optionId = 0;
                var optionIdMatch = element.name.match(/[0-9]+/);
                if (optionIdMatch) {
                    optionId = parseInt(optionIdMatch[0], 10);
                }
                if (config[optionId]) {
                    var configOptions = config[optionId];
                    var curConfig = {price: 0};
                    if (element.type == 'checkbox' || element.type == 'radio') {
                        if (element.checked) {
                            if (typeof configOptions[element.value] != 'undefined') {
                                curConfig = configOptions[element.value];
                            }
                        }
                    } else if(element.classList.contains('datetime-picker') && skipIds.indexOf(optionId) === -1) {
                        dateSelected = true;
                        document.querySelectorAll('.product-custom-option[id^="options_' + optionId + '"]').forEach(function(dt){
                            if (dt.value == '') {
                                dateSelected = false;
                            }
                        });
                        if (dateSelected) {
                            curConfig = configOptions;
                            skipIds[optionId] = optionId;
                        }
                    } else if(element.type == 'select-one' || element.type == 'select-multiple') {
                        if ('options' in element) {
                            Array.from(element.options).forEach(function(selectOption){
                                if ('selected' in selectOption && selectOption.selected) {
                                    if (typeof(configOptions[selectOption.value]) != 'undefined') {
                                        curConfig = configOptions[selectOption.value];
                                    }
                                }
                            });
                        }
                    } else {
                        if (element.value.trim() != '') {
                            curConfig = configOptions;
                        }
                    }
                    if(element.type == 'select-multiple' && ('options' in element)) {
                        Array.from(element.options).forEach(function(selectOption) {
                            if (('selected' in selectOption) && typeof(configOptions[selectOption.value]) != 'undefined') {
                                if (selectOption.selected) {
                                    curConfig = configOptions[selectOption.value];
                                } else {
                                    curConfig = {price: 0};
                                }
                                optionsPrice.addCustomPrices(optionId + '-' + selectOption.value, curConfig);
                                optionsPrice.reload();
                            }
                        });
                    } else {
                        optionsPrice.addCustomPrices(element.id || optionId, curConfig);
                        optionsPrice.reload();
                    }
                }
            });
        }
    }
    function validateOptionsCallback(elmId, result) {
        var container = document.getElementById(elmId).closest('ul.options-list');
        if (result == 'failed') {
            container.classList.remove('validation-passed');
            container.classList.add('validation-failed');
        } else {
            container.classList.remove('validation-failed');
            container.classList.add('validation-passed');
        }
    }
    var opConfig = new Product.Options(<?php echo $this->getJsonConfig() ?>);
    //]]>
    </script>
    <dl>
    <?php foreach($_options as $_option): ?>
        <?php echo $this->getOptionHtml($_option) ?>
    <?php endforeach ?>
    </dl>
<?php endif ?>
