<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @deprecated  after 1.4.0.0-alpha3
 */
?>
<div class="price-box" id="product_price">
    <p class="old-price"><?php echo $this->__('Old Price:') ?> <?php echo $this->getPrice() ?></p>
    <p class="special-price"><?php echo $this->getPrice() ?></p>
</div>
