<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_Catalog_Block_Product_View
 * @var Mage_Catalog_Block_Product_View $this
 */
?>
<?php $_product = $this->getProduct() ?>
<?php echo $this->getPriceHtml($_product, false, '_clone') ?>
