<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @deprecated  after 1.4.0.0-alpha3
 */
?>
<div class="price-box" id="product_price">
    <p class="old-price"><?php echo $this->__('Old Price:') ?> <?php echo $this->getPrice() ?></p>
    <p class="special-price"><?php echo $this->getPrice() ?></p>
</div>
