<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2018-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @var Mage_Bundle_Block_Sales_Order_Items_Renderer $this
 */
?>
<?php $parentItem = $this->getItem() ?>

<?php $items = array_merge([$parentItem->getOrderItem()], $parentItem->getOrderItem()->getChildrenItems()) ?>
<?php $shipItems = $this->getChilds($parentItem) ?>

<?php $_prevOptionId = '' ?>

<?php if($this->getItemOptions() || $parentItem->getDescription() || $this->canDisplayGiftmessage()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif ?>

<?php foreach ($items as $_item): ?>
<?php if ($_item->getParentItem()): ?>
    <?php $attributes = $this->getSelectionAttributes($_item) ?>
    <?php if ($_prevOptionId != $attributes['option_id']): ?>
    <tr>
        <td class="bundle-item"><strong><em><?php echo $this->escapeHtml($attributes['option_label']); ?></em></strong></td>
        <td class="bundle-item">&nbsp;</td>
        <td class="bundle-item">&nbsp;</td>
    </tr>
    <?php $_prevOptionId = $attributes['option_id'] ?>
    <?php endif ?>
<?php endif ?>
<tr id="order-item-row-<?php echo $_item->getId() ?>">
    <?php if (!$_item->getParentItem()): ?>
    <td class="bundle-item-parent product-info">
        <p class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></p>
    </td>
    <td class="bundle-item-parent align-center">
        <?php echo $this->escapeHtml($_item->getSku()) ?>
    </td>
    <td class="bundle-item-parent align-right">
    <?php else: ?>
    <td class="bundle-item bundle-details product-info"><div><?php echo $this->getValueHtml($_item)?></div></td>
    <td class="bundle-item bundle-details align-center">
        <?php echo $this->escapeHtml($_item->getSku()) ?>
    </td>
    <td class="bundle-item align-right">
    <?php endif ?>
    <?php if (($this->isShipmentSeparately() && $_item->getParentItem()) || (!$this->isShipmentSeparately() && !$_item->getParentItem())): ?>
        <?php if (isset($shipItems[$_item->getId()])): ?>
            <?php echo $shipItems[$_item->getId()]->getQty()*1 ?>
        <?php elseif ($_item->getIsVirtual()): ?>
            <?php echo $this->__('N/A') ?>
        <?php else: ?>
            0
        <?php endif ?>
    <?php else: ?>
    &nbsp;
    <?php endif ?>
    </td>
</tr>
<?php endforeach ?>

<?php if ($_showlastRow): ?>
<tr>
    <td align="left" valign="top" style="padding:3px 9px">
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?php echo $option['label'] ?></em></strong>
                        <dd style="margin:0; padding:0 0 0 9px;"><?php echo $option['value'] ?></dd>
            <?php endforeach ?>
        </dl>
        <?php endif ?>
        <?php echo $this->escapeHtml($parentItem->getDescription()) ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php endif ?>
