<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Sales_Block_Order_Email_Creditmemo_Items
 * @var Mage_Sales_Block_Order_Email_Creditmemo_Items $this
 */
?>
<?php $_creditmemo = $this->getCreditmemo() ?>
<?php $_order      = $this->getOrder() ?>
<?php if ($_creditmemo && $_order): ?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Item') ?></th>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Sku') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Qty') ?></th>
            <th align="right" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>

    <?php $i=0; foreach ($_creditmemo->getAllItems() as $_item): ?>
    <?php if($_item->getOrderItem()->getParentItem()) continue; $i++; ?>
    <tbody<?php echo $i%2 ? ' bgcolor="#F6F6F6"' : '' ?>>
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
    <?php endforeach ?>

    <tfoot>
        <?php echo $this->getChildHtml('creditmemo_totals');?>
    </tfoot>
</table>
<?php endif ?>
