<?php if ($_product = $this->getProduct()): ?>
    <?php if ($this->canRenderScript()): ?>
        <script defer src="https://www.paypal.com/sdk/js?client-id=<?php echo $this->getPaypalSdkClientId(); ?>&components=messages"></script>
    <?php endif; ?>
    <div class="paypal-paylater-message-product"></div>
    <script>
        document.addEventListener('DOMContentLoaded', (e) => {
            if (typeof paypal != "undefined") {
                paypal
                    .Messages({
                        amount: <?php echo $_product->getFinalPrice(); ?>,
                        placement: "product"
                    })
                    .render(".paypal-paylater-message-product");
            }
        });
    </script>
<?php endif; ?>

