<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * Authorize confirm simple template
 *
 * @var Mage_Oauth_Block_Authorize $this
 */
?>
<div class="account-login login-only">
        <div class="page-title">
            <h1><?php echo $this->__('Confirmation Of Authorization') ?></h1>
        </div>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php if ($this->getVerifier()): ?>
        <p><?php echo $this->__('Give the verifier code to application administrator') ?></p>
        <p style="font-size: 14px;"><?php echo $this->__('Verifier code: %s', $this->getVerifier()) ?></p>
    <?php endif ?>
</div>
