<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * Head block Oauth simple pages
 *
 * @var Mage_Page_Block_Html_Head $this
 */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php echo $this->getCssJsHtml() ?>
