<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * Head block Oauth simple pages
 *
 * @var Mage_Page_Block_Html_Head $this
 */
?>
<meta http-equiv="Content-Type" content="<?= $this->getContentType() ?>" />
<title><?= $this->getTitle() ?></title>
<link rel="icon" href="<?= $this->getFaviconFile() ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?= $this->getFaviconFile() ?>" type="image/x-icon" />

<?= $this->getCssJsHtml() ?>
