<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * Head block Oauth simple pages
 *
 * @var Mage_Page_Block_Html_Head $this
 */
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php echo $this->getCssJsHtml() ?>
