<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * Token rejection template
 *
 * @var Mage_Oauth_Block_Authorize_Button $this
 */
?>
<div class="account-login login-only">
        <div class="page-title">
            <h1><?php echo $this->__('Reject authorization') ?></h1>
        </div>
        <?php echo $this->getMessagesBlock()->toHtml() ?>
</div>
