<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * Authorize rejection simple template
 *
 * @var Mage_Oauth_Block_AuthorizeBaseAbstract $this
 */
?>
<div class="login-container">
    <div class="login-box">
        <div class="page-title">
            <h1><?php echo $this->__('Rejection Of Authorization') ?></h1>
        </div>
        <div class="form-box">
            <div id="messages">
                <?php echo $this->getMessagesBlock()->toHtml() ?>
            </div>
            <button type="submit" class="button" onclick="window.close();" title="<?php echo $this->__('Close') ?>">
                <span><span><?php echo $this->__('Close') ?></span></span>
            </button>
        </div>
    </div>
</div>
