<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Newsletter_Template_Edit $this */
?>
<div class="content-header">
   <h3 class="icon-head head-newsletter"><?php echo $this->getHeaderText() ?></h3>
   <p class="content-buttons form-buttons">
                <?php echo $this->getBackButtonHtml(); ?>
                <?php echo $this->getResetButtonHtml(); ?>
                <?php if(!$this->isTextType()): ?>
                <?php echo $this->getToPlainButtonHtml(); ?>
                <?php echo $this->getToHtmlButtonHtml(); ?>
                <?php endif ?>
                <?php echo $this->getPreviewButtonHtml(); ?>
                <?php if($this->getEditMode()): ?>
                <?php echo $this->getDeleteButtonHtml(); ?>
                <?php endif ?>
                <?php if($this->getEditMode()): ?>
                <?php echo $this->getSaveAsButtonHtml(); ?>
                <?php endif ?>
                <?php echo $this->getSaveButtonHtml(); ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="newsletter_template_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="no-display">
        <input type="hidden" id="change_flag_element" name="_change_type_flag" value="" />
        <input type="hidden" id="save_as_flag" name="_save_as_flag" value="<?php echo $this->getSaveAsFlag() ?>" />
    </div>
    <?php echo $this->getForm() ?>
</form>
<form action="<?php echo $this->getPreviewUrl() ?>" method="post" id="newsletter_template_preview_form" target="_blank">
    <?php echo $this->getBlockHtml('formkey')?>
    <div class="no-display">
        <input type="hidden" id="preview_type" name="type" value="<?php echo $this->isTextType()?1:2 ?>" />
        <input type="hidden" id="preview_text" name="text" value="" />
        <input type="hidden" id="preview_styles" name="styles" value="" />
        <input type="hidden" id="preview_id" name="id" value="" />
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var templateForm = new varienForm('newsletter_template_edit_form');
    var templatePreviewForm = new varienForm('newsletter_template_preview_form');
    var templateControl = {

        unconvertedText: '',
        typeChange: false,
        templateName: false,
        id: 'text',

        init: function () {
            if (document.getElementById('convert_button_back')) {
                document.getElementById('convert_button_back').style.display = 'none';
            }
        },

        stripTags: function () {
            if(!window.confirm("<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('newsletter')->__('Are you sure that you want to strip all tags?')) ?>")) {
                return false;
            }
            if(this.isEditor()) {
                this.getEditor().turnOff();
                this.getEditor().getToggleButton().hide();
            }
            this.unconvertedText = document.getElementById(this.id).value;
            document.getElementById('convert_button').style.display = 'none';
            document.getElementById('convert_button_back').style.display = '';
            document.getElementById(this.id).value = document.getElementById(this.id).value.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '').replace(/<\/?[^>]+>/gi, '');
            document.getElementById('field_template_styles').style.display = 'none';
            this.typeChange = true;
            return false;
        },

        unStripTags: function () {
            document.getElementById('convert_button').style.display = '';
            document.getElementById('convert_button_back').style.display = 'none';
            document.getElementById(this.id).value = this.unconvertedText;
            if(this.isEditor()) {
                this.getEditor().turnOn();
                this.getEditor().getToggleButton().show();
            }
            this.typeChange = false;
            document.getElementById('field_template_styles').style.display = '';
            return false;
        },

        save: function() {
            if (this.typeChange) {
                document.getElementById('change_flag_element').value = '1';
            }
            if(this.isEditor()) {
                tinymce.triggerSave();
            }
            templateForm.submit();
            return false;
        },

        saveAs: function() {
            if (this.typeChange) {
                document.getElementById('change_flag_element').value = '1';
            }

            var codeVal = document.getElementById('code').value;
            if(!codeVal || codeVal.trim() === '' || codeVal==templateControl.templateName) {
               value = prompt('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('newsletter')->__('Please enter new template name')) ?>', templateControl.templateName + '<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('newsletter')->__(' Copy')) ?>');
               if(!value) {
                   if(value !== null) {
                       document.getElementById('code').value = '';
                       templateForm.submit();
                   }
                   return false;
               } else {
                   document.getElementById('code').value = value;
               }
            }

            document.getElementById('save_as_flag').value = '1';

            if(this.isEditor()) {
                tinymce.triggerSave();
            }
            templateForm.submit();
            return false;
        },

        preview: function() {
            if (this.typeChange) {
                document.getElementById('preview_type').value = 1;
            } else {
                document.getElementById('preview_type').value = 2;
            }
            if (this.isEditor() && tinymce.get(this.id)) {
                tinymce.triggerSave();
                document.getElementById('preview_text').value = document.getElementById(this.id).value;
                tinymce.triggerSave();
            } else {
                document.getElementById('preview_text').value = document.getElementById(this.id).value;
            }
            if (document.getElementById('template_styles') != undefined) {
                document.getElementById('preview_styles').value = document.getElementById('template_styles').value;
            }
            if (document.getElementById('id') != undefined) {
                document.getElementById('preview_id').value = document.getElementById('id').value;
            }
            templatePreviewForm.submit();
            return false;
        },

        deleteTemplate: function() {
            if(window.confirm("<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('newsletter')->__('Are you sure that you want to delete this template?')) ?>")) {
                   window.location.href = '<?php echo $this->getDeleteUrl() ?>';
            }
        },

        isEditor: function() {
            return (typeof tinyMceEditors != 'undefined' && tinyMceEditors[this.id] != undefined)
        },

        getEditor: function() {
            return tinyMceEditors[this.id];
        }
    };

    templateControl.init();
    templateControl.templateName = "<?php echo $this->getJsTemplateName() ?>";
//]]>
</script>
