<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Customer_Block_Account_Dashboard_Newsletter
 * @var Mage_Customer_Block_Account_Dashboard_Newsletter $this
 */
?>
<div class="col-2">
    <h4><?php echo $this->__('Newsletters') ?></h4>
    <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit Newsletters') ?></a>
    <p><?php echo $this->__('You are currently subscribed to our newsletter.') ?></p>
</div>
