<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Customer_Block_Account_Dashboard_Newsletter
 * @var Mage_Customer_Block_Account_Dashboard_Newsletter $this
 */
?>
<div class="col-2">
    <h4><?php echo $this->__('Newsletters') ?></h4>
    <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit Newsletters') ?></a>
    <p><?php echo $this->__('You are currently subscribed to our newsletter.') ?></p>
</div>
