<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Template
 * @var Mage_Adminhtml_Block_Template $this
 */
$object = $this->getObject();
?>

<a href="<?php echo $this->getLinkUrl(); ?>" class="<?php echo $object->getIsDefault() ? 'bold' : '' ?> <?php echo $this->getClass(); ?>" title="<?php echo $this->__('Id') . ': ' . $object->getId()?>">
    <?php echo $this->escapeHtml($object->getName()); ?>
</a>
<br />
<span class="additional-info">(<?php echo $this->getInfo(); ?>)</span>
