'Environment':
  - .github/*
  - .github/**/*
  - .phpstorm.meta.php/*
  - .travis.yml

'htaccess':
  - .htaccess

'composer':
  - composer.json

'downloader':
  - downloader/*
  - downloader/**/*

'errors':
  - errors/*
  - errors/**/*

'Javascript':
  - js/*
  - js/**/*

# Add Library Labels (tbc)
'Component: lib/Mage':
  - lib/Mage/*
  - lib/Mage/**/*

'Component: lib/Varien':
  - lib/Varien/*
  - lib/Varien/**/*

'Component: lib/PEAR':
  - lib/PEAR/*
  - lib/PEAR/**/*

'Component: lib/Zend':
  - lib/Zend/*
  - lib/Zend/**/*
  - app/code/core/Zend/*
  - app/code/core/Zend/**/*

'Component: lib/*':
  - lib/*
  - lib/**/*

'shell':
  - shell/*
  - shell/**/*

# Add Mage.php
'Mage.php':
  - app/Mage.php

# Add Module Labels
'Component: Admin':
  - app/code/core/Mage/Admin/*
  - app/code/core/Mage/Admin/**/*
  - app/design/adminhtml/default/layout/admin.xml

'Component: Adminhtml':
  - app/code/core/Mage/Adminhtml/*
  - app/code/core/Mage/Adminhtml/**/*
  - app/design/adminhtml/*
  - app/design/adminhtml/**/*
  - skin/adminhtml/*
  - skin/adminhtml/**/*

'Component: AdminNotification':
  - app/code/core/Mage/AdminNotification/*
  - app/code/core/Mage/AdminNotification/**/*
  - app/design/adminhtml/default/layout/adminnotification.xml

'Component: Api':
  - app/code/core/Mage/Api/*
  - app/code/core/Mage/Api/**/*
  - app/design/adminhtml/default/template/api/*
  - app/design/adminhtml/default/template/api/**/*

'Component: Api2':
  - app/code/core/Mage/Api2/*
  - app/code/core/Mage/Api2/**/*
  - app/design/adminhtml/default/layout/api2.xml
  - app/design/adminhtml/default/template/api2/*
  - app/design/adminhtml/default/template/api2/**/*

'Component: Authorizenet':
  - app/code/core/Mage/Authorizenet/*
  - app/code/core/Mage/Authorizenet/**/*
  - app/design/adminhtml/default/layout/authorizenet.xml
  - app/design/adminhtml/default/template/authorizenet/*
  - app/design/adminhtml/default/template/authorizenet/**/*
  - app/design/frontend/*/*/layout/authorizenet.xml
  - app/design/frontend/*/*/template/authorizenet/*
  - app/design/frontend/*/*/template/authorizenet/**/*

'Component: Backup':
  - app/code/core/Mage/Backup/*
  - app/code/core/Mage/Backup/**/*
  - app/design/adminhtml/default/template/backup/*
  - app/design/adminhtml/default/template/backup/**/*

'Component: Bundle':
  - app/code/core/Mage/Bundle/*
  - app/code/core/Mage/Bundle/**/*
  - app/design/adminhtml/default/layout/bundle.xml
  - app/design/adminhtml/default/template/bundle/*
  - app/design/adminhtml/default/template/bundle/**/*
  - app/design/frontend/*/*/layout/bundle.xml
  - app/design/frontend/*/*/template/bundle/*
  - app/design/frontend/*/*/template/bundle/**/*

'Component: Captcha':
  - app/code/core/Mage/Captcha/*
  - app/code/core/Mage/Captcha/**/*
  - app/design/adminhtml/default/layout/captcha.xml
  - app/design/adminhtml/default/template/captcha/*
  - app/design/adminhtml/default/template/captcha/**/*
  - app/design/frontend/*/*/layout/captcha.xml
  - app/design/frontend/*/*/template/captcha/*
  - app/design/frontend/*/*/template/captcha/**/*

'Component: Catalog':
  - app/code/core/Mage/Catalog/*
  - app/code/core/Mage/Catalog/**/*
  - app/design/adminhtml/default/layout/catalog.xml
  - app/design/adminhtml/default/template/catalog/*
  - app/design/adminhtml/default/template/catalog/**/*
  - app/design/frontend/*/*/layout/catalog.xml
  - app/design/frontend/*/*/layout/catalog_msrp.xml
  - app/design/frontend/*/*/template/catalog/*
  - app/design/frontend/*/*/template/catalog/**/*

'Component: CatalogIndex':
  - app/code/core/Mage/CatalogIndex/*
  - app/code/core/Mage/CatalogIndex/**/*

'Component: CatalogInventory':
  - app/code/core/Mage/CatalogInventory/*
  - app/code/core/Mage/CatalogInventory/**/*
  - app/design/frontend/*/*/layout/cataloginventory.xml
  - app/design/frontend/*/*/template/cataloginventory/*
  - app/design/frontend/*/*/template/cataloginventory/**/*

'Component: CatalogRule':
  - app/code/core/Mage/CatalogRule/*
  - app/code/core/Mage/CatalogRule/**/*

'Component: CatalogSearch':
  - app/code/core/Mage/CatalogSearch/*
  - app/code/core/Mage/CatalogSearch/**/*
  - app/design/adminhtml/default/layout/search.xml
  - app/design/frontend/*/*/layout/catalogsearch.xml
  - app/design/frontend/*/*/template/catalogsearch/*
  - app/design/frontend/*/*/template/catalogsearch/**/*

'Component: Centinel':
  - app/code/core/Mage/Centinel/*
  - app/code/core/Mage/Centinel/**/*
  - app/design/adminhtml/default/layout/centinel.xml
  - app/design/adminhtml/default/template/centinel/*
  - app/design/adminhtml/default/template/centinel/**/*
  - app/design/frontend/*/*/layout/centinel.xml
  - app/design/frontend/*/*/template/centinel/*
  - app/design/frontend/*/*/template/centinel/**/*

'Component: Checkout':
  - app/code/core/Mage/Checkout/*
  - app/code/core/Mage/Checkout/**/*
  - app/design/frontend/*/*/layout/checkout.xml
  - app/design/frontend/*/*/template/checkout/*
  - app/design/frontend/*/*/template/checkout/**/*

'Component: Cms':
  - app/code/core/Mage/Cms/*
  - app/code/core/Mage/Cms/**/*
  - app/design/adminhtml/default/layout/cms.xml
  - app/design/adminhtml/default/template/cms/*
  - app/design/adminhtml/default/template/cms/**/*
  - app/design/frontend/*/*/layout/cms.xml
  - app/design/frontend/*/*/template/cms/*
  - app/design/frontend/*/*/template/cms/**/*

'Component: ConfigurableSwatches':
  - app/code/core/Mage/ConfigurableSwatches/*
  - app/code/core/Mage/ConfigurableSwatches/**/*

'Component: Connect':
  - app/code/core/Mage/Connect/*
  - app/code/core/Mage/Connect/**/*
  - app/design/adminhtml/default/layout/connect.xml
  - app/design/adminhtml/default/template/connect/*
  - app/design/adminhtml/default/template/connect/**/*

'Component: Contacts':
  - app/code/core/Mage/Contacts/*
  - app/code/core/Mage/Contacts/**/*
  - app/design/frontend/*/*/layout/contacts.xml
  - app/design/frontend/*/*/template/contacts/*
  - app/design/frontend/*/*/template/contacts/**/*

'Component: Core':
  - app/code/core/Mage/Core/*
  - app/code/core/Mage/Core/**/*
  - app/design/frontend/*/*/layout/core.xml
  - app/design/frontend/*/*/template/core/*
  - app/design/frontend/*/*/template/core/**/*

'Component: Cron':
  - app/code/core/Mage/Cron/*
  - app/code/core/Mage/Cron/**/*

'Component: CurrencySymbol':
  - app/code/core/Mage/CurrencySymbol/*
  - app/code/core/Mage/CurrencySymbol/**/*
  - app/design/adminhtml/default/layout/currencysymbol.xml
  - app/design/adminhtml/default/template/currencysymbol/*
  - app/design/adminhtml/default/template/currencysymbol/**/*

'Component: Customer':
  - app/code/core/Mage/Customer/*
  - app/code/core/Mage/Customer/**/*
  - app/design/adminhtml/default/layout/customer.xml
  - app/design/adminhtml/default/template/customer/*
  - app/design/adminhtml/default/template/customer/**/*
  - app/design/frontend/*/*/layout/customer.xml
  - app/design/frontend/*/*/template/customer/*
  - app/design/frontend/*/*/template/customer/**/*

'Component: Dataflow':
  - app/code/core/Mage/Dataflow/*
  - app/code/core/Mage/Dataflow/**/*
  - app/design/adminhtml/default/layout/dataflow.xml

'Component: Directory':
  - app/code/core/Mage/Directory/*
  - app/code/core/Mage/Directory/**/*
  - app/design/adminhtml/default/template/directory/*
  - app/design/adminhtml/default/template/directory/**/*
  - app/design/frontend/*/*/layout/directory.xml
  - app/design/frontend/*/*/template/directory/*
  - app/design/frontend/*/*/template/directory/**/*

'Component: Downloadable':
  - app/code/core/Mage/Downloadable/*
  - app/code/core/Mage/Downloadable/**/*
  - app/design/adminhtml/default/layout/downloadable.xml
  - app/design/adminhtml/default/template/downloadable/*
  - app/design/adminhtml/default/template/downloadable/**/*
  - app/design/frontend/*/*/layout/downloadable.xml
  - app/design/frontend/*/*/template/downloadable/*
  - app/design/frontend/*/*/template/downloadable/**/*

'Component: Eav':
  - app/code/core/Mage/Eav/*
  - app/code/core/Mage/Eav/**/*
  - app/design/adminhtml/default/template/eav/*
  - app/design/adminhtml/default/template/eav/**/*

'Component: Giftmessage':
  - app/code/core/Mage/Giftmessage/*
  - app/code/core/Mage/Giftmessage/**/*
  - app/design/adminhtml/default/layout/giftmessage.xml
  - app/design/adminhtml/default/template/giftmessage/*
  - app/design/adminhtml/default/template/giftmessage/**/*
  - app/design/frontend/*/*/template/giftmessage/*
  - app/design/frontend/*/*/template/giftmessage/**/*

'Component: GoogleAnalytics':
  - app/code/core/Mage/GoogleAnalytics/*
  - app/code/core/Mage/GoogleAnalytics/**/*
  - app/design/frontend/*/*/layout/googleanalytics.xml
  - app/design/frontend/*/*/template/googleanalytics/*
  - app/design/frontend/*/*/template/googleanalytics/**/*

'Component: GoogleBase':
  - app/code/core/Mage/GoogleBase/*
  - app/code/core/Mage/GoogleBase/**/*
  - app/design/adminhtml/default/template/googlebase/*
  - app/design/adminhtml/default/template/googlebase/**/*

'Component: GoogleCheckout':
  - app/code/core/Mage/GoogleCheckout/*
  - app/code/core/Mage/GoogleCheckout/**/*

'Component: ImportExport':
  - app/code/core/Mage/ImportExport/*
  - app/code/core/Mage/ImportExport/**/*
  - app/design/adminhtml/default/layout/importexport.xml
  - app/design/adminhtml/default/template/importexport/*
  - app/design/adminhtml/default/template/importexport/**/*

'Component: Index':
  - app/code/core/Mage/Index/*
  - app/code/core/Mage/Index/**/*
  - app/design/adminhtml/default/layout/index.xml
  - app/design/adminhtml/default/template/index/*
  - app/design/adminhtml/default/template/index/**/*

'Component: Install':
  - app/code/core/Mage/Install/*
  - app/code/core/Mage/Install/**/*

'Component: Log':
  - app/code/core/Mage/Log/*
  - app/code/core/Mage/Log/**/*

'Component: Media':
  - app/code/core/Mage/Media/*
  - app/code/core/Mage/Media/**/*
  - app/design/adminhtml/default/template/media/*
  - app/design/adminhtml/default/template/media/**/*

'Component: Newsletter':
  - app/code/core/Mage/Newsletter/*
  - app/code/core/Mage/Newsletter/**/*
    - app/design/adminhtml/default/layout/newsletter.xml
  - app/design/adminhtml/default/template/newsletter/*
  - app/design/adminhtml/default/template/newsletter/**/*
  - app/design/frontend/*/*/layout/newsletter.xml
  - app/design/frontend/*/*/template/newsletter/*
  - app/design/frontend/*/*/template/newsletter/**/*

'Component: Oauth':
  - app/code/core/Mage/Oauth/*
  - app/code/core/Mage/Oauth/**/*
  - app/design/adminhtml/default/layout/oauth.xml
  - app/design/adminhtml/default/template/oauth/*
  - app/design/adminhtml/default/template/oauth/**/*
  - app/design/frontend/*/*/layout/oauth.xml
  - app/design/frontend/*/*/template/oauth/*
  - app/design/frontend/*/*/template/oauth/**/*

'Component: Page':
  - app/code/core/Mage/Page/*
  - app/code/core/Mage/Page/**/*
  - app/design/adminhtml/default/template/page/*
  - app/design/adminhtml/default/template/page/**/*
  - app/design/frontend/*/*/layout/page.xml
  - app/design/frontend/*/*/template/page/*
  - app/design/frontend/*/*/template/page/**/*

'Component: PageCache':
  - app/code/core/Mage/PageCache/*
  - app/code/core/Mage/PageCache/**/*
  - app/design/adminhtml/default/layout/pagecache.xml
  - app/design/adminhtml/default/template/pagecache/*
  - app/design/adminhtml/default/template/pagecache/**/*
  - app/design/frontend/*/*/layout/pagecache.xml
  - app/design/frontend/*/*/template/pagecache/*
  - app/design/frontend/*/*/template/pagecache/**/*

'Component: Paygate':
  - app/code/core/Mage/Paygate/*
  - app/code/core/Mage/Paygate/**/*
  - app/design/adminhtml/default/template/paygate/*
  - app/design/adminhtml/default/template/paygate/**/*
  - app/design/frontend/*/*/template/paygate/*
  - app/design/frontend/*/*/template/paygate/**/*

'Component: Payment':
  - app/code/core/Mage/Payment/*
  - app/code/core/Mage/Payment/**/*
  - app/design/adminhtml/default/template/payment/*
  - app/design/adminhtml/default/template/payment/**/*
  - app/design/frontend/*/*/layout/payment.xml
  - app/design/frontend/*/*/template/payment/*
  - app/design/frontend/*/*/template/payment/**/*

'Component: Paypal':
  - app/code/core/Mage/Paypal/*
  - app/code/core/Mage/Paypal/**/*
  - app/design/adminhtml/default/template/paypal/*
  - app/design/adminhtml/default/template/paypal/**/*
  - app/design/frontend/*/*/layout/paypal.xml
  - app/design/frontend/*/*/layout/bml.xml
  - app/design/frontend/*/*/template/paypal/*
  - app/design/frontend/*/*/template/paypal/**/*

'Component: PaypalUk':
  - app/code/core/Mage/PaypalUk/*
  - app/code/core/Mage/PaypalUk/**/*
  - app/design/frontend/*/*/layout/paypaluk.xml

'Component: Persistant':
  - app/code/core/Mage/Persistant/*
  - app/code/core/Mage/Persistant/**/*
  - app/design/frontend/*/*/layout/persistent.xml
  - app/design/frontend/*/*/template/persistent/*
  - app/design/frontend/*/*/template/persistent/**/*

'Component: Poll':
  - app/code/core/Mage/Poll/*
  - app/code/core/Mage/Poll/**/*
  - app/design/adminhtml/default/template/poll/*
  - app/design/adminhtml/default/template/poll/**/*
  - app/design/frontend/*/*/layout/poll.xml
  - app/design/frontend/*/*/template/poll/*
  - app/design/frontend/*/*/template/poll/**/*

'Component: ProductAlert':
  - app/code/core/Mage/ProductAlert/*
  - app/code/core/Mage/ProductAlert/**/*
  - app/design/frontend/*/*/layout/productalert.xml
  - app/design/frontend/*/*/template/productalert/*
  - app/design/frontend/*/*/template/productalert/**/*

'Component: Rating':
  - app/code/core/Mage/Rating/*
  - app/code/core/Mage/Rating/**/*
  - app/design/adminhtml/default/template/rating/*
  - app/design/adminhtml/default/template/rating/**/*
  - app/design/frontend/*/*/template/rating/*
  - app/design/frontend/*/*/template/rating/**/*

'Component: Reports':
  - app/code/core/Mage/Reports/*
  - app/code/core/Mage/Reports/**/*
  - app/design/adminhtml/default/layout/report.xml
  - app/design/adminhtml/default/template/report/*
  - app/design/adminhtml/default/template/report/**/*
  - app/design/frontend/*/*/layout/reports.xml
  - app/design/frontend/*/*/template/reports/*
  - app/design/frontend/*/*/template/reports/**/*

'Component: Review':
  - app/code/core/Mage/Review/*
  - app/code/core/Mage/Review/**/*
  - app/design/adminhtml/default/template/review/*
  - app/design/adminhtml/default/template/review/**/*
  - app/design/frontend/*/*/layout/review.xml
  - app/design/frontend/*/*/template/review/*
  - app/design/frontend/*/*/template/review/**/*

'Component: Rss':
  - app/code/core/Mage/Rss/*
  - app/code/core/Mage/Rss/**/*
  - app/design/adminhtml/default/layout/rss.xml
  - app/design/frontend/*/*/layout/rss.xml
  - app/design/frontend/*/*/template/rss/*
  - app/design/frontend/*/*/template/rss/**/*

'Component: Rule':
  - app/code/core/Mage/Rule/*
  - app/code/core/Mage/Rule/**/*

'Component: Sales':
  - app/code/core/Mage/Sales/*
  - app/code/core/Mage/Sales/**/*
  - app/design/adminhtml/default/layout/sales.xml
  - app/design/adminhtml/default/template/sales/*
  - app/design/adminhtml/default/template/sales/**/*
  - app/design/frontend/*/*/layout/sales/*
  - app/design/frontend/*/*/layout/sales/**/*
  - app/design/frontend/*/*/layout/sales.xml
  - app/design/frontend/*/*/template/email/*
  - app/design/frontend/*/*/template/email/**/*
  - app/design/frontend/*/*/template/sales/*
  - app/design/frontend/*/*/template/sales/**/*

'Component: SalesRule':
  - app/code/core/Mage/SalesRule/*
  - app/code/core/Mage/SalesRule/**/*

'Component: Sendfriend':
  - app/code/core/Mage/Sendfriend/*
  - app/code/core/Mage/Sendfriend/**/*
  - app/design/frontend/*/*/layout/sendfriend.xml
  - app/design/frontend/*/*/template/sendfriend/*
  - app/design/frontend/*/*/template/sendfriend/**/*

'Component: Shipping':
  - app/code/core/Mage/Shipping/*
  - app/code/core/Mage/Shipping/**/*
  - app/design/frontend/*/*/layout/shipping.xml
  - app/design/frontend/*/*/template/shipping/*
  - app/design/frontend/*/*/template/shipping/**/*

'Component: Sitemap':
  - app/code/core/Mage/Sitemap/*
  - app/code/core/Mage/Sitemap/**/*

'Component: Tag':
  - app/code/core/Mage/Tag/*
  - app/code/core/Mage/Tag/**/*
  - app/design/adminhtml/default/layout/tag.xml
  - app/design/adminhtml/default/template/tag/*
  - app/design/adminhtml/default/template/tag/**/*
  - app/design/frontend/*/*/layout/tag.xml
  - app/design/frontend/*/*/template/tag/*
  - app/design/frontend/*/*/template/tag/**/*

'Component: Tax':
  - app/code/core/Mage/Tax/*
  - app/code/core/Mage/Tax/**/*
  - app/design/adminhtml/default/layout/tax.xml
  - app/design/adminhtml/default/template/tax/*
  - app/design/adminhtml/default/template/tax/**/*
  - app/design/frontend/*/*/template/tax/*
  - app/design/frontend/*/*/template/tax/**/*

'Component: Uploader':
  - app/code/core/Mage/Uploader/*
  - app/code/core/Mage/Uploader/**/*

'Component: Usa':
  - app/code/core/Mage/Usa/*
  - app/code/core/Mage/Usa/**/*
  - app/design/adminhtml/default/template/usa/*
  - app/design/adminhtml/default/template/usa/**/*

'Component: Weee':
  - app/code/core/Mage/Weee/*
  - app/code/core/Mage/Weee/**/*
  - app/design/adminhtml/default/template/weee/*
  - app/design/adminhtml/default/template/weee/**/*
  - app/design/frontend/*/*/layout/weee.xml

'Component: Widget':
  - app/code/core/Mage/Widget/*
  - app/code/core/Mage/Widget/**/*
  - app/design/adminhtml/default/layout/widget.xml
  - app/design/adminhtml/default/template/widget/*
  - app/design/adminhtml/default/template/widget/**/*

'Component: Wishlist':
  - app/code/core/Mage/Wishlist/*
  - app/code/core/Mage/Wishlist/**/*
  - app/design/frontend/*/*/layout/wishlist.xml
  - app/design/frontend/*/*/template/wishlist/*
  - app/design/frontend/*/*/template/wishlist/**/*

'Component: XmlConnect':
  - app/code/core/Mage/XmlConnect/*
  - app/code/core/Mage/XmlConnect/**/*
  - app/design/adminhtml/default/layout/xmlconnect.xml
  - app/design/adminhtml/default/template/xmlconnect/*
  - app/design/adminhtml/default/template/xmlconnect/**/*
  - app/design/frontend/*/*/layout/xmlconnect.xml
  - app/design/frontend/*/*/template/xmlconnect/*
  - app/design/frontend/*/*/template/xmlconnect/**/*

'Component: Cm/RedisSession':
  - app/code/community/Cm/RedisSession/*
  - app/code/community/Cm/RedisSession/**/*

'Component: Phoenix/Moneybookers':
  - app/code/community/Phoenix/Moneybookers/*
  - app/code/community/Phoenix/Moneybookers/**/*
  - app/design/adminhtml/default/layout/moneybookers.xml
  - app/design/adminhtml/default/template/moneybookers/*
  - app/design/adminhtml/default/template/moneybookers/**/*
  - app/design/frontend/*/*/layout/moneybookers.xml
  - app/design/frontend/*/*/template/moneybookers/*
  - app/design/frontend/*/*/template/moneybookers/**/*

# Add Template Labels
'Template : admin':
  - app/design/adminhtml/*
  - app/design/adminhtml/**/*
  - skin/adminhtml/*
  - skin/adminhtml/**/*

'Template : base':
  - app/design/frontend/base/*
  - app/design/frontend/base/**/*
  - skin/frontend/base/*
  - skin/frontend/base/**/*

'Template : default':
  - app/design/frontend/default/*
  - app/design/frontend/default/**/*
  - skin/frontend/default/*
  - skin/frontend/default/**/*

'Template : rwd':
  - app/design/frontend/rwd/*
  - app/design/frontend/rwd/**/*
  - skin/frontend/rwd/*
  - skin/frontend/rwd/**/*

'Template : install':
  - app/design/install/*
  - app/design/install/**/*
  - skin/frontend/install/*
  - skin/frontend/install/**/*

'Translations':
  - app/locale/*.csv
  - app/locale/**/*.csv
  - app/design/adminhtml/default/locale/*.csv

'XML Layout':
  - app/design/adminhtml/*/layout/*
  - app/design/frontend/*/*/layout/*

# Add Documentation Label
'Documentation':
  - '*.md'
