<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php if ($this->getCanDisplayTotalDue()): ?>
<tr>
    <td class="label"><big><strong><?php echo Mage::helper('sales')->__('Total Due', true) ?></strong></big></td>
    <td class="emph"><big><?php echo $this->displayPriceAttribute('total_due', true) ?></big></td>
</tr>
<?php endif ?>
