<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade Magento to newer
 * versions in the future. If you wish to customize Magento for your
 * needs please refer to http://www.magentocommerce.com for more information.
 *
 * @category    Mage
 * @package     Mage_Captcha
 * @copyright   Copyright (c) 2011 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Implementation of Zend_Captcha
 *
 * @category   Mage
 * @package    Mage_Captcha
 * @author     Magento Core Team <core@magentocommerce.com>
 */
class Mage_Captcha_Model_Captcha implements Mage_Captcha_Model_Interface
{
    protected $_model;

    /**
     * Zend captcha constructor
     *
     * @param array $params
     */
    public function __construct($params)
    {
        $type = Mage::helper('captcha')->getConfigNode('type');
        $this->_model = Mage::getModel('captcha/' . $type, $params);
    }

    /**
     * Whether to respect case while checking the answer
     *
     * @return bool
     */
    public function isCaseSensitive()
    {
        return $this->_model->isCaseSensitive();
    }

    /**
     * Generates captcha
     *
     */
    public function generate()
    {
        $this->_model->generate();
    }

    /**
     * Checks whether word entered by user corresponds to the one generated by generate()
     *
     * @param string $word
     * @return void
     */
    public function isCorrect($word)
    {
        return $this->_model->isCorrect($word);
    }

    /**
     * Get captcha image base URL
     *
     * @return string
     */
    public function getImgUrl()
    {
        return $this->_model->getImgUrl();
    }

    /**
     * Return full URL to captcha image
     *
     * @return string
     */
    public function getImgSrc()
    {
        return $this->_model->getImgSrc();
    }


    /**
     * Returns session instance
     *
     * @return Captcha_Zend_Model_Session
     */
    public function getSession()
    {
        return $this->_model->getSession();
    }

    /**
     * Returns Captcha Width
     *
     * @return string
     */
    public function getWidth()
    {
        return $this->_model->getWidth();
    }

    /**
     * Returns Captcha Height
     *
     * @return string
     */
    public function getHeight()
    {
        return $this->_model->getHeight();
    }

    /**
     * Returns Captcha Height
     *
     * @return string
     */
    public function getImgAlt()
    {
        return $this->_model->getImgAlt();
    }

    /**
     * Returns Template Path
     *
     * @return string
     */
    public function getTemplatePath()
    {
        return $this->_model->getTemplatePath();
    }
}
