<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_Payment_Block_Info_Banktransfer
 * @var Mage_Payment_Block_Info_Banktransfer $this
 */
?>
<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php if ($this->getInstructions()): ?>
<table>
    <tbody>
        <tr>
            <td><?php echo nl2br($this->getInstructions()) ?></td>
        </tr>
    </tbody>
</table>
<?php endif ?>
