# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'
  - name: Install OpenMage
    init: |
      BASE_URL="$(echo "$GITPOD_WORKSPACE_URL" | sed s~https://~https://8000-~)"
      HOST_PORT=8000 BASE_URL=$BASE_URL bash dev/gitpod/install.sh
    command: docker ps
    openMode: tab-after
  - name: prepare git
    init: git config core.fileMode false

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    visibility: public
    onOpen: open-preview
