matrix:
  - name: Markdown
    expect_match: false
    apsell:
      mode: en
    dictionary:
      wordlists:
        - .wordlist.txt
      output: wordlist.dic
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.extra:
      - pyspelling.filters.html:
          comments: false
          attributes:
            - alt
          ignores:
            - ':matches(code, pre)'
            - ':matches(.magiclink.magiclink-github.magiclink-mention)'
            - 'a'
            - 'code'
            - 'pre'
            - 'blockquote'
    sources:
      - 'docs/**/*.md'
