<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php
/**
 * Template for block Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Alerts
 *
 * @see Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Alerts
 * @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Alerts $this
 */
?>
<div id="alert_messages_block"><?php echo $this->getMessageHtml() ?></div>
<div>
    <h4 class="icon-head head-edit-form"><?php echo Mage::helper('productalert')->__('Product Alerts') ?></h4>
</div>
<div class="clear"></div>
<?php echo $this->getAccordionHtml() ?>
