<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Template for block Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Alerts
 *
 * @see Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Alerts
 * @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Alerts $this
 */
?>
<div id="alert_messages_block"><?php echo $this->getMessageHtml() ?></div>
<div>
    <h4 class="icon-head head-edit-form"><?php echo Mage::helper('productalert')->__('Product Alerts') ?></h4>
</div>
<div class="clear"></div>
<?php echo $this->getAccordionHtml() ?>
