<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<script type="text/javascript">
//<![CDATA[
    document.addEventListener('uploader:success', function(event) {
        MediabrowserInstance.handleUploadComplete(event.detail.files);
    });
//]]>
</script>
