<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @var Mage_Page_Block_Html $this
 */
?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
<?= $this->getChildHtml('head') ?>
</head>
<body<?= $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?= $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?= $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?= $this->getChildHtml('header') ?>
        <div class="main-container col2-right-layout">
            <div class="main">
                <?= $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">
                    <?= $this->getChildHtml('global_messages') ?>
                    <?= $this->getChildHtml('content') ?>
                </div>
                <div class="col-right sidebar"><?= $this->getChildHtml('right') ?></div>
            </div>
        </div>
        <?= $this->getChildHtml('footer') ?>
        <?= $this->getChildHtml('global_cookie_notice') ?>
        <?= $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?= $this->getAbsoluteFooter() ?>
</body>
</html>
