<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Redirecting...') ?></h1>
</div>
<?php if($this->getMessage()): ?>
    <p><?php echo $this->getMessage() ?></p>
<?php endif ?>
<?php echo $this->getRedirectOutput() ?>
<?php if(!$this->isHtmlFormRedirect()): ?>
    <p><?php echo $this->__('Click <a href="%s">here</a> if nothing has happened', $this->getTargetURL()) ?></p>
<?php endif ?>
