<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Container for product link widget chooser
 *
 * @see Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser_Container
 * @var Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser_Container $this 
 */
?>
<div class="columns">
    <div class="side-col"><?php echo $this->getTreeHtml() ?></div>
    <div class="main-col"><?php echo $this->getGridHtml() ?></div>
</div>
