<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php
/**
 * Container for product link widget chooser
 *
 * @see Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser_Container
 * @var Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser_Container $this 
 */
?>
<div class="columns">
    <div class="side-col"><?php echo $this->getTreeHtml() ?></div>
    <div class="main-col"><?php echo $this->getGridHtml() ?></div>
</div>
