<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */
/** @var Mage_Paypal_Block_Payflow_Advanced_Iframe $this */
?>
<div id="iframe-warning" class="warning-message">
    <?php echo $this->__('Please do not refresh the page until you complete payment.') ?>
</div>
<iframe id="payflow-advanced-iframe" style="display:none;" scrolling="no" frameborder="0"
        src="<?php echo $this->getFrameActionUrl() ?>" height="610" width="100%"></iframe>
<script type="text/javascript">
//<![CDATA[
var headers = $$('#' + checkout.accordion.container.readAttribute('id') + ' .section');
headers.each(function(header) {
    header.removeClassName('allow');
});
$('payflow-advanced-iframe').observe('load', function(){
    $('payflow-advanced-iframe').show();
    $('iframe-warning').show();
    checkout.loadWaiting = 'review';
    checkout.setLoadWaiting(false);
    if (checkout.accordion.currentSection == 'opc-review') {
        $('checkout-review-submit').hide();
    }
});
//]]>
</script>
