<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Paypal_Block_Payflow_Advanced_Form $this
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="form-list">
    <li>
    <?php echo $this->__('You will be required to enter your payment details after you place an order.') ?>
    </li>
</ul>
