<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @var Mage_Paypal_Block_Payflow_Advanced_Form $this
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="form-list">
    <li>
    <?php echo $this->__('You will be required to enter your payment details after you place an order.') ?>
    </li>
</ul>
