<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /* @var $this Mage_Sales_Block_Recurring_Profile_View */ ?>

<div class="order-page">

<!-- title 'n' actions -->
<div class="page-title recurring-profiles-title">
    <h1><?= $this->__('Recurring Profile # %s', $this->escapeHtml($this->getReferenceId())) ?></h1>
</div>
<div class="title-buttons recurring-profiles-title-buttons">
    <?php if ($this->getCanCancel()): ?>
        <button type="button" title="<?= $this->quoteEscape($this->__('Cancel')) ?>" class="button" onclick="if( confirm('<?= $this->getConfirmationMessage() ?>') ) { window.location.href = '<?= $this->getCancelUrl() ?>'; } return false;"><span><span><?= $this->__('Cancel') ?></span></span></button>
    <?php endif ?>
    <?php if ($this->getCanSuspend()): ?>
        <button type="button" title="<?= $this->quoteEscape($this->__('Suspend')) ?>" class="button" onclick="if( confirm('<?= $this->getConfirmationMessage() ?>') ) { window.location.href = '<?= $this->getSuspendUrl() ?>'; } return false;"><span><span><?= $this->__('Suspend') ?></span></span></button>
    <?php endif ?>
    <?php if ($this->getCanActivate()): ?>
        <button type="button" title="<?= $this->quoteEscape($this->__('Activate')) ?>" class="button" onclick="if( confirm('<?= $this->getConfirmationMessage() ?>') ) { window.location.href = '<?= $this->getActivateUrl() ?>'; } return false;"><span><span><?= $this->__('Activate') ?></span></span></button>
    <?php endif ?>
    <?php if ($this->getCanUpdate()):?>
        <button type="button" title="<?= $this->quoteEscape($this->__('Get Update')) ?>" class="button" onclick="if( confirm('<?= $this->getConfirmationMessage() ?>') ) { window.location.href = '<?= $this->getUpdateUrl() ?>'; } return false;"><span><span><?= $this->__('Get Update') ?></span></span></button>
    <?php endif ?>
</div>

<div class="recurring-profiles-messages">
    <?= $this->getMessagesBlock()->toHtml() ?>
</div>

<!-- info tabs -->
<?php $infoTabs = $this->getChildGroup('info_tabs'); ?>
<dl class="order-info">
    <dt><?= $this->__('About This Profile:') ?></dt>
    <dd>
        <ul id="order-info-tabs">
        <?php foreach ($infoTabs as $block): ?>
            <?php if ($this->getObjectData($block, 'is_view_current')): ?>
                <li class="current"><strong><?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></strong></li>
            <?php else: ?>
                <li><a href="<?= $this->escapeHtml($this->getObjectData($block, 'view_url')) ?>"><?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></a></li>
            <?php endif ?>
        <?php endforeach ?>
        </ul>
    </dd>
</dl>

<!-- info blocks in 2 columns -->
<?php for ($i = 1; $i <= 5; $i++):?>
    <?php $infoBlocks = $this->getChildGroup("info_blocks_row_{$i}"); ?>
    <?php if ($infoBlocks):?>
<div class="col2-set order-info-box">
        <?php for ($j = 1; $j <= 2; $j++):?>
            <?php foreach ($infoBlocks as $alias => $block):?>
<?php if ($j == $this->getObjectData($block, 'view_column')):?>
    <div class="col-<?php echo $j?>">
        <div class="info-box">
            <div class="box-title">
                <h2><?= $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></h2>
            </div>
            <div class="box-content">
                <?php $html = $this->getChildHtml($alias) ?>
                <?= ($html ? $html : $this->__('No information available.')) ?>
            </div>
        </div>
    </div>
<?php endif ?>
            <?php endforeach ?>
        <?php endfor ?>
</div>
    <?php endif ?>
<?php endfor ?>

<!-- table data block -->
<?php $table = $this->getChild('table') ?>
<?php if ($table):?>
<div>
    <h2 class="table-caption"><?= $this->escapeHtml($this->getObjectData($table, 'view_label')) ?></h2>
    <?= $this->getChildHtml('table') ?>
</div>
<?php endif ?>

    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->getBackUrl() ?>"><small>&laquo; </small><?= $this->__('Back to Recurring Profiles') ?></a></p>
    </div>
</div>
