<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3><?php echo $this->_getHeader() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml(); ?>
                <?php echo $this->getResetButtonHtml(); ?>
                <?php echo $this->getDeleteButtonHtml(); ?>
                <?php echo $this->getSaveButtonHtml(); ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->_getRenameFormHtml(); ?>
<script type="text/javascript">
    var renameForm = new varienForm('<?php echo $this->_getRenameFormId() ?>');
</script>
