<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Index_Block_Adminhtml_Notifications $this */
?>
<?php $_processes = $this->getProcessesForReindex()?>
<?php if($_processes):?>
<div class="notification-global">
    <strong><?php echo $this->helper('index')->__('One or more of the Indexes are not up to date:') ?></strong>
    <?php echo implode(', ', $_processes)?>.
    <?php echo $this->helper('index')->__('Click here to go to <a href="%s">Index Management</a> and rebuild required indexes.', $this->getManageUrl());?>
</div>
<?php endif ?>
