<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>
<?php
/**
 * "Remember Me" popup template (when click on "What's this?")
 *
 */

/** @var Mage_Core_Block_Template $this */
?>
<div id="window-overlay" class="window-overlay" style="display:none;"></div>
<div id="remember-me-popup" class="remember-me-popup" style="display:none;">
    <div class="remember-me-popup-head">
        <h3>What's this?</h3>
        <a href="#" class="remember-me-popup-close" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close')) ?>"><?php echo $this->__('Close') ?></a>
    </div>
    <div class="remember-me-popup-body">
        <p>Checking &quot;Remember Me&quot; will let you access your shopping cart on this computer when you are logged out</p>
        <div class="remember-me-popup-close-button a-right">
            <a href="#" class="remember-me-popup-close button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close')) ?>"><span><?php echo $this->__('Close') ?></span></a>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    function toggleRememberMepopup(event){
        var popup = document.getElementById('remember-me-popup');
        if(popup){
            var viewportHeight = window.innerHeight,
                docHeight      = document.querySelector('body').offsetHeight,
                height         = docHeight > viewportHeight ? docHeight : viewportHeight;
            popup.style.display = popup.style.display === 'none' ? '' : 'none';
            var overlay = document.getElementById('window-overlay');
            overlay.style.height = height + 'px';
            overlay.style.display = overlay.style.display === 'none' ? '' : 'none';
        }
        event.preventDefault();
        event.stopPropagation();
    }

    document.addEventListener('DOMContentLoaded', function() {
        document.querySelector('body').appendChild(document.getElementById('window-overlay'));
        document.querySelector('body').appendChild(document.getElementById('remember-me-popup'));

        document.querySelectorAll('.remember-me-popup-close').forEach(function(element){
            element.addEventListener('click', toggleRememberMepopup);
        })
        document.querySelectorAll('#remember-me-box a').forEach(function(element) {
            element.addEventListener('click', toggleRememberMepopup);
        });
    });
//]]>
</script>
