<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?= $this->getMessagesBlock()->toHtml() ?>
<div class="page-title">
    <h1><?= $this->__('My Tags') ?></h1>
</div>
<?php if($this->getTags()): ?>
    <p><?= $this->__('Click on a tag to view your corresponding products.') ?></p>
    <ul class="tags-list">
        <?php foreach ($this->getTags() as $_tag): ?>
            <li><a href="<?= $this->getUrl('tag/customer/view', ['tagId' => $_tag->getTagId()]) ?>" style="font-size:<?= $_tag->getRatio()*70+75 ?>%;"><?= $this->escapeHtml($_tag->getName()) ?></a></li>
        <?php endforeach ?>
    </ul>
<?php else: ?>
    <p><?= $this->__('You have not tagged any products yet.') ?></p>
<?php endif ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?= $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?= $this->__('Back') ?></a></p>
</div>
