<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_System_Currency_Rate_Services $this */
?>
<strong><?php echo $this->__('Import Service') ?></strong>
<?php echo $this->getChildHtml('import_services') ?>
