<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <title><?php echo Mage::helper('adminhtml')->__('Log into OpenMage Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('login.css') ?>" media="all" />
    <link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/captcha.js') ?>"></script>
</head>
<body id="page-login">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="" id="loginForm">
                <fieldset class="login-form">
                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                    <h2><?php echo Mage::helper('adminhtml')->__('Forgot your user name or password?') ?></h2>
                    <div id="messages">
                        <?php echo $this->getMessagesBlock()->toHtml() ?>
                    </div>
                    <div class="input-box forgot-password">
                        <label for="email"><?php echo Mage::helper('adminhtml')->__('Email Address:') ?></label><br />
                        <input type="email" id="email" name="email" value="" class="required-entry input-text forgot-password validate-email" autofocus="autofocus" style="width:461px;" />
                    </div>
                    <?php echo $this->getChildHtml('form.additional.info') ?>
                    <div class="clear"></div>
                    <div class="form-buttons">
                        <a class="left" href="<?php echo $this->getUrl('adminhtml', ['_nosecret' => true]) ?>">&laquo; <?php echo Mage::helper('adminhtml')->__('Back to Login') ?></a>
                        <input type="submit" class="forgot-password form-button" value="<?php echo Mage::helper('adminhtml')->__('Retrieve Password') ?>">
                    </div>
                </fieldset>
                <p class="legal"><?php echo Mage::helper('adminhtml')->__('Powered by OpenMage') ?></p>
            </form>
            <div class="bottom"></div>
            <script type="text/javascript">
                var loginForm = new varienForm('loginForm');
            </script>
        </div>
    </div>
</body>
</html>
