<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Paygate_Block_Authorizenet_Info_Cc
 * @var Mage_Paygate_Block_Authorizenet_Info_Cc $this
 */
?>
<?php if (!$this->getHideTitle()): ?>
    <p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>
<?php endif ?>

<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;
?>

<dl class="cards-list">
<?php foreach ($cards as $key => $card): ?>
    <?php if ($showCount): ?>
        <dt><?php echo sprintf($this->__('Credit Card %s'), $key + 1); ?></dt>
    <?php endif ?>

    <dd <?php if ($showCount):?> class="offset"<?php endif ?>>
    <table class="info-table">
        <tbody>
        <?php foreach ($card as $_label => $_value):?>
        <tr>
            <th><?php echo $this->escapeHtml($_label)?>:</th>
            <td><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></td>
        </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    </dd>
<?php endforeach ?>
</dl>
