<?php
/**
 * OpenMage
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_modern
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div style=" float:left; width:653px;">
    <img src="<?php echo $this->getSkinUrl('images/media/home_co_main.jpg');?>" alt="" />
</div>
<div style="float:right; width:280px;">
    <div style="margin:0 0 10px;" ><img src="<?php echo $this->getSkinUrl('images/media/home_co_tr.gif');?>" alt="" /></div>
    <div><img src="<?php echo $this->getSkinUrl('images/media/home_co_br.gif');?>" alt="" /></div>
</div>
<div class="clearer"></div>
<div style="margin:10px 0 0;"><img src="<?php echo $this->getSkinUrl('images/media/home_co_bottom.gif');?>" alt="" /></div>
