<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Centinel_Block_Authentication_Complete
 * @var Mage_Centinel_Block_Authentication_Complete $this
 */
?>
<?php if ($this->getIsProcessed()):?>
    <?php if ($this->getIsSuccess()):?>
        <h1><?php echo $this->__('Verification Successful');?></h1>
        <p><?php echo $this->__('Please continue with placing order.')?></p>
    <?php else: ?>
        <h4><?php echo $this->__('Verification Failed');?></h4>
        <p><?php echo $this->__('The card has failed verification with the issuer bank.')?> <strong><?php echo $this->__('Order cannot be placed.')?></strong></p>
    <?php endif ?>
<?php else: ?>
    <h4><?php echo $this->__('Verification cannot be processed');?></h4>
    <p><?php echo $this->__('There has been wrong payment information submitted or time limit has expired. Please, try again.')?> <strong><?php echo $this->__('Order cannot be placed.')?></strong></p>
<?php endif ?>
