<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<script type="text/javascript">
//<![CDATA[
function setSettings(urlTemplate, typeElement, packageThemeElement) {
    if (editForm.validator && editForm.validator.validate()) {
        typeElement = $F(typeElement).replace(/\//g, '-');
        packageThemeElement = $F(packageThemeElement).split(/\//g);

        setLocation(new Template(urlTemplate, /(^|.|\r|\n)({{(\w+)}})/).evaluate({
            'type': typeElement,
            'package': packageThemeElement[0],
            'theme': packageThemeElement[1]
        }));
    } else {
        return false;
    }
}

function saveAndContinueEdit() {
    editForm.submit($('edit_form').action + 'back/edit/');
}
//]]>
</script>
