<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Api_Tab_Rolesusers
 * @var Mage_Adminhtml_Block_Api_Tab_Rolesusers $this
 */
?>
<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Role Users') ?></h4>
<?php echo $this->_getGridHtml() ?>
