<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<script type="text/javascript">
function saveAndContinueEdit(urlTemplate) {
        var template = new Template(urlTemplate, /(^|.|\r|\n)({{(\w+)}})/);
        var url = template.evaluate({tab_id:customer_info_tabsJsTabs.activeTab.id});
        editForm.submit(url);
}
</script>
