<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<script type="text/javascript">
function saveAndContinueEdit(urlTemplate) {
        var template = new Template(urlTemplate, /(^|.|\r|\n)({{(\w+)}})/);
        var url = template.evaluate({tab_id:customer_info_tabsJsTabs.activeTab.id});
        editForm.submit(url);
}
</script>
