<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Api2_Block_Adminhtml_Attribute_Buttons $this */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3 class="icon-head head-permissions-role">
                    <?php echo $this->getCaption() ?>
                </h3>
            </td>
            <td class="form-buttons">
            <?php echo $this->getBackButtonHtml() ?>
            <?php echo $this->getResetButtonHtml() ?>
            <?php echo $this->getDeleteButtonHtml() ?>
            <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<form action="<?php echo $this->getUrl('*/*/save') ?>" method="post" id="role_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
//<![CDATA[
    var roleForm = new varienForm('role_edit_form');
//]]>
</script>
