<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Core_Block_Template
 * @var Mage_Core_Block_Template $this
 */
?>
<script type="text/javascript">
//<![CDATA[
<?php
    /** @var Mage_Api2_Block_Adminhtml_Roles_Tab_Users $myBlock */
    $myBlock = $this->getLayout()->getBlock('adminhtml.role.edit.tab.users');
    $name = $myBlock->getJsObjectName();
?>
    <?php if (is_object($myBlock) && $name && !$myBlock->isHidden()): ?>
    var checkBoxes = <?php echo $myBlock->getUsers(true) ?> || {};
    var warning = false;
    if (Object.keys(checkBoxes).length > 0) {
        warning = true;
    }
    document.getElementById('in_role_users').value = new URLSearchParams(checkBoxes).toString();

    function registerUserRole(grid, element, checked)
    {
        if (checked) {
            checkBoxes[element.value] = 0;
        } else {
            delete checkBoxes[element.value];
        }
        document.getElementById('in_role_users').value = new URLSearchParams(checkBoxes).toString();
        grid.reloadParams = {'in_role_users[]':Object.keys(checkBoxes)};
    }

    function roleUsersRowClick(grid, event)
    {
        var trElement = event.target.closest('tr');
        var isInput   = event.target.tagName == 'INPUT';
        if (trElement) {
            var checkbox = trElement.querySelectorAll('input');
            if(checkbox[0]){
                var checked = isInput ? checkbox[0].checked : !checkbox[0].checked;
                if (checked) {
                    checkbox[0].checked = true;
                    if ( confirm("<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Warning!\r\nThis action will remove this user from already assigned role\r\nAre you sure?')) ?>") ) {
                        checkBoxes[checkbox[0].value] = checked;
                        varienElementMethods.setHasChanges.call(checkbox[0]);
                    } else {
                        checkbox[0].checked = false;
                    }
                    warning = false;
                } else {
                    delete checkBoxes[checkbox[0].value];
                }

                document.getElementById('in_role_users').value = new URLSearchParams(checkBoxes).toString();
                grid.reloadParams = {'in_role_user[]':Object.keys(checkBoxes)};
            }
        }
    }

    function roleUsersRowInit(grid, row)
    {
        var checkbox = row.getElementsByClassName('checkbox')[0];
        if (checkbox) {
            if (checkbox.checked) {
                checkBoxes[checkbox.value] = checkbox.checked;
            } else {
                delete checkBoxes[checkbox.value];
            }

            document.getElementById('in_role_users').value = new URLSearchParams(checkBoxes).toString();
            grid.reloadParams = {'in_role_user[]':Object.keys(checkBoxes)};
        }
    }

    function myhandler(o)
    {
        if (Object.keys(checkBoxes).length > 0) {
            if (!confirm("<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Warning!\r\nThis action will remove those users from already assigned roles\r\nAre you sure?')) ?>") ) {
                o.checked = !o.checked;
            } else {
                Object.entries(checkBoxes).forEach(function(el){
                    el.checked = o.checked;
                });
                return false;
            }
            warning = false;
        }

        document.getElementById('in_role_users').value = new URLSearchParams(checkBoxes).toString();
        //grid.reloadParams = {'in_role_user[]':Object.keys(checkBoxes)};
    }

        <?php echo $name ?>.rowClickCallback = roleUsersRowClick;
        <?php echo $name ?>.initRowCallback = roleUsersRowInit;
        <?php echo $name ?>.checkboxCheckCallback = registerUserRole;
        <?php echo $name ?>.checkCheckboxes = myhandler;
        <?php echo $name ?>.rows.forEach(function(row){roleUsersRowInit(<?php echo $name ?>, row)});
    document.getElementById('in_role_users_old').value = document.getElementById('in_role_users').value;
        <?php endif ?>
//]]>
</script>
