#!/bin/bash
#ddev-generated
## Description: Use Cypress in "runner" mode.
##
## Usage: cypress-run [arguments]
## Example: "ddev cypress-run --browser chrome"

cypress run --config .cypress.config.js "$@"
