<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Checkout_Block_Total_Tax
 * @var Mage_Checkout_Block_Total_Tax $this
 */
?>
<?php global $taxIter;
$taxIter++; ?>
<?php if ($this->helper('tax')->displayFullSummary() && $this->getTotal()->getValue() != 0): ?>
<?php $isTop = 1; ?>
            <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
                <?php if (isset($info['hidden']) && $info['hidden']) {
                    continue;
                } ?>
                <?php $percent = $info['percent']; ?>
                <?php $amount = $info['amount']; ?>
                <?php $rates = $info['rates']; ?>
                <?php $isFirst = 1; ?>

                <?php foreach ($rates as $rate): ?>
                <tr class="summary-details-<?php echo $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif; ?>" style="display:none;">
                    <td class="a-right" style="<?php echo $this->getTotal()->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
                        <?php echo $this->escapeHtml($rate['title']); ?>
                        <?php if (!is_null($rate['percent'])): ?>
                            (<?php echo (float) $rate['percent']; ?>%)
                        <?php endif ?>
                        <br />
                    </td>
                    <?php if ($isFirst): ?>
                        <td rowspan="<?php echo count($rates); ?>" class="a-right" style="<?php echo $this->getTotal()->getStyle() ?>">
                            <?php echo $this->helper('checkout')->formatPrice($amount); ?>
                        </td>
                    <?php endif ?>
                </tr>
                <?php $isFirst = 0; ?>
                <?php $isTop = 0; ?>
                <?php endforeach ?>
            <?php endforeach ?>
<?php endif ?>
<tr<?php if ($this->helper('tax')->displayFullSummary() && $this->getTotal()->getValue() != 0): ?> class="summary-total" onclick="expandDetails(this, '.summary-details-<?php echo $taxIter;?>')"<?php endif ?>>
    <td class="a-right" colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <div class="summary-collapse"><?php echo $this->getTotal()->getTitle() ?></div>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle() ?>
        <?php endif ?>
    </td>
    <td class="a-right" style="<?php echo $this->getTotal()->getStyle() ?>">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
