<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Paygate_Block_Authorizenet_Form_Cc
 * @var Mage_Paygate_Block_Authorizenet_Form_Cc $this
 */
?>
<?php $_formMessage = $this->getPartialAuthorizationFormMessage(); ?>
<?php $_isPartialAuthorization = $this->isPartialAuthorization(); ?>
<?php if ($_isPartialAuthorization || $_formMessage): ?>
    <div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>_before" style="display:none;">
        <?php if ($_formMessage): ?>
        <?php echo $this->showNoticeMessage($_formMessage) ?>
        <?php endif ?>

        <?php if ($_isPartialAuthorization): ?>
                <?php echo $this->getChildHtml('cards') ?>
                <div class="release-amounts">
                    <?php echo $this->getCancelButtonHtml()?>
                    <p class="note"><?php echo $this->__('To cancel pending authorizations and release amounts that have already been processed during this payment, click Cancel.') ?></p>
                </div>
                <?php echo $this->showNoticeMessage($this->__('Please enter another credit card number to complete your purchase.')) ?>
                    <script type="text/javascript">
                    //<![CDATA[
                    function cancelPaymentAuthorizations(){
                        new Ajax.Request('<?php echo $this->getAdminCancelUrl() ?>', {
                            onSuccess : function(transport) {
                                try{
                                    response = eval('(' + transport.responseText + ')');
                                } catch (e) {
                                    response = {};
                                }

                                if (response.success) {
                                    order.loadArea(['billing_method','totals'], true, []);
                                } else {
                                    var msg = response.error_message;
                                    if (msg) {
                                        alert(msg);
                                    }
                                }
                            }
                        });
                    }
                    <?php if ($_message = $this->getPartialAuthorizationConfirmationMessage()): ?>
                    if (!confirm('<?php echo Mage::helper('core')->jsQuoteEscape($_message) ?>')) {
                        cancelPaymentAuthorizations();
                    }
                    <?php endif ?>
                    //]]>
                    </script>
        <?php endif ?>
    </div>
<?php endif ?>
<?php echo $this->getChildHtml('method_form_block') ?>
