<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Downloadable_Block_Adminhtml_Catalog_Product_Edit_Tab_Downloadable
 * @var Mage_Downloadable_Block_Adminhtml_Catalog_Product_Edit_Tab_Downloadable $this
 */
?>
<script type="text/javascript">
//<![CDATA[>

var uploaderTemplate = '<div class="no-display" id="[[idName]]-template">' +
                            '<div id="{{id}}-container" class="file-row file-row-narrow">' +
                                '<span class="file-info">' +
                                    '<span class="file-info-name">{{name}}</span>' +
                                    ' ' +
                                    '<span class="file-info-size">{{size}}</span>' +
                                '</span>' +
                                '<span class="progress-text"></span>' +
                                '<div class="clear"></div>' +
                            '</div>' +
                        '</div>';

var fileListTemplate = '<span class="file-info">' +
                            '<span class="file-info-name">{{name}}</span>' +
                            ' ' +
                            '<span class="file-info-size">({{size}})</span>' +
                        '</span>';

var Downloadable = {
    uploaderObj : new Map(),
    objCount : 0,
    setUploaderObj : function(type, key, obj){
        if (!this.uploaderObj.get(type)) {
            this.uploaderObj.set(type, new Map());
        }
        this.uploaderObj.get(type).set(key, obj);
    },
    getUploaderObj : function(type, key){
        try {
            return this.uploaderObj.get(type).get(key);
        } catch (e) {
            try {
                console.log(e);
            } catch (e2) {
                alert(e.name + '\n' + e.message);
            }
        }
    },
    unsetUploaderObj : function(type, key){
        try {
            this.uploaderObj.get(type).delete(key);
        } catch (e) {
            try {
                console.log(e);
            } catch (e2) {
                alert(e.name + '\n' + e.message);
            }
        }
    },
    massUploadByType : function(type){
        try {
            this.uploaderObj.get(type).forEach(function(value, key){
                var container = value.elements.container.closest('tr');
                if (container.style.display !== 'none' && !container.classList.contains('no-display')) {
                    value.upload();
                } else {
                    Downloadable.unsetUploaderObj(type, key);
                }
            });
        } catch (e) {
            try {
                console.log(e);
            } catch (e2) {
                alert(e.name + '\n' + e.message);
            }
        }
    }
};

Downloadable.FileUploader = Class.create();
Downloadable.FileUploader.prototype = {
    type : null,
    key : null, //key, identifier of uploader obj
    elmContainer : null, //insert Flex object and templates to elmContainer
    fileValueName : null, //name of field of JSON data of saved file
    fileValue : null,
    idName : null, //id name of elements for unique uploader
    uploaderText: uploaderTemplate,
    uploaderSyntax : /(^|.|\r|\n)(\[\[(\w+)\]\])/,
    uploaderObj : new Map(),
    config : null,
    initialize: function (type, key, elmContainer, fileValueName, fileValue ,idName, config) {
        this.type = type;
        this.key = key;
        this.elmContainer = elmContainer;
        this.fileValueName = fileValueName;
        this.fileValue = fileValue;
        this.idName = idName;
        this.config = config;
        uploaderTemplate = new Template(this.uploaderText, this.uploaderSyntax);
        <?php if (!$this->isReadonly()):?>
        elmContainer.insertAdjacentHTML(
            'afterbegin',
            uploaderTemplate.evaluate({
                    'idName' : this.idName,
                    'fileValueName' : this.fileValueName,
                    'uploaderObj' : 'Downloadable.getUploaderObj(\''+this.type+'\', \''+this.key+'\')'
                })
        );
        if (document.getElementById(this.idName+'_save')) {
            document.getElementById(this.idName+'_save').value = this.fileValue.toJSON
               ? this.fileValue.toJSON()
               : Object.toJSON(this.fileValue);
        }
        var uploaderConfig = (typeof this.config === 'string' ? JSON.parse(this.config) : this.config);
        Downloadable.setUploaderObj(
            this.type,
            this.key,
            new Uploader(uploaderConfig)
        );
        if (varienGlobalEvents) {
            varienGlobalEvents.attachEventHandler('tabChangeBefore', Downloadable.getUploaderObj(type, key).onContainerHideBefore);
        }
        new Downloadable.FileList(this.idName, Downloadable.getUploaderObj(type, key));
        <?php endif ?>
    }
}

Downloadable.FileList = Class.create();
Downloadable.FileList.prototype = {
    file: [],
    containerId: '',
    container: null,
    uploader: null,
    fileListTemplate: fileListTemplate,
    templatePattern : /(^|.|\r|\n)({{(\w+)}})/,
    listTemplate : null,
    initialize: function (containerId, uploader) {
        this.containerId  = containerId,
        this.container = document.getElementById(this.containerId);
        this.uploader = uploader;
        document.on('uploader:fileSuccess', function(event) {
            var memo = event.memo;
            if(this._checkCurrentContainer(memo.containerId)) {
                this.handleUploadComplete([{response: memo.response}]);
                this.handleButtonsSwap();
            }
        }.bind(this));
        document.on('uploader:fileError', function(event) {
            var memo = event.memo;
            if(this._checkCurrentContainer(memo.containerId)) {
                this.handleButtonsSwap();
            }
        }.bind(this));
        document.on('upload:simulateDelete', this.handleFileRemoveAll.bind(this));
        document.on('uploader:simulateNewUpload', this.handleFileNew.bind(this));
        this.file = JSON.parse(this.getElement('save').value);
        this.listTemplate = new Template(this.fileListTemplate, this.templatePattern);
        this.updateFiles();
        this.uploader.onFileRemoveAll = this.handleFileRemoveAll.bind(this);
        this.uploader.onFileSelect = this.handleFileSelect.bind(this);
    },

    _checkCurrentContainer: function (child) {
        return document.getElementById(this.containerId).querySelector('#' + child);
    },

    handleFileRemoveAll: function(e) {
        if(e.memo && this._checkCurrentContainer(e.memo.containerId)) {
            document.getElementById(this.containerId+'-new').style.display = 'none';
            document.getElementById(this.containerId+'-old').style.display = '';
            this.handleButtonsSwap();
        }
    },
    handleFileNew: function (e) {
        if(e.memo && this._checkCurrentContainer(e.memo.containerId)) {
            document.getElementById(this.containerId + '-new').style.display = '';
            document.getElementById(this.containerId + '-old').style.display = 'none';
            this.handleButtonsSwap();
        }
    },
    handleButtonsSwap: function () {
        [document.getElementById(this.containerId+'-browse'), document.getElementById(this.containerId+'-delete')].forEach(function(el) {
            if (el) el.style.display = el.style.display === 'none' ? '' : 'none';
        });
    },
    handleFileSelect: function() {
        document.getElementById(this.containerId+'_type').checked = true;
    },
    getElement: function (name) {
        return document.getElementById(this.containerId + '_' + name);
    },
    handleUploadComplete: function (files) {
        files.forEach(function(item) {
           try { JSON.parse(item.response); } catch(e) {
                try {
                    console.log(item.response);
                } catch (e2) {
                    alert(item.response);
                }
               return;
           }
           var response = JSON.parse(item.response);
           if (response.error) {
               return;
           }
           var newFile = {};
           newFile.file = response.file;
           newFile.name = response.name;
           newFile.size = response.size;
           newFile.status = 'new';
           this.file[0] = newFile;
        }.bind(this));
        this.updateFiles();
    },
    updateFiles: function() {
        this.getElement('save').value = this.file.toJSON
            ? this.file.toJSON()
            : Object.toJSON(this.file);
        this.file.forEach(function(row){
            row.size = this.uploader.formatSize(row.size);
            document.getElementById(this.containerId + '-old').innerHTML = this.listTemplate.evaluate(row);
            document.getElementById(this.containerId + '-new').style.display = 'none';
            document.getElementById(this.containerId + '-old').style.display = '';
        }.bind(this));
    }
}

var alertAlreadyDisplayed = false;

Validation.addAllThese([
    ['validate-downloadable-file', 'Please upload a file.', function(v,element) {
            linkType = element.parentNode.querySelector('input[value="file"]');
            if (linkType.checked && (v == '' || v == '[]')) {
                newFileContainer = element.parentNode.querySelector('div.new-file');
                if (!alertAlreadyDisplayed && (!newFileContainer.innerHTML.trim() || newFileContainer.style.display != 'none')) {
                    alertAlreadyDisplayed = true;
                    alert('<?php echo $this->jsQuoteEscape($this->__('There are files that were selected but not uploaded yet. Please upload or remove them first'));?>');
                }
                return false;
            }
            return true;
        }]
    ]);

Validation.addAllThese([
    ['validate-downloadable-url', 'Please specify Url.', function(v,element) {
            linkType = element.parentNode.querySelector('input[value="url"]');
            if (linkType.checked && v == '') {
                return false;
            }
            return true;
        }]
    ]);
//]]>
</script>

<div id="alert_messages_block"><?php echo $this->getMessageHtml() ?></div>

<div class="entry-edit">
<?php echo $this->getChildHtml('accordion') ?>
</div>
<div style="display:none">
    <div id="custom-advice-container"></div>
</div>
<?php if ($this->isReadonly()): ?>
<script type="text/javascript">
document.getElementById('downloadableInfo').querySelectorAll('input, select, textarea, button').forEach(function (item){
    item.disabled = true;
    if (item.tagName.toLowerCase() == 'button') {
        item.classList.add('disabled');
    }
});
</script>
<?php endif ?>
<!--
<div><input type="hidden" name="affect_downloadable_information" value="1" /></div>
-->
