<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<script type="text/javascript">
<!--
<?php $myBlock = $this->getLayout()->getBlock('roleUsersGrid'); ?>
<?php if( is_object($myBlock) && $myBlock->getJsObjectName() ): ?>
    var checkBoxes = <?php echo $myBlock->_getUsers(true) ?> || {};
    var warning = false;
    if (Object.keys(checkBoxes).length > 0) {
        warning = true;
    }
    document.getElementById('in_role_user').value = new URLSearchParams(checkBoxes).toString();

    function registerUserRole(grid, element, checked)
    {
        if (checked) {
            checkBoxes[element.value] = 0;
        } else {
            delete checkBoxes[element.value];
        }
        document.getElementById('in_role_user').value = new URLSearchParams(checkBoxes).toString();
        grid.reloadParams = {'in_role_user[]':Object.keys(checkBoxes)};
    }

    function roleUsersRowClick(grid, event)
    {
        var trElement = event.target.closest('tr');
        var isInput   = event.target.tagName == 'INPUT';
        if (trElement) {
            var checkbox = trElement.querySelectorAll('input');
            if(checkbox[0]){
                var checked = isInput ? !checkbox[0].checked : checkbox[0].checked;
                if (checked) {
                    if ( confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Warning!\r\nThis action will remove this user from already assigned role\r\nAre you sure?')) ?>') ) {
                        checkbox[0].checked = false;
                        delete checkBoxes[checkbox[0].value];
                        varienElementMethods.setHasChanges.call(checkbox[0]);
                    } else {
                        checkbox[0].checked = true;
                    }
                } else {
                    checkbox[0].checked = true;
                    checkBoxes[checkbox[0].value] = true;
                }

                document.getElementById('in_role_user').value = new URLSearchParams(checkBoxes).toString();
                grid.reloadParams = {'in_role_user[]':Object.keys(checkBoxes)};
            }
        }
    }

    function roleUsersRowInit(grid, row)
    {
        var checkbox = row.getElementsByClassName('checkbox')[0];
        if (checkbox) {
            if (checkbox.checked) {
                checkBoxes[checkbox.value] = checkbox.checked;
            } else {
                delete checkBoxes[checkbox.value];
            }

            document.getElementById('in_role_user').value = new URLSearchParams(checkBoxes).toString();
            grid.reloadParams = {'in_role_user[]':Object.keys(checkBoxes)};
        }
    }

    function massSelectUsers(allCheckbox)
    {
        if (!allCheckbox.checked && Object.keys(checkBoxes).length > 0) {
            if (!confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Warning!\r\nThis action will remove those users from already assigned roles\r\nAre you sure?')) ?>') ) {
                allCheckbox.checked = false;
                return false;
            }
        }
        <?php echo $myBlock->getJsObjectName() ?>.rows.forEach(function(row)
        {
            row.getElementsByClassName('checkbox')[0].checked = allCheckbox.checked;
            roleUsersRowInit(<?php echo $myBlock->getJsObjectName() ?>, row);
        });
    }

<?php echo $myBlock->getJsObjectName() ?>.rowClickCallback = roleUsersRowClick;
<?php echo $myBlock->getJsObjectName() ?>.initRowCallback = roleUsersRowInit;
<?php echo $myBlock->getJsObjectName() ?>.checkboxCheckCallback = registerUserRole;
<?php echo $myBlock->getJsObjectName() ?>.checkCheckboxes = massSelectUsers;
<?php echo $myBlock->getJsObjectName() ?>.rows.forEach(function(row){roleUsersRowInit(<?php echo $myBlock->getJsObjectName() ?>, row)});
    document.getElementById('in_role_user_old').value = document.getElementById('in_role_user').value;
<?php endif ?>
//-->
</script>
