<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_System_Currency $this */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-system-currency"><?php echo $this->getHeader() ?></h3></td>
            <td class="form-buttons">
                <form action="<?php echo $this->getImportFormAction() ?>" method="post">
                    <?php echo $this->getBlockHtml('formkey')?>
                    <?php echo $this->getServicesHtml() ?>
                    <?php echo $this->getImportButtonHtml() ?>
                </form>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getRatesMatrixHtml() ?>
