<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_item = $this->getItem() ?>
<?php $_order = $this->getItem()->getOrder() ?>
<tbody>
    <tr>
        <td class="cell-content product-info">
        <p class="product-name"><?= $this->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $this->__('SKU') ?>: <?= $this->escapeHtml($this->getSku($_item)) ?></p>
            <?php if ($this->getItemOptions()): ?>
                <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
                            <dt><strong><em><?= $option['label'] ?></em></strong></dt>
                            <dd style="margin:0; padding:0 0 0 9px;">
                                <?= nl2br($option['value']) ?>
                            </dd>
                        <?php endforeach ?>
                    </dl>
                <?php endif ?>
                <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif ?>
                <?= $this->escapeHtml($_item->getDescription()) ?>
            </td>
            <td class="cell-content align-center"><?= $_item->getQtyOrdered()*1 ?></td>
            <td class="cell-content align-right">
                <?php if ($this->helper('tax')->displaySalesPriceExclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                    <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                        <span class="label"><?= Mage::helper('tax')->__('Excl. Tax') ?>:</span>
                    <?php endif ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'email', $_order->getStore())): ?>
                        <?= $_order->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()) ?>
                    <?php else: ?>
                        <?= $_order->formatPrice($_item->getRowTotal()) ?>
                    <?php endif ?>


                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                        <br />
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount'],true,true) ?></span><br />
                                <?php endforeach ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="nobr"><small><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount'],true,true) ?></small></span><br />
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount'],true,true) ?></span><br />
                                <?php endforeach ?>
                            </small>
                        <?php endif ?>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                            <br />
                            <span class="nobr"><?= Mage::helper('weee')->__('Total') ?>:<br /> <?= $_order->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()) ?></span>
                        <?php endif ?>
                    <?php endif ?>
                <?php endif ?>


                <?php if ($this->helper('tax')->displaySalesPriceInclTax($_order->getStore()) || $this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                    <?php if ($this->helper('tax')->displaySalesBothPrices($_order->getStore())): ?>
                        <br /><span class="label"><?= Mage::helper('tax')->__('Incl. Tax') ?>:</span>
                    <?php endif ?>
                    <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'email', $_order->getStore())): ?>
                        <?= $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?>
                    <?php else: ?>
                        <?= $_order->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
                    <?php endif ?>
                    <?php if (Mage::helper('weee')->getApplied($_item)): ?>
                        <br />
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'email', $_order->getStore())): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount_incl_tax'],true,true) ?></span><br />
                                <?php endforeach ?>
                            </small>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="nobr"><small><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount_incl_tax'],true,true) ?></small></span><br />
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'email', $_order->getStore())): ?>
                            <small>
                                <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                    <span class="nobr"><?= $tax['title'] ?>: <?= $_order->formatPrice($tax['row_amount_incl_tax'],true,true) ?></span><br />
                                <?php endforeach ?>
                            </small>
                        <?php endif ?>

                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'email', $_order->getStore())): ?>
                            <span class="nobr"><?= Mage::helper('weee')->__('Total incl. tax') ?>:<br /> <?= $_order->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?></span>
                        <?php endif ?>
                    <?php endif ?>
                <?php endif ?>
            </td>
        </tr>
    <?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('giftmessage/message')->getGiftMessage($_item->getGiftMessageId())): ?>
        <tr>
            <td colspan="4" style=" border-bottom:2px solid #CCCCCC; padding:3px 9px;">
                <strong style="color:#444444; font-size:11px;"><?= $this->__('Gift Message') ?></strong>
                <?= $this->__('From:') ?> <?= $this->escapeHtml($_giftMessage->getSender()) ?><br />
                <?= $this->__('To:') ?> <?= $this->escapeHtml($_giftMessage->getRecipient()) ?><br />
                <strong><?= $this->__('Message:') ?></strong><br /><?= $this->escapeHtml($_giftMessage->getMessage()) ?>
            </td>
        </tr>
    <?php endif ?>
</tbody>
