<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>

<?php
/**
 * @var Mage_Page_Block_Js_Translate $this
 */
?>
<?php
$_data = [
    'Please select an option.' => $this->__('Please select an option.'),
    'This is a required field.' => $this->__('This is a required field.'),
    'Please enter a valid number in this field.' => $this->__('Please enter a valid number in this field.'),
    'Please use numbers only in this field. Please avoid spaces or other characters such as dots or commas.' => $this->__('Please use numbers only in this field. Please avoid spaces or other characters such as dots or commas.'),
    'Please use letters only (a-z) in this field.' => $this->__('Please use letters only (a-z) in this field.'),
    'Please use in this field only "a-z,0-9,_".' => $this->__('Please use in this field only "a-z,0-9,_".'),
    'Please use only letters (a-z) or numbers (0-9) only in this field. No spaces or other characters are allowed.' => $this->__('Please use only letters (a-z) or numbers (0-9) only in this field. No spaces or other characters are allowed.'),
    'Please use only letters (a-z) or numbers (0-9) or spaces and # only in this field.' => $this->__('Please use only letters (a-z) or numbers (0-9) or spaces and # only in this field.'),
    'Please enter a valid phone number. For example (123) 456-7890 or 123-456-7890.' => $this->__('Please enter a valid phone number. For example (123) 456-7890 or 123-456-7890.'),
    'Please enter a valid date.' => $this->__('Please enter a valid date.'),
    'Please enter a valid email address. For example johndoe@domain.com.' => $this->__('Please enter a valid email address. For example johndoe@domain.com.'),
    'Please enter 6 or more characters.' => $this->__('Please enter 6 or more characters.'),
    'Please make sure your passwords match.' => $this->__('Please make sure your passwords match.'),
    'Please enter a valid URL. http:// is required' => $this->__('Please enter a valid URL. http:// is required'),
    'Please enter a valid URL. For example http://www.example.com or www.example.com' => $this->__('Please enter a valid URL. For example http://www.example.com or www.example.com'),
    'Please enter a valid social security number. For example 123-45-6789.' => $this->__('Please enter a valid social security number. For example 123-45-6789.'),
    'Please enter a valid zip code. For example 90602 or 90602-1234.' => $this->__('Please enter a valid zip code. For example 90602 or 90602-1234.'),
    'Please enter a valid zip code.' => $this->__('Please enter a valid zip code.'),
    'Please use this date format: dd/mm/yyyy. For example 17/03/2006 for the 17th of March, 2006.' => $this->__('Please use this date format: dd/mm/yyyy. For example 17/03/2006 for the 17th of March, 2006.'),
    'Please enter a valid $ amount. For example $100.00.' => $this->__('Please enter a valid $ amount. For example $100.00.'),
    'Please select one of the above options.' => $this->__('Please select one of the above options.'),
    'Please select one of the options.' => $this->__('Please select one of the options.'),
    'Please select State/Province.' => $this->__('Please select State/Province.'),
    'Please enter valid password.' => $this->__('Please enter valid password.'),
    'Please enter a number greater than 0 in this field.' => $this->__('Please enter a number greater than 0 in this field.'),
    'Please enter a valid credit card number.' => $this->__('Please enter a valid credit card number.'),
    'Please wait, loading...' => $this->__('Please wait, loading...')
];
?>
<script type="text/javascript">
    var Translator = new Translate(<?php echo Zend_Json::encode($_data) ?>);
</script>
