<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     rwd_default
 */

/**
 * @see Mage_Core_Block_Template
 * @var Mage_Core_Block_Template $this
 */
?>
<table class="table-totals" cellpadding="0" cellspacing="0" border="0">
    <tr>
        <td class="padding-totals">
            <table cellpadding="0" cellspacing="0" border="0">
                <?php echo $this->getChildHtml(); ?>
            </table>
        </td>
    </tr>
</table>
