<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Core_Block_Template
 * @var Mage_Core_Block_Template $this
 */
?>
<table class="table-totals" cellpadding="0" cellspacing="0" border="0">
    <tr>
        <td class="padding-totals">
            <table cellpadding="0" cellspacing="0" border="0">
                <?php echo $this->getChildHtml(); ?>
            </table>
        </td>
    </tr>
</table>
