<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Payment_Block_Form_Purchaseorder
 * @var Mage_Payment_Block_Form_Purchaseorder $this
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="po_number"><?php echo Mage::helper('payment')->__('Purchase Order Number') ?> <span class="required">*</span></label><br/>
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('payment')->__('Purchase Order Number')) ?>" class="required-entry input-text" value="<?php echo $this->getInfoData('po_number') ?>"/>
        </div>
    </li>
</ul>
