<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Payment_Block_Form_Purchaseorder
 * @var Mage_Payment_Block_Form_Purchaseorder $this
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <label for="po_number"><?php echo Mage::helper('payment')->__('Purchase Order Number') ?> <span class="required">*</span></label><br/>
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('payment')->__('Purchase Order Number')) ?>" class="required-entry input-text" value="<?php echo $this->getInfoData('po_number') ?>"/>
        </div>
    </li>
</ul>
