<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/** @var Mage_Wishlist_Block_Render_Item_Price $this */
?>

<?php echo $this->getCleanProductPriceHtml(); ?>

<?php /** @var Mage_Catalog_Model_Product $product */ ?>
<?php $product = $this->getProduct(); ?>
<?php $finalPrice = $product->getFinalPrice(1); ?>
<?php if ($product->canConfigure()): ?>
    <p class="configured-price">
        <span class="price-label"><?php echo Mage::helper('wishlist')->__('Configured Price:') ?></span>
        <span class="price"><?php echo Mage::helper('core')->currency($finalPrice, true, false); ?></span>
    </p>
<?php endif ?>
