<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
/** @var Mage_Wishlist_Block_Render_Item_Price $this */
?>

<?php echo $this->getCleanProductPriceHtml(); ?>

<?php /** @var Mage_Catalog_Model_Product $product */ ?>
<?php $product = $this->getProduct(); ?>
<?php $finalPrice = $product->getFinalPrice(1); ?>
<?php if ($product->canConfigure()): ?>
    <p class="configured-price">
        <span class="price-label"><?php echo Mage::helper('wishlist')->__('Configured Price:') ?></span>
        <span class="price"><?php echo Mage::helper('core')->currency($finalPrice, true, false); ?></span>
    </p>
<?php endif ?>
