<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     rwd_default
 */

/** @var Mage_Core_Block_Template $this */
?>
<?php if ($this->getLayout()->getBlock('head')->getItems('skin_js/js/configurableswatches/swatches-product.js')): ?>
    <script type="text/javascript">
        document.observe('dom:loaded', function() {
            var swatchesConfig = new Product.ConfigurableSwatches(spConfig);
        });
    </script>
<?php endif ?>
