<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     rwd_default
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart $this */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div class="cart-cell">
    <?php echo $this->getPriceHtml($product, empty($options));?>
</div>
