<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     rwd_default
 */
/**
 * @var Mage_ConfigurableSwatches_Block_Catalog_Product_List_Price $this
 */
?>
<script type="text/javascript">
    new ConfigurableSwatchPrices(<?php echo $this->getJsonConfig(); ?>);
</script>
