<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     rwd_default
 */

/**
 * @see Mage_Adminhtml_Block_Review_Rating_Detailed
 * @see Mage_Rating_Block_Entity_Detailed
 * @var Mage_Adminhtml_Block_Review_Rating_Detailed|Mage_Rating_Block_Entity_Detailed $this
 */
?>
<?php if(!empty($collection) && $collection->getSize()): ?>
    <table class="ratings-table">
        <colgroup>
            <col class="review-label" />
            <col class="review-value" />
        </colgroup>
        <tbody>
            <?php foreach ($collection as $_rating): ?>
                <?php if($_rating->getSummary()): ?>
                    <tr>
                        <th><?php echo $this->__($this->escapeHtml($_rating->getRatingCode())) ?></th>
                        <td>
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo ceil($_rating->getSummary()) ?>%;"></div>
                            </div>
                        </td>
                    </tr>
                <?php endif ?>
            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
