<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<script type="text/javascript">
function saveAndContinueEdit(urlTemplate) {
        var url = urlTemplate.replace(/{{tab_id}}/g, customer_info_tabsJsTabs.activeTab.id);
        editForm.submit(url);
}
</script>
