<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>

<?php
/**
 * @see Mage_Customer_Block_Account_Changeforgotten
 * @var Mage_Customer_Block_Account_Changeforgotten $this
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Change Account Password') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form action="<?php echo $action ?>" method="post" id="form-validate">
<div class="fieldset">
    <h2 class="legend"><?php echo $this->__('Change Account Password') ?></h2>
    <ul class="form-list">
        <li>
            <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
            <div class="input-box">
                <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>" class="input-text required-entry" name="current_password" id="current_password" autocomplete="off" />
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                <div class="input-box">
                    <?php $minPasswordLength = max((int)$this->getCustomer()->getMinPasswordLength(), Mage_Core_Model_App::ABSOLUTE_MIN_PASSWORD_LENGTH); ?>
                    <input type="password"
                           title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>"
                           class="input-text required-entry validate-password min-pass-length-<?php echo $minPasswordLength ?>"
                           name="password"
                           id="password"
                           autocomplete="new-password" />
                    <p class="form-instructions">
                        <?php echo Mage::helper('customer')->__('The minimum password length is %s', $minPasswordLength) ?>
                    </p>
                </div>
            </div>
            <div class="field">
                <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                <div class="input-box">
                    <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" autocomplete="new-password" />
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="buttons-set">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Password')) ?>" class="button"><span><span><?php echo $this->__('Save Password') ?></span></span></button>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate');
//]]>
</script>
