<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @var Mage_Checkout_Block_Onepage $this
 */
?>
<div class="page-title">
    <h1><?= $this->__('Checkout') ?></h1>
</div>
<script type="text/javascript" src="<?= $this->getJsUrl('varien/accordion.js') ?>"></script>
<script type="text/javascript" src="<?= $this->getSkinUrl('js/opcheckout.js') ?>"></script>
<script type="text/javascript" src="<?= $this->getSkinUrl('js/opcheckout_rwd.js') ?>"></script>
<ol class="opc opc-firststep-<?= $this->getActiveStep() ?>" id="checkoutSteps">
<?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
    <li id="opc-<?= $_stepId ?>" class="section<?= !empty($_stepInfo['allow'])?' allow':'' ?><?= !empty($_stepInfo['complete'])?' saved':'' ?>">
        <div class="step-title">
            <span class="number"><?= $i ?></span>
            <h2><?= $_stepInfo['label'] ?></h2>
            <a href="#"><?= $this->__('Edit') ?></a>
        </div>
        <div id="checkout-step-<?= $_stepId ?>" class="step a-item" style="display:none;">
            <?= $this->getChildHtml($_stepId) ?>
        </div>
    </li>
<?php endforeach ?>
</ol>
<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?= $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?= $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?= $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?= $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?= $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>
