<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Page_Footer $this */
?>
<p class="bug-report">
    <?= $this->__('Interface Locale: %s', $this->getLanguageSelect()) ?>
</p>
<p class="legality">
    <a href="<?= $this->getOpenMageProjectUrl() ?>" target="_blank"><?= $this->__('OpenMage Project') ?></a> |
    <a href="<?= $this->getReportIssuesUrl() ?>" target="_blank"><?= $this->__('Report Issues') ?></a>
</p>
<?= $this->__('OpenMage %s', Mage::getOpenMageVersion()) ?>
<script type="text/javascript">
    function setInterfaceLanguage(evt) {
        var elem = Event.element(evt);
        if (elem) {
            setLocation('<?= $this->getChangeLocaleUrl() ?>locale/'+elem.value+'/<?= $this->getRefererParamName() ?>/<?= $this->getUrlForReferer() ?>');
        }
    }
    Event.observe('interface_locale', 'change', setInterfaceLanguage)
</script>
