<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Page_Head $this */
?>
<meta http-equiv="Content-Type" content="<?= $this->getContentType() ?>"/>
<meta name="robots" content="noindex, nofollow"/>
<title><?= htmlspecialchars(html_entity_decode($this->getTitle())) ?></title>
<link rel="icon" href="<?= $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>
<link rel="shortcut icon" href="<?= $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon"/>

<script type="text/javascript">
    var BLANK_URL = '<?= $this->getJsUrl() ?>blank.html';
    var BLANK_IMG = '<?= $this->getJsUrl() ?>spacer.gif';
    var BASE_URL = '<?= $this->getUrl('*') ?>';
    var SKIN_URL = '<?= $this->jsQuoteEscape($this->getSkinUrl()) ?>';
    var FORM_KEY = '<?= $this->getFormKey() ?>';
    <?php # BC: cast to INT in case of non-existing method getLoadingTimeout() in 3rd-party code?>
    var LOADING_TIMEOUT = <?= (int)$this->getLoadingTimeout() ?>;
</script>

<?= $this->getCssJsHtml() ?>

<?php if ($this->getCanLoadExtJs()): ?>
<script type="text/javascript">
    Ext.BLANK_IMAGE_URL = BLANK_IMG;
    Ext.UpdateManager.defaults.loadScripts = false;
    Ext.UpdateManager.defaults.disableCaching = true;
</script>
<?php endif ?>

<?php if ($this->getCanLoadTinyMce()): // TinyMCE is broken when loaded through index.php?>
<script type="text/javascript" src="<?= $this->getJsUrl() ?>tinymce/tinymce.min.js"></script>
<?php endif ?>

<script type="text/javascript">
    Fieldset.addToPrefix(<?= Mage::helper('adminhtml')->getCurrentUserId() ?>);
</script>

<?= $this->helper('core/js')->getTranslatorScript() ?>
<?= $this->getChildHtml() ?>
