<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $_order   = $this->getOrder() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getDiscountAmount()): ?>
    <tr>
        <td class="label">
            <?php if ($_order->getCouponCode()): ?>
                <?php echo Mage::helper('sales')->__('Discount (%s)', $this->escapeHtml($_order->getCouponCode())) ?>
            <?php else: ?>
                <?php echo Mage::helper('sales')->__('Discount') ?>
            <?php endif ?>
        </td>
        <td><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    </tr>
<?php endif ?>
