<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $_order   = $this->getOrder() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getDiscountAmount()): ?>
    <tr>
        <td class="label">
            <?php if ($_order->getCouponCode()): ?>
                <?php echo Mage::helper('sales')->__('Discount (%s)', $this->escapeHtml($_order->getCouponCode())) ?>
            <?php else: ?>
                <?php echo Mage::helper('sales')->__('Discount') ?>
            <?php endif ?>
        </td>
        <td><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    </tr>
<?php endif ?>
