<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<tr>
    <td class="label">
        <strong><big>
        <?php if ($this->getGrandTotalTitle()): ?>
            <?php echo $this->getGrandTotalTitle() ?>
        <?php else: ?>
            <?php echo Mage::helper('sales')->__('Grand Total') ?>
        <?php endif ?>
        </big></strong>
    </td>
    <td class="emph"><big><?php echo $this->displayPriceAttribute('grand_total', true) ?></big></td>
</tr>
