<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getDataUsingMethod($this->getSourceField())): ?>
    <tr>
        <td class="label"><?php if ($this->getStrong()) : ?><strong><?php endif ?><?php echo Mage::helper('sales')->__($this->getLabel()) ?><?php if ($this->getStrong()) : ?></strong><?php endif ?></td>
        <td <?php echo $this->getHtmlClass() ? ('class="' . $this->getHtmlClass() . '"') : '';?>><?php if ($this->getStrong()) : ?><strong><?php endif ?><?php echo $this->displayPriceAttribute($this->getSourceField()) ?><?php if ($this->getStrong()) : ?></strong><?php endif ?></td>
    </tr>
<?php endif ?>
