<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getDataUsingMethod($this->getSourceField())): ?>
    <tr>
        <td class="label"><?php if ($this->getStrong()) : ?><strong><?php endif ?><?php echo Mage::helper('sales')->__($this->getLabel()) ?><?php if ($this->getStrong()) : ?></strong><?php endif ?></td>
        <td <?php echo $this->getHtmlClass() ? ('class="' . $this->getHtmlClass() . '"') : '';?>><?php if ($this->getStrong()) : ?><strong><?php endif ?><?php echo $this->displayPriceAttribute($this->getSourceField()) ?><?php if ($this->getStrong()) : ?></strong><?php endif ?></td>
    </tr>
<?php endif ?>
