<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php if ($this->getCanDisplayTotalRefunded()): ?>
<tr>
    <td class="label"><strong><?php echo Mage::helper('sales')->__('Total Refunded') ?></strong></td>
    <td class="emph"><?php echo $this->displayPriceAttribute('total_refunded', true) ?></td>
</tr>
<?php endif ?>
