<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($this->getCanDisplayTotalRefunded()): ?>
<tr>
    <td class="label"><strong><?php echo Mage::helper('sales')->__('Total Refunded') ?></strong></td>
    <td class="emph"><?php echo $this->displayPriceAttribute('total_refunded', true) ?></td>
</tr>
<?php endif ?>
