<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getShippingAmount() || $_source->getShippingDescription()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('sales')->__('Shipping &amp; Handling') ?></td>
        <td><?php echo $this->displayPriceAttribute('shipping_amount') ?></td>
    </tr>
<?php endif ?>
