<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php $_source  = $this->getSource() ?>
<?php $this->setPriceDataObject($_source) ?>

<?php if ((float) $_source->getShippingAmount() || $_source->getShippingDescription()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('sales')->__('Shipping &amp; Handling') ?></td>
        <td><?php echo $this->displayPriceAttribute('shipping_amount') ?></td>
    </tr>
<?php endif ?>
