<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php
    $_source  = $this->getSource();
    $_order   = $this->getOrder();
    $this->setPriceDataObject($_source);
?>
<?php if ($this->helper('tax')->displaySalesSubtotalBoth($_order->getStore())): ?>
    <tr>
        <td class="label">
            <?php echo Mage::helper('tax')->__('Subtotal (Excl. Tax)')?>
        </td>
        <td><?php echo $this->displaySubtotalExclTax() ?></td>
    </tr>
    <tr>
        <td class="label">
            <?php echo Mage::helper('tax')->__('Subtotal (Incl. Tax)')?>
        </td>
        <td><?php echo $this->displaySubtotalInclTax() ?></td>
    </tr>
<?php elseif ($this->helper('tax')->displaySalesSubtotalInclTax($_order->getStore())):?>
    <tr>
        <td class="label">
            <?php echo Mage::helper('sales')->__('Subtotal') ?>
        </td>
        <td><?php echo $this->displaySubtotalInclTax() ?></td>
    </tr>
<?php else: ?>
    <tr>
        <td class="label">
            <?php echo Mage::helper('sales')->__('Subtotal') ?>
        </td>
        <td><?php echo $this->displaySubtotalExclTax() ?></td>
    </tr>
<?php endif ?>
