<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
    $_source  = $this->getSource();
    $_order   = $this->getOrder();
    $this->setPriceDataObject($_source);
?>
<?php if ($this->helper('tax')->displaySalesSubtotalBoth($_order->getStore())): ?>
    <tr>
        <td class="label">
            <?php echo Mage::helper('tax')->__('Subtotal (Excl. Tax)')?>
        </td>
        <td><?php echo $this->displaySubtotalExclTax() ?></td>
    </tr>
    <tr>
        <td class="label">
            <?php echo Mage::helper('tax')->__('Subtotal (Incl. Tax)')?>
        </td>
        <td><?php echo $this->displaySubtotalInclTax() ?></td>
    </tr>
<?php elseif ($this->helper('tax')->displaySalesSubtotalInclTax($_order->getStore())):?>
    <tr>
        <td class="label">
            <?php echo Mage::helper('sales')->__('Subtotal') ?>
        </td>
        <td><?php echo $this->displaySubtotalInclTax() ?></td>
    </tr>
<?php else: ?>
    <tr>
        <td class="label">
            <?php echo Mage::helper('sales')->__('Subtotal') ?>
        </td>
        <td><?php echo $this->displaySubtotalExclTax() ?></td>
    </tr>
<?php endif ?>
