<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset_Element $this */
?>
<?php $_element = $this->getElement() ?>
<?php if (!$_element->getNoDisplay()): ?>
<tr>
    <td colspan="3" class="value"><?php echo trim($_element->getElementHtml()) ?></td>
</tr>
<?php endif ?>
