<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>

<?php echo $this->getItem()->getName() ?>
<div><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->escapeHtml($this->getItem()->getSku()))); ?></div>
<?php if ($this->getOrderOptions()): ?>
    <ul class="item-options">
    <?php foreach ($this->getOrderOptions() as $option): ?>
        <li><strong><?php echo $this->escapeHtml($option['label']) ?>:</strong><br />
        <?php if (is_array($option['value'])): ?>
        <?php foreach ($option['value'] as $item): ?>
            <?php echo $this->getValueHtml($item) ?><br />
            <?php endforeach ?>
        <?php else: ?>
            <?php echo $this->escapeHtml($option['value']); ?>
        <?php endif ?>
        </li>
    <?php endforeach ?>
    </ul>
<?php endif ?>
<?php echo $this->escapeHtml($this->getItem()->getDescription()) ?>
