<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Currency') ?></h1>
</div>
<p><?php echo $this->__('Your current currency is: %s', $currency->getCode()) ?></p>
<p><a href="<?php echo Mage::getBaseUrl() ?>"><?php echo $this->__('Continue &raquo;') ?></a></p>
