<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>

<?php
/**
 * @see Mage_Core_Block_Template
 * @var Mage_Core_Block_Template $this
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Currency') ?></h1>
</div>
<p><?php echo $this->__('Your current currency is: %s', $currency->getCode()) ?></p>
<p><a href="<?php echo Mage::getBaseUrl() ?>"><?php echo $this->__('Continue &raquo;') ?></a></p>
