<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>
<?php
/**
 * @see Mage_PayPal_Block_Express_Form
 * @see Mage_PayPal_Block_Standard_Form
 * @var Mage_PayPal_Block_Express_Form $this
 */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li class="form-alt"><?php echo $this->getRedirectMessage() ?></li>
    <?php if ($code = $this->getCreateBACode()): ?>
        <li class="form-alt">
            <label for="<?php echo $code ?>"><input type="checkbox" id="<?php echo $code ?>" value="1" name="payment[<?php echo $code ?>]" class="checkbox" />
            <?php echo $this->__('Sign a billing agreement to streamline further purchases with PayPal.') ?></label>
        </li>
    <?php endif ?>
</ul>
