<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php
/**
 * @see Mage_Paypal_Block_Adminhtml_System_Config_Fieldset_Hint
 * @var Mage_Paypal_Block_Adminhtml_System_Config_Fieldset_Hint $this
 */
?>
<?php if ($this->getHelpLink()): ?>
    <div class="paypal-payment-notice">
        <?php echo Mage::helper('paypal')->__('Not sure what PayPal payment method to use? Click <a href="%s" target="_blank">here</a> to learn more.', $this->getHelpLink()); ?>
    </div>
<?php endif ?>
