<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Bundle_Block_Catalog_Product_View_Type_Bundle
 * @var Mage_Bundle_Block_Catalog_Product_View_Type_Bundle $this
 */
?>
<?php $_product = $this->getProduct() ?>

<?php if ($_product->isSaleable()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var skipTierPricePercentUpdate = true;
        var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
        var taxCalcMethod = "<?php echo Mage::helper('tax')->getConfig()->getAlgorithm($_product->getStore()) ?>";
        var CACL_UNIT_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_UNIT_BASE ?>";
        var CACL_ROW_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_ROW_BASE ?>";
        var CACL_TOTAL_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_TOTAL_BASE ?>";
        //]]>
    </script>
<?php endif ?>
<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="availability in-stock"><?php echo $this->helper('catalog')->__('Availability:') ?>
            <span><?php echo $this->helper('catalog')->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><?php echo $this->helper('catalog')->__('Availability:') ?>
            <span><?php echo $this->helper('catalog')->__('Out of stock') ?></span></p>
    <?php endif ?>
<?php endif ?>
<div class="price-box-bundle">
    <?php echo $this->getPriceHtml($_product) ?>
</div>
<?php echo $this->getChildHtml('bundle_prices') ?>
