<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */
?>
<?php if($pageData->getPageMetaKeywords()): ?>
<meta name="keywords" content="<?php echo $pageData->getPageMetaKeywords() ?>" />
<?php endif ?>
<?php if($pageData->getPageMetaDescription()): ?>
<meta name="description" content="<?php echo $pageData->getPageMetaDescription() ?>" />
<?php endif ?>
