<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Wysiwyg Images content template
 *
 * @see Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content
 * @var Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content $this 
 */
?>
<?php echo $this->getChildHtml('wysiwyg_images.js') ?>

<div class="content-header skip-header" id="content_header">
    <table cellspacing="0">
        <tr>
            <td><h3 id="content_header_text"><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>

<div id="contents-uploader"><?php echo $this->getChildHtml('wysiwyg_images.uploader') ?></div>
<div id="contents"></div>
<div id="contents-newfolder" class="no-display"><?php echo $this->getChildHtml('wysiwyg_images.newfolder') ?></div>
