<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php
/**
 * Directories tree template
 *
 * @see Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content
 * @var Mage_Adminhtml_Block_Cms_Wysiwyg_Images_Content $this
 */
?>
<script type="text/javascript">
//<![CDATA[
MediabrowserInstance = new Mediabrowser(<?php echo $this->getFilebrowserSetupObject() ?>);
MediabrowserInstance.storeId = '<?php echo $this->getStoreId() ?>';
//]]>
</script>
