<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Comments_View $this */
?>
<?php if ($_entity = $this->getEntity()): ?>
<div id="comments_block">
    <span class="field-row">
        <label class="normal" for="history_comment"><?php echo Mage::helper('sales')->__('Comment Text') ?></label>
        <textarea name="comment[comment]" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
    </span>
    <div class="f-left">
        <?php if ($this->canSendCommentEmail()): ?>
            <input name="comment[is_customer_notified]" type="checkbox" id="history_notify" value="1" />
            <label class="normal" for="history_notify"><?php echo Mage::helper('sales')->__('Notify Customer by Email') ?></label><br />
        <?php endif ?>
        <input name="comment[is_visible_on_front]" type="checkbox" id="history_visible" value="1" /><label class="normal" for="history_visible"> <?php echo Mage::helper('sales')->__('Visible on Frontend') ?></label>
    </div>
    <div class="f-right">
        <?php echo $this->getChildHtml('submit_button') ?>
    </div>
    <div class="clear"></div>
    <ul class="note-list">
    <?php foreach ($_entity->getCommentsCollection(true) as $_comment): ?>
        <li>
            <strong><?php echo $this->helper('core')->formatDate($_comment->getCreatedAtDate(), 'medium') ?></strong>
            <?php echo $this->helper('core')->formatTime($_comment->getCreatedAtDate(), 'medium') ?><span class="separator">|</span><small><?php echo $this->helper('sales')->__('Customer') ?>
            <strong class="subdue">
            <?php if ($_comment->getIsCustomerNotified()): ?>
            <?php echo $this->helper('sales')->__('Notified') ?>
            <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
            <?php else: ?>
            <?php echo $this->helper('sales')->__('Not Notified') ?>
            <?php endif ?>
            </strong></small>
            <br/>
            <?php echo $this->escapeHtml($_comment->getComment(), ['b', 'br', 'strong', 'i', 'u', 'a']) ?>
        </li>
    <?php endforeach ?>
    </ul>
<script type="text/javascript">
function submitComment() {
    submitAndReloadArea($('comments_block').parentNode, '<?php echo $this->getSubmitUrl() ?>')
}

if ($('submit_comment_button')) {
    $('submit_comment_button').observe('click', submitComment);
}
</script>
</div>
<?php endif ?>
