<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */
?>
<?php /** @var Mage_Sales_Block_Recurring_Profiles $this */ ?>
<div class="page-title">
    <h1><?php echo $this->__('Recurring Profiles') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="recurring-profiles">

    <?php echo $this->getChildHtml('grid')?>

    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    </div>
</div>
