<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Tax_Rate_Form $this */
?>
<div class="entry-edit">
    <?php echo $this->getFormHtml() ?>
</div>
<?php echo $this->getChildHtml('form_after');?>
<script type="text/javascript">
var updater = new RegionUpdater('tax_country_id', 'tax_region', 'tax_region_id', <?php echo Mage::helper('directory')->getRegionJsonByStore() ?>, 'disable');
</script>
