<?php /* <table class="dynamic-grid" cellspacing="0" id="tax-rate-titles-table"> */ ?>
    <tr class="dynamic-grid">
    <?php foreach ($this->getStores() as $_store): ?>
        <th><?php echo $_store->getName() ?></th>
    <?php endforeach; ?>
    </tr>
    <tr class="dynamic-grid">
        <?php $_labels = $this->getTitles() ?>
        <?php foreach ($this->getStores() as $_store): ?>
        <td>
            <input class="input-text<?php if($_store->getId()==0): ?> required-entry<?php endif; ?>" type="text" name="title[<?php echo $_store->getId() ?>]" value="<?php echo $_labels[$_store->getId()] ?>" />
        </td>
        <?php endforeach; ?>
    </tr>
    <tr class="dynamic-grid">
        <td colspan="<?php echo count($this->getStores()); ?>" class="tax-rate-titles-note-td">
            Note: Leave empty to use tax identifier
        </td>
    </tr>
<?php /* </table> */ ?>
