<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Tax_Rate_Title $this */
?>
<?php /* <table class="dynamic-grid" cellspacing="0" id="tax-rate-titles-table"> */ ?>
    <tr class="dynamic-grid">
    <?php foreach ($this->getStores() as $_store): ?>
        <th><?php echo $this->escapeHtml($_store->getName()); ?></th>
    <?php endforeach ?>
    </tr>
    <tr class="dynamic-grid">
        <?php $_labels = $this->getTitles() ?>
        <?php foreach ($this->getStores() as $_store): ?>
        <td>
            <input class="input-text<?php if($_store->getId()==0): ?> required-entry<?php endif ?>" type="text" name="title[<?php echo $_store->getId() ?>]" value="<?php echo $_labels[$_store->getId()] ?>" />
        </td>
        <?php endforeach ?>
    </tr>
    <tr class="dynamic-grid">
        <td colspan="<?php echo count($this->getStores()); ?>" class="tax-rate-titles-note-td">
            <p><strong><?php echo $this->__('Note:'); ?></strong> <?php echo $this->__('Leave empty to use tax identifier'); ?></p>
        </td>
    </tr>
<?php /* </table> */ ?>
