<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_GiftMessage_Block_Message_Form
 * @var Mage_GiftMessage_Block_Message_Form $this
 */
?>
<?php echo $this->helper('core/js')->includeScript('mage/adminhtml/giftmessage.js') ?>
<?php if(!$this->getSaveMode()): ?>
<form action="<?php echo $this->getSaveUrl() ?>" id="message-form" method="post" class="a-left">
    <?php echo $this->getBlockHtml('formkey')?>
    <?php echo $this->getFormHtml(); ?>
    <?php echo $this->getSaveButtonHtml() ?>
    <?php echo $this->getCancelButtonHtml() ?>
    <?php if($this->getMessage()->getGiftMessageId()): ?>
    <?php echo $this->getRemoveButtonHtml() ?>
    <?php endif ?>
</form>
<?php elseif($this->getSaveMode() == 'save'): ?>
<h3><?php echo Mage::helper('giftmessage')->__('The gift message has been saved') ?></h3>
<br /><?php echo $this->getCloseButtonHtml() ?>
<?php else: ?>
<h3><?php echo Mage::helper('giftmessage')->__('The gift message has been removed') ?></h3>
<br /><?php echo $this->getCloseButtonHtml() ?>
<?php endif ?>
<script type="text/javascript">
<!--
<?php if(!$this->getSaveMode()): ?>
    var giftMessageWindowObject = new GiftMessageWindow('<?php echo $this->getUniqueId() ?>','message-form', '<?php echo $this->getRemoveUrl() ?>');
    giftMessageWindowObject.confirmMessage = '<?php echo $this->getEscapedForJs(Mage::helper('giftmessage')->__('Are you sure?')) ?>';
<?php else: ?>
    var giftMessageWindowObject = new GiftMessageWindow('<?php echo $this->getUniqueId() ?>', null, '<?php echo $this->getRemoveUrl() ?>');
    Event.observe(window, 'load', function(evt) {
        giftMessageWindowObject.updateParent('<?php echo $this->getEditUrl() ?>', '<?php echo $this->getButtonUrl() ?>');
    });
<?php endif ?>
//-->
</script>
