<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/** @var Mage_Wishlist_Block_Customer_Wishlist_Item_Options $this */
?>

<?php $options = $this->getOptionList(); ?>
<?php if ($options): ?>
<div class="truncated">
  <div class="truncated_full_value">
      <div class="item-options">
          <p><?php echo $this->__('Options Details'); ?></p>
          <dl>
              <?php foreach ($options as $option): ?>
              <dt><?php echo $this->escapeHtml($option['label']) ?></dt>
              <dd>
                  <?php if (is_array($option['value'])): ?>
                  <?php echo nl2br(implode("\n", $option['value'])) ?>
                  <?php else: ?>
                  <?php echo $option['value'] ?>
                  <?php endif ?>
              </dd>
              <?php endforeach ?>
          </dl>
      </div>
  </div>
  <a href="#" onclick="return false;" class="details"><?php echo $this->__('View Details') ?></a>
</div>
<?php endif ?>
