<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
/** @var Mage_Wishlist_Block_Customer_Wishlist_Item_Options $this */
?>

<?php $options = $this->getOptionList(); ?>
<?php if ($options): ?>
<div class="truncated">
  <div class="truncated_full_value">
      <div class="item-options">
          <p><?php echo $this->__('Options Details'); ?></p>
          <dl>
              <?php foreach ($options as $option): ?>
              <dt><?php echo $this->escapeHtml($option['label']) ?></dt>
              <dd>
                  <?php if (is_array($option['value'])): ?>
                  <?php echo nl2br(implode("\n", $option['value'])) ?>
                  <?php else: ?>
                  <?php echo $option['value'] ?>
                  <?php endif ?>
              </dd>
              <?php endforeach ?>
          </dl>
      </div>
  </div>
  <a href="#" onclick="return false;" class="details"><?php echo $this->__('View Details') ?></a>
</div>
<?php endif ?>
