<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Customer_Edit_Tab_Addresses $this */
?>
<!-- Addresses list -->
<table cellspacing="0" class="form-edit">
<tr>
<td class="address-list">
    <div class="entry-edit-head">
        <h4 class="icon-head head-customer-address-list"><?php echo Mage::helper('customer')->__('Customer Addresses') ?></h4>
    </div>
    <div class="sub-btn-set"><?php echo $this->getAddNewButtonHtml() ?></div>
    <ul id="address_list">
    <?php $_iterator = 0; ?>
    <?php if(count($addressCollection)): ?>
        <?php foreach ($addressCollection as $_address): ?>
        <li id="address_item_<?php echo $_address->getId() ?>">
            <?php if (!$this->isReadonly()): ?>
            <a href="#" class="btn-remove-address">
                <img src="<?php echo $this->getSkinUrl('images/cancel_icon.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('customer')->__('Remove address')) ?>" id="delete_button<?php echo ++$_iterator ?>" />
            </a>
            <a href="#" id="select_button_<?php echo $_address->getId() ?>" class="select_button btn-edit-address">
                <img src="<?php echo $this->getSkinUrl('images/edit_icon.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('customer')->__('Edit address')) ?>"/>
            </a>
            <?php endif ?>
            <address>
                <?php echo $this->maliciousCodeFilter($_address->format('html')) ?>
            </address>
            <div class="address-type">
                <span class="address-type-line">
                    <input type="radio" <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif ?> value="<?php echo $_address->getId() ?>" id="address_item_billing<?php echo $_address->getId() ?>" name="account[default_billing]" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('customer')->__('Set as Default Billing Address')) ?>"<?php if($_address->getId()==$customer->getDefaultBilling()): ?> checked="checked"<?php endif ?>/>
                    &nbsp;<label for="address_item_billing<?php echo $_address->getId() ?>"><?php echo Mage::helper('customer')->__('Default Billing Address') ?></label>
                </span>
                <span class="address-type-line">
                    <input type="radio"  <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif ?> value="<?php echo $_address->getId() ?>" id="address_item_shipping<?php echo $_address->getId() ?>" name="account[default_shipping]" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('customer')->__('Set as Default Shipping Address')) ?>"<?php if($_address->getId()==$customer->getDefaultShipping()): ?> checked="checked"<?php endif ?>/>
                    &nbsp;<label for="address_item_shipping<?php echo $_address->getId() ?>"><?php echo Mage::helper('customer')->__('Default Shipping Address') ?></label>
                </span>
            </div>
        </li>
        <?php endforeach ?>
    <?php endif ?>
    </ul>
</td>
<td>
    <!-- Template for adding address item to list -->
    <?php $_templatePrefix = $this->getTemplatePrefix() ?>
    <div id="address_item_template" class="no-display template">
        <?php if (!$this->isReadonly()): ?>
        <a href="#" class="btn-remove-address">
            <img src="<?php echo $this->getSkinUrl('images/cancel_icon.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('customer')->__('Remove address')) ?>" id="delete_button<?php echo ++$_iterator ?>" />
        </a>
        <a href="#" id="select_button_" class="select_button btn-edit-address">
            <img src="<?php echo $this->getSkinUrl('images/edit_icon.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('customer')->__('Edit address')) ?>"/>
        </a>
        <?php endif ?>
        <address><?php echo Mage::helper('customer')->__('New Customer Address') ?></address>
        <div class="address-type">
            <span class="address-type-line">
                <input  <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif ?> type="radio" value="<?php echo $_templatePrefix ?>" id="address_item_billing<?php echo $_templatePrefix ?>" name="account[default_billing]" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('customer')->__('Set as Default Billing Address')) ?>"/>
                &nbsp;<label for="address_item_billing<?php echo $_templatePrefix ?>"><?php echo Mage::helper('customer')->__('Default Billing Address') ?></label>
            </span>
            <span class="address-type-line">
                <input  <?php if ($this->isReadonly()):?> disabled="disabled"<?php endif ?> type="radio" value="<?php echo $_templatePrefix ?>" id="address_item_shipping<?php echo $_templatePrefix ?>" name="account[default_shipping]" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('customer')->__('Set as Default Shipping Address')) ?>"/>
                &nbsp;<label for="address_item_shipping<?php echo $_templatePrefix ?>"><?php echo Mage::helper('customer')->__('Default Shipping Address') ?></label>
            </span>
        </div>
    </div>

    <!-- Address form template -->
    <div id="address_form_template" class="no-display template">
    <?php
        // Set form template elements prefix
        $this->getForm()->setHtmlIdPrefix($_templatePrefix)
                ->setFieldNameSuffix('address['.$_templatePrefix.']');
    ?>
    <?php echo $this->getForm()->getHtml() ?>
    <?php echo $this->getCancelButtonHtml() ?>
    </div>
<!-- -->

<!-- Addresses forms -->
    <div class="entry-edit" id="address_form_container">
        <?php if(count($addressCollection)): ?>
            <?php foreach ($addressCollection as $_address): ?>
            <div id="form_address_item_<?php echo $_address->getId() ?>" style="display:none">
            <?php
                    $this->getForm()->setValues($_address->getData())
                            ->setHtmlIdPrefix("_item{$_address->getId()}")
                            ->setFieldNameSuffix('address['.$_address->getId().']');
                    $this->addValuesToNamePrefixElement($_address->getPrefix())
                        ->addValuesToNameSuffixElement($_address->getSuffix());
            ?>
            <?php echo $this->getForm()->getHtml() ?>
            <input type="hidden" name="address[<?php echo $_address->getId() ?>][_deleted]" id="deleted_address_item_<?php echo $_address->getId() ?>" />
            </div>
            <?php endforeach ?>
        <?php else: ?>
            <div id="no_address_message"><?php echo Mage::helper('customer')->__('This customer has no saved addresses.') ?></div>
        <?php endif ?>
    </div>

<script type="text/javascript">
//<![CDATA[
var deleteButtonId = <?php echo $_iterator ?>;

var addressesModel = Class.create();
addressesModel.prototype = {
    initialize : function() {
        this.activeItem   = null;
        this.itemTemplate = document.getElementById('address_item_template');
        this.formTemplate = document.getElementById('address_form_template');
        this.itemContainer= document.getElementById('address_list');
        this.formContainer= document.getElementById('address_form_container');
        this.baseItemId   = 'new_item';

        this.defaultCountries = <?php echo $this->getDefaultCountriesJson(); ?>;
        this.itemContentTemplate = new Template('<?php echo $this->helper('customer/address')->getFormat('js_template')?>');

        this.onNewAddressClick  = this.addNewAddress.bind(this);
        this.onItemMouseOver    = this.itemMouseOver.bind(this);
        this.onItemMouseOut     = this.itemMouseOut.bind(this);
        this.onItemMouseClick   = this.itemMouseClick.bind(this);
        this.onItemFormFieldChange = this.syncFormData.bind(this);

        this.loader = new varienLoader(true);
        this.regionsUrl = '<?php echo $this->getRegionsUrl() ?>';
        this.requiredStateForCountries = <?php echo $this->helper('directory')->getCountriesWithStatesRequired(true) ?>;
        this.showAllRegions = <?php echo (string)$this->helper('directory')->getShowNonRequiredState() ? 1 : 0; ?>;

        this.reloadItemList(1);

        for(var i=0,n=this.itemList.length; i<n; i++){
            if(this.itemList[i].id){
                this.addItemObservers(this.itemList[i]);
                this.initItem(this.itemList[i]);
            }
        }
        if(document.getElementById('add_new_address_button')){
            document.getElementById('add_new_address_button').addEventListener('click', this.onNewAddressClick);
        }

        this.setActiveItem(this.itemList[0]);
        this.setAddressAsDefault();
        this.bindCountryRegionRelation();
    },

    reloadItemList : function(initial){
        this.itemList = Array.from(document.querySelectorAll('#address_list li'));
        if( initial ) {
            this.itemCount = this.itemList.length;
        }
        if(!this.itemList.length){
            if(document.getElementById('no_address_message')){
                document.getElementById('no_address_message').style.display = '';
            }
            else {
                this.formContainer.innerHTML+= '<div id="no_address_message"><?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('customer')->__('This customer has no saved addresses.')) ?></div>'
            }
        }
    },

    initItem : function(item){
        if(item && document.getElementById('form_'+item.id)){
            item.formBlock = document.getElementById('form_'+item.id);
            document.getElementById('form_'+item.id).style.display = 'none';
            document.getElementById('form_'+item.id).statusBar = item;
            document.getElementById('form_'+item.id).addressItem = item;

            // set Zip optional/required
            var countryElement = document.getElementById('_item' + item.id.replace(/address_item_/, '').replace(new RegExp(this.baseItemId), '') + 'country_id');
            varienGlobalEvents.fireEvent("address_country_changed", countryElement);
        }
    },

    addItemObservers : function(item){
        if(item.id){
            item.addEventListener('mouseover', this.onItemMouseOver);
            item.addEventListener('mouseout', this.onItemMouseOut);
            item.addEventListener('click', this.onItemMouseClick);
        }
    },

    addNewAddress : function(event){
        if(this.canCreateNewAddress){
            this.itemCount++;
            if(document.getElementById('no_address_message')){
                document.getElementById('no_address_message').style.display = 'none';
            }
            // preventing duplication of ids for fields and blocks
            while (document.querySelectorAll("div[id='form_address_item_" + this.itemCount + "']").length) {
                this.itemCount++;
            }
            // create new form elements
            this.formContainer.insertAdjacentHTML('beforeend',
                '<div id="' + 'form_' + this.baseItemId + this.itemCount + '">'
                + this.prepareTemplate(this.formTemplate.innerHTML)
                + '</div>'
            );

            var newForm = document.getElementById('form_' + this.baseItemId + this.itemCount);

            document.getElementById('_item'+this.itemCount+'firstname').value = document.getElementById('_accountfirstname').value;
            document.getElementById('_item'+this.itemCount+'lastname').value = document.getElementById('_accountlastname').value;

            if (document.getElementById('_accountwebsite_id').value !== '' && undefined !== this.defaultCountries[document.getElementById('_accountwebsite_id').value]) {
                document.getElementById('_item'+this.itemCount+'country_id').value = this.defaultCountries[document.getElementById('_accountwebsite_id').value];
            }

            newForm.style.display = 'none';
            var template = '<li id="' + this.baseItemId+this.itemCount + '">';
            deleteButtonId ++;
            template    += this.prepareTemplate(this.itemTemplate.innerHTML).replace('delete_button', 'delete_button'+ deleteButtonId);
            template    += '</li>';
            this.itemContainer.insertAdjacentHTML('beforeend', template);
            var newItem = document.getElementById(this.baseItemId+this.itemCount);
            newItem.isNewAddress = true;
            newItem.formBlock = newForm;


            newForm.statusBar = newItem;
            newForm.addressItem = newItem;

            // set Zip optional/required
            var countryElement = document.getElementById('_item' + newItem.id.replace(/address_item_/, '').replace(new RegExp(this.baseItemId), '') + 'country_id');
            varienGlobalEvents.fireEvent("address_country_changed", countryElement);

            this.addItemObservers(newItem);
            this.setActiveItem(newItem);
            this.bindCountryRegionRelation(newForm.id);

            if( document.getElementById('_item'+this.itemCount+'firstname').value ) this.syncFormData(document.getElementById('_item'+this.itemCount+'firstname'));
            if( document.getElementById('_item'+this.itemCount+'lastname').value ) this.syncFormData(document.getElementById('_item'+this.itemCount+'lastname'));
        }
        this.reloadItemList();
        //Event.stop(event);
    },

    prepareTemplate : function(template){
        return template
            .replace(/<?php echo $_templatePrefix ?>/g, '_item'+this.itemCount)
            .replace(/_counted="undefined"/g, '')
            .replace(/"select_button_"/g, 'select_button_' + this.itemCount)
            ;
    },

    canCreateNewAddress : function(){
        return true;
    },

    itemMouseOver : function(event){
        var element = event.target.closest('li');
        if (element) element.classList.add('over');
    },

    itemMouseOut : function(event){
        var element = event.target.closest('li');
        if (element) element.classList.remove('over');
    },

    itemMouseClick : function(event){
        var element = event.target.closest('li'); // find top item
        var elem = event.target; // exact element clicked

        if ( ((elem.tagName.toUpperCase() == 'A') && elem.id.match(/^delete_button([0-9]*?)$/)) || ((elem.tagName.toUpperCase() == 'IMG') && elem.id.match(/^delete_button([0-9]*?)$/)) ) {
            this.deleteAddress(element);
            event.preventDefault(); event.stopPropagation();
        }
        else if(elem.tagName.toUpperCase() == 'INPUT') {
            this.setAddressAsDefault(element);
        }
        else {
            this.setActiveItem(element);
        }
    },

     setAddressAsDefault : function(){
        for(var i=0; i<this.itemList.length;i++){
            if(this.itemList[i].id){
                var inputs = document.getElementById(this.itemList[i].id).querySelectorAll('input');
                var isActive = false;
                for(var j in inputs){
                    if(inputs[j].type=='radio' && inputs[j].checked && this.itemList.length > 1){
                        isActive = true;
                    }
                }
                this.toggleDeleteButton(this.itemList[i], !isActive);
            }
        }
    },

    toggleDeleteButton : function(item, flag){
        if(flag){
            item.querySelectorAll('.btn-remove-address').forEach(function(el){ el.style.display = ''; });
            item.formBlock.querySelectorAll('.delete-address').forEach(function(el){ el.style.display = ''; });
        } else {
            item.querySelectorAll('.btn-remove-address').forEach(function(el){ el.style.display = 'none'; });
            item.formBlock.querySelectorAll('.delete-address').forEach(function(el){ el.style.display = 'none'; });
        }
    },

    setActiveItem : function(item){
        if(this.activeItem){
            this.activeItem.classList.remove('on');
            if(document.getElementById('form_'+this.activeItem.id)){
                document.getElementById('form_'+this.activeItem.id).style.display = 'none';
            }
        }
        item.classList.add('on');

        if(item && document.getElementById('form_'+item.id)){
            document.getElementById('form_'+item.id).changeRelation = item;
            document.getElementById('form_'+item.id).addressItem = item;
            document.getElementById('form_'+item.id).style.display = '';
            this.addFieldChangeObserver(document.getElementById('form_'+item.id));
            var regionIdElement = document.getElementById('_item' + item.id.replace(/address_item_/, '').replace(new RegExp(this.baseItemId), '') + 'region_id');
            var regionElement = document.getElementById('_item' + item.id.replace(/address_item_/, '').replace(new RegExp(this.baseItemId), '') + 'region');
            this.countryEl = document.getElementById('_item' + item.id.replace(/address_item_/, '').replace(new RegExp(this.baseItemId), '') + 'country_id');
            if (regionIdElement && regionElement) {
                var actualId = regionElement.id;
                if (('select' == regionIdElement.tagName.toLowerCase()) && regionIdElement) {
                    actualId = regionIdElement.id;
                }
                this._checkRegionRequired([regionIdElement, regionElement], actualId);
            }
        }

        this.activeItem = item;
    },

    getFormContainerFields : function(container){
        var fields = Array.from(container.querySelectorAll('input, select, textarea'));
        return fields;
    },

    addFieldChangeObserver : function(container){
        var fields = this.getFormContainerFields(container);
        for (var i = 0; i < fields.length; i++) {
            fields[i].addEventListener('change', this.onItemFormFieldChange);
        }

    },

    syncFormData : function(evt){
        var container = false;

        if(evt instanceof Event || (evt && evt.target)) {
            var elm = evt.target;
        } else {
            var elm = evt;
        }

        while(elm && elm.tagName && elm.tagName.toUpperCase() != 'BODY') {
            if(elm.addressItem){
                container = elm;
            }
            elm = elm.parentNode;
        }

        if(container){
            var data = {};
            var fields = this.getFormContainerFields(container);
            for(var i=0; i < fields.length; i++){
                if(fields[i].id){
                    var id = fields[i].id.replace(/^(_item)?[0-9]+/, '');
                    var id = id.replace(/^(id)?[0-9]+/, '');
                    var value = fields[i].value;
                    var tagName = fields[i].tagName.toLowerCase();
                    var _escapeHTML = function(s) { var d = document.createElement('div'); d.appendChild(document.createTextNode(s)); return d.innerHTML; };
                    if (tagName == 'select') {
                        if (fields[i].multiple) {
                            var values = [];
                            var l = fields[i].options.length;
                            for (j=0; j<l; j++) {
                                var o = fields[i].options[j];
                                if (o.selected === true) {
                                    values[values.length] = _escapeHTML(o.text);
                                }
                            }
                            data[id] = values.join(', ');
                        } else {
                            var option = fields[i].options[fields[i].selectedIndex],
                                text   = option.value == '0' || option.value == '' ? '' : option.text;
                            data[id] = _escapeHTML(text);
                        }
                    } else if (value !== null) {
                        data[id] = _escapeHTML(value);
                    }
                }
            }

            // Set name of state to 'region' if list of states are in 'region_id' selectbox
            if (!data['region'] && data['region_id']) {
                data['region'] = data['region_id'];
                delete data['region_id'];
            }

            // Set data to html
            var itemContainer = container.addressItem.querySelectorAll('address');
            if(itemContainer[0]){
                var html = this.itemContentTemplate.evaluate(data);
                html = html.replace(new RegExp('(<br\\s*/?>\\s*){2,}','img'),'<br/>');
                html = html.replace(new RegExp('<br\\s*/?>(\\s*,){1,}\\s*<br\\s*/?>','ig'),'<br/>');
                html = html.replace(new RegExp('<br\\s*/?>(\\s*,){1,}(.*)<br\\s*/?>','ig'),'<br/>$2<br/>');
                html = html.replace(new RegExp('<br\\s*/?>(.*?)(,\\s*){1,}<br\\s*/?>','ig'),'<br/>$1<br/>');
                html = html.replace(new RegExp('<br\\s*/?>(.*?)(,\\s*){2,}(.*?)<br\\s*/?>','ig'),'<br/>$1, $3<br/>');
                html = html.replace(new RegExp('t:\\s*<br\\s*/?>','ig'),'');
                html = html.replace(new RegExp('f:\\s*<br\\s*/?>','ig'),'');
                html = html.replace(new RegExp('vat:\\s*$','ig'),'');
                itemContainer[0].innerHTML = html;
            }
        }
    },

    deleteAddress : function(item){
        if(confirm('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('customer')->__('Are you sure you want to delete this address?')) ?>')){
            if (!item.isNewAddress && document.getElementById('deleted_'+item.id)){
                document.getElementById('deleted_'+item.id).value = 1;
                if (item.formBlock){
                    item.formBlock.classList.add('ignore-validation');
                }
            }
            if (this.activeItem == item && item != this.itemList[0]) this.setActiveItem(this.itemList[0]);
            if (item == this.itemList[0] && (this.itemList[1])) this.setActiveItem(this.itemList[1]);

            this.formContainer.removeChild(item.formBlock);
            this.itemContainer.removeChild(item);
            this.reloadItemList();
            this.setAddressAsDefault();
        }
    },

    cancelAdd : function(button){
        if(confirm('<?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('customer')->__('Are you sure you want to cancel adding of this address?')) ?>')){
            var item = document.getElementById(this.baseItemId + button.id.replace(new RegExp('[a-z_]*',''), ''));

            if( item.isNewAddress){
                if ( this.activeItem == item ) this.formContainer.removeChild(item.formBlock);
            }
            if ( this.activeItem == item && item != this.itemList[0] ) this.setActiveItem(this.itemList[0]);
            if ( item == this.itemList[0] && (this.itemList[1]) ) this.setActiveItem(this.itemList[1]);

            this.itemContainer.removeChild(item);

            this.reloadItemList();
            this.setAddressAsDefault();
        }
    },

    bindCountryRegionRelation : function(parentId){
        //alert('OK');
        if(parentId){
            var countryElements = document.getElementById(parentId).getElementsByClassName('countries');
        }
        else{
            var countryElements = document.querySelectorAll('.countries');
        }

        for(var i=0;i<=countryElements.length;i++){
            if(countryElements[i]){
                if(!countryElements[i].bindRegions || !countryElements[i].parentBindId || countryElements[i].parentBindId!=parentId){
                //if(!countryElements[i].bindRegions || !countryElements[i].parentBindId){
                    countryElements[i].addEventListener('change', this.reloadRegionField.bind(this));

                    countryElements[i].bindRegions = true;
                    countryElements[i].parentBindId = parentId;
                }
            }
        }
    },

    reloadRegionField : function(event){
        var countryElement = event.target;
        if(countryElement.id){
            var regionElement  = document.getElementById(countryElement.id.replace(/country_id/, 'region'));
            if(regionElement){
                this.regionElement = regionElement;
                this.countryEl = countryElement;
                if (countryElement.value) {
                    var url = this.regionsUrl + 'parent/' + countryElement.value;
                    this.loader.load(url, {}, this.refreshRegionField.bind(this));
                } else {
                    // Set empty text field in region
                    this.refreshRegionField('[]');
                }
            }
            // set Zip optional/required
            varienGlobalEvents.fireEvent("address_country_changed", countryElement);
        }
    },

    // serverResponse is either string with server response, or object to force some paricular data setting
    refreshRegionField : function(serverResponse){
        if (!serverResponse)
            return;
        var data = eval('(' + serverResponse + ')');

        var row = this.regionElement.parentNode.previousElementSibling;
        var reqLabel = row ? row.querySelectorAll('.required') : [];

        // Set regions and refresh controls
        // We use a pair of 'region' and 'region_id' to properly submit data:
        // manually entered text goes in 'region' and selected option id goes in 'region_id'
        var regionHtmlName = this.regionElement.name;
        var regionIdHtmlName = regionHtmlName.replace(/region/, 'region_id');
        var regionHtmlId = this.regionElement.id;
        var regionIdHtmlId = regionHtmlId.replace(/region/, 'region_id');
        var newInputId = null; // id of imput that was added to a page - filled below

        if (data.length) {
            // Create visible selectbox 'region_id' and hidden 'region'
            var html = '<select name="' + regionIdHtmlName + '" id="' + regionIdHtmlId + '" class="required-entry select" title="' + this.regionElement.title + '">';
            for (var i in data){
                if(data[i].label) {
                    html+= '<option value="'+data[i].value+'"';
                    if(this.regionElement.value && (this.regionElement.value == data[i].value || this.regionElement.value == data[i].label)){
                        html+= ' selected="selected"';
                    }
                    html+='>'+data[i].label+'</option>';
                }
            }
            html += '</select>';

            html += '<input type="hidden" name="' + regionHtmlName + '" id="' + regionHtmlId + '"/>';

            if (reqLabel) {
                reqLabel.forEach(function(item){item.style.display = ''});
            }

            newInputId = regionIdHtmlId;
        } else {
            // Create visible text input 'region' and hidden 'region_id'
            var html = '<input type="text" name="' + regionHtmlName + '" id="' + regionHtmlId + '" class="input-text" title="' + this.regionElement.title + '" />';
            html += '<input type="hidden" name="' + regionIdHtmlName + '" id="' + regionIdHtmlId + '"/>';

            if (reqLabel) {
                reqLabel.forEach(function(item){item.style.display = 'none'});
            }

            newInputId = regionHtmlId;
        }

        var parentNode = this.regionElement.parentNode;
        parentNode.innerHTML = html;
        this.regionElement = document.getElementById(regionHtmlId);

        // Updating in address info
        var newInput = document.getElementById(newInputId);
        newInput.addEventListener('change', this.onItemFormFieldChange); // Restore observing to update address info
        this.syncFormData(newInput); // Update address info now
        var activeElementId = regionHtmlId;
        if (('select' == document.getElementById(regionIdHtmlId).tagName.toLowerCase()) && regionIdHtmlId) {
            activeElementId = regionIdHtmlId;
        }
        this._checkRegionRequired([document.getElementById(regionHtmlId), document.getElementById(regionIdHtmlId)], activeElementId);
    },

    _checkRegionRequired: function(elements, activeElementId)
    {
        var label, wildCard;
        var that = this;
        var regionRequired = this.requiredStateForCountries.indexOf(this.countryEl.value) >= 0;

        elements.forEach(function(currentElement) {
            Validation.reset(currentElement);
            label = document.querySelector('label[for="' + currentElement.id + '"]');
            if (label) {
                wildCard = label.querySelector('em') || label.querySelector('span.required');
                if (!wildCard) {
                    label.insertAdjacentHTML('beforeend', ' <span class="required">*</span>');
                    wildCard = label.querySelector('span.required');
                }
                if (!that.showAllRegions) {
                    if (regionRequired) {
                        label.closest('tr').style.display = '';
                    } else {
                        label.closest('tr').style.display = 'none';
                    }
                }
            }

            if (label && wildCard) {
                if (!regionRequired) {
                    wildCard.style.display = 'none';
                } else {
                    wildCard.style.display = '';
                }
            }

            if (!regionRequired) {
                if (currentElement.classList.contains('required-entry')) {
                    currentElement.classList.remove('required-entry');
                }
                if ('select' == currentElement.tagName.toLowerCase() &&
                    currentElement.classList.contains('validate-select')
                ) {
                    currentElement.classList.remove('validate-select');
                }
            } else if (activeElementId == currentElement.id) {
                if (!currentElement.classList.contains('required-entry')) {
                    currentElement.classList.add('required-entry');
                }
                if ('select' == currentElement.tagName.toLowerCase() &&
                    !currentElement.classList.contains('validate-select')
                ) {
                    currentElement.classList.add('validate-select');
                }
            }
        });
    }
}

customerAddresses = new addressesModel();
//]]>
</script>
</td>
</tr>
</table>
