<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
/**
 * @see Mage_Adminhtml_Block_Notification_Curl
 * @var Mage_Adminhtml_Block_Notification_Curl $this 
 */
?>
<div>
    <ul class="messages">
        <li class="notice-msg">
            <?php echo $this->getMessage(); ?>
        </li>
    </ul>
</div>
