<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
/**
 * @see Mage_Adminhtml_Block_Notification_Baseurl
 * @var Mage_Adminhtml_Block_Notification_Baseurl $this 
 */
?>
<div class="notification-global notification-global-notice">
    <?php echo $this->helper('adminhtml')->__('Your web server is configured incorrectly. As a result, configuration files with sensitive information are accessible from the outside. Please contact your hosting provider.')?>
</div>
