<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
/**
 * @see Mage_Adminhtml_Block_Notification_Baseurl
 * @var Mage_Adminhtml_Block_Notification_Baseurl $this 
 */
?>
<div class="notification-global notification-global-notice">
    <?php echo $this->helper('adminhtml')->__('Your web server is configured incorrectly. As a result, configuration files with sensitive information are accessible from the outside. Please contact your hosting provider.')?>
</div>
