<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php
/**
 * @var Mage_Adminhtml_Block_Notification_Toolbar $this
 */
?>
<?php if ($this->isShow()): ?>
<div class="notification-global">
    <?php
        $sParts = [];

        if ($this->getCriticalCount()):
            $sParts[] = '<span class="critical"><strong>'.$this->getCriticalCount().'</strong> '.$this->__('critical').'</span>';
        endif;

        if ($this->getMajorCount()):
            $sParts[] = '<strong>'.$this->getMajorCount().'</strong> '.$this->__('major');
        endif;

        if ($this->getMinorCount()):
            $sParts[] = '<strong>'.$this->getMinorCount().'</strong> '.$this->__('minor');
        endif;

        if ($this->getNoticeCount()):
            $sParts[] = '<strong>'.$this->getNoticeCount().'</strong> '.$this->__('notice');
        endif;

        $msgStats = '';
        $c = count($sParts);
        for ($i = 0; $i < $c; $i++) {
            $msgStats .= $sParts[$i] . ($i == $c-1 ? '' : ($i == $c-2 ? $this->__(' and ') : ', '));
        }

        $latestNoticeUrl = $this->getLatestNoticeUrl();
    ?>
    <?php /*
    <span class="f-right"><?php echo $this->__('You have %s unread message(s). <a href="%s">Go to messages inbox</a>.', $msgStats, $this->getNoticesInboxUrl());?></span>
    */?>

    <span class="f-right">
        <?php $goToBoxMessage = (!empty($latestNoticeUrl)) ? $this->__('Go to messages inbox') : $this->__('Go to notifications') ?>
        <?php echo $this->__('You have %s unread message(s).', $msgStats) ?> <a href="<?php echo $this->getNoticesInboxUrl() ?>"><?php echo $goToBoxMessage ?></a>
    </span>
<?php /* ********** temporary commented
    <span class="f-right"><?php echo $this->__('You have %s, %s and %s unread messages. <a href="%s">Go to messages inbox</a>.', '<span class="critical"><strong>'.$this->getCriticalCount().'</strong> '.$this->__('critical').'</span>', '<strong>'.$this->getMajorCount().'</strong> '.$this->__('major'), '<strong>'.$this->getMinorCount().'</strong> '.$this->__('minor'), $this->getNoticesInboxUrl());?></span>
******** */?>
    <?php if ($this->isMessageWindowAvailable()): ?>
        <strong class="label clickable" onclick="openMessagePopup()">
    <?php else: ?>
        <strong class="label">
    <?php endif ?>

    <?php echo $this->__('Latest Message:') ?></strong> <?php echo $this->escapeHtml($this->getLatestNotice()); ?>
    <?php if (!empty($latestNoticeUrl)): ?>
        <a href="<?php echo $latestNoticeUrl ?>" onclick="this.target='_blank';"><?php echo $this->__('Read details') ?></a>
    <?php endif ?>
</div>
<?php endif ?>
