<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Mage
 * @package    design_default
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($this->isShow()): ?>
<div class="notification-global">
	<?php
        $sParts = array();

		if ($this->getCriticalCount()):
			$sParts[] = '<span class="critical"><strong>'.$this->getCriticalCount().'</strong> '.$this->__('critical').'</span>';
		endif;

		if ($this->getMajorCount()):
            $sParts[] = '<strong>'.$this->getMajorCount().'</strong> '.$this->__('major');
		endif;

		if ($this->getMinorCount()):
		    $sParts[] = '<strong>'.$this->getMinorCount().'</strong> '.$this->__('minor');
		endif;

		if ($this->getNoticeCount()):
		    $sParts[] = '<strong>'.$this->getNoticeCount().'</strong> '.$this->__('notice');
		endif;

		$msgStats = '';
		$c = count($sParts);
		for ($i = 0; $i < $c; $i++) {
		    $msgStats .= $sParts[$i] . ($i == $c-1 ? '' : ($i == $c-2 ? ' and ' : ', '));
		}

	?>
    <span class="f-right"><?php echo $this->__('You have %s unread message(s). <a href="%s">Go to messages inbox</a>.',
        $msgStats,
        $this->getNoticesInboxUrl()
    );?></span>
<?php /* ********** temporary commented
	<span class="f-right"><?php echo $this->__('You have %s, %s and %s unread messages. <a href="%s">Go to messages inbox</a>.',
        '<span class="critical"><strong>'.$this->getCriticalCount().'</strong> '.$this->__('critical').'</span>',
        '<strong>'.$this->getMajorCount().'</strong> '.$this->__('major'),
        '<strong>'.$this->getMinorCount().'</strong> '.$this->__('minor'),
        $this->getNoticesInboxUrl()
    );?></span>
******** */?>
    <?php if ($this->isMessageWindowAvailable()): ?>
        <strong class="label clickable" onclick="openMessagePopupWindow()">
    <?php else: ?>
        <strong class="label">
    <?php endif; ?>

    <?php echo $this->__('Latest Message:') ?></strong> <?php echo $this->getLatestNotice() ?> <a href="<?php echo $this->getLatestNoticeUrl() ?>" onclick="this.target='_blank';"><?php echo $this->__('Read details') ?></a>
</div>
<?php endif; ?>