<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo Mage::helper('install')->__('OpenMage Installation Wizard') ?></title>
<link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>prototype/prototype.js"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>prototype/validation.js"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>scriptaculous/effects.js"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>mage/translate.js" ></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>varien/js.js"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl() ?>varien/form.js"></script>
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/reset.css') ?>" type="text/css" media="all" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/boxes.css') ?>" type="text/css" media="all" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/clears.css') ?>" type="text/css" media="all" />

<?php echo $this->helper('core/js')->getTranslatorScript() ?>

</head>

<body>
<!-- [start] header -->
    <div class="header">
        <div class="header-top-container">
            <div class="header-top">
                <h1 id="logo">
                    <a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getSkinUrl('images/logo.svg') ?>" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('install')->__('OpenMage')) ?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('install')->__('OpenMage')) ?>" /></a>
                </h1>

                <?php echo $this->getChildHtml('topSearch') ?>

                <div class="quick-access">
                    <div class="account-access">
                       <strong>&nbsp;<?php echo $this->getWelcome() ?></strong> <?php echo $this->getChildHtml('topLeftLinks') ?>
                    </div>
                    <div class="shop-access">
                        <?php echo $this->getChildHtml('topRightLinks') ?>
                    </div>
                </div>

            </div>
        </div>
        <?php echo $this->getChildHtml('topMenu') ?>
    </div>
<!-- [end] header -->

        <!-- [start] middle -->
       <?php echo $this->getChildHtml('store') ?>
    <div class="middle-container">
        <div class="middle col-2-left-layout">
            <?php echo $this->getChildHtml('breadcrumbs') ?>

            <!-- [start] left -->
            <div class="col-left side-col">
                <?php echo $this->getChildHtml('left') ?>
            </div>
            <div id="main" class="col-main">
            <!-- [start] global messages -->
                <?php echo $this->getChildHtml('global_messages') ?>
            <!-- [end] global messages -->
            <!-- [start] content -->
                <?php echo $this->getChildHtml('content') ?>
            <!-- [end] content -->
            </div>
        </div>
            <!-- [end] center -->
    </div>
        <!-- [end] middle -->

        <!-- [start] footer -->
    <div class="footer-container">
        <div class="footer">
        <p class="legality">
            <?php echo Mage::helper('install')->__('Help Us to Keep OpenMage Healthy') ?> - <a href="https://github.com/OpenMage/magento-lts/issues" id="bug_tracking_link"><strong><?php echo Mage::helper('install')->__('Report All Bugs') ?></strong></a> <?php echo Mage::helper('install')->__('(ver. %s)', Mage::getOpenMageVersion()) ?><br/>
<script type="text/javascript">
//<![CDATA[
    $('bug_tracking_link').target = "varien_external";
//]]>
</script>
            <?php echo Mage::helper('install')->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')) ?>
        </p>
        </div>
    </div>
        <!-- [end] footer -->
    </body>
</html>
