<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?= Mage::helper('install')->__('OpenMage Installation Wizard') ?></title>

<link rel="icon" href="<?= $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?= $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />

<script type="text/javascript" src="<?= $this->getJsUrl() ?>prototype/prototype.js"></script>
<script type="text/javascript" src="<?= $this->getJsUrl() ?>prototype/validation.js"></script>
<script type="text/javascript" src="<?= $this->getJsUrl() ?>scriptaculous/effects.js"></script>
<script type="text/javascript" src="<?= $this->getJsUrl() ?>mage/translate.js" ></script>
<script type="text/javascript" src="<?= $this->getJsUrl() ?>varien/js.js"></script>
<script type="text/javascript" src="<?= $this->getJsUrl() ?>varien/form.js"></script>
<link rel="stylesheet" href="<?= $this->getSkinUrl('css/reset.css') ?>" type="text/css" media="all" />
<link rel="stylesheet" href="<?= $this->getSkinUrl('css/boxes.css') ?>" type="text/css" media="all" />
<link rel="stylesheet" href="<?= $this->getSkinUrl('css/clears.css') ?>" type="text/css" media="all" />

<?= $this->helper('core/js')->getTranslatorScript() ?>

</head>

<body>
<!-- [start] header -->
    <div class="header">
        <div class="header-top-container">
            <div class="header-top">
                <h1 id="logo">
                    <a href="<?= $this->getUrl('') ?>"><img src="<?= $this->getSkinUrl('images/logo.svg') ?>" title="<?= Mage::helper('core')->quoteEscape(Mage::helper('install')->__('OpenMage')) ?>" alt="<?= Mage::helper('core')->quoteEscape(Mage::helper('install')->__('OpenMage')) ?>" /></a>
                </h1>

                <?= $this->getChildHtml('topSearch') ?>

                <div class="quick-access">
                    <div class="account-access">
                       <strong>&nbsp;<?= $this->getWelcome() ?></strong> <?= $this->getChildHtml('topLeftLinks') ?>
                    </div>
                    <div class="shop-access">
                        <?= $this->getChildHtml('topRightLinks') ?>
                    </div>
                </div>

            </div>
        </div>
        <?= $this->getChildHtml('topMenu') ?>
    </div>
<!-- [end] header -->

        <!-- [start] middle -->
       <?= $this->getChildHtml('store') ?>
    <div class="middle-container">
        <div class="middle col-2-left-layout">
            <?= $this->getChildHtml('breadcrumbs') ?>

            <!-- [start] left -->
            <div class="col-left side-col">
                <?= $this->getChildHtml('left') ?>
            </div>
            <div id="main" class="col-main">
            <!-- [start] global messages -->
                <?= $this->getChildHtml('global_messages') ?>
            <!-- [end] global messages -->
            <!-- [start] content -->
                <?= $this->getChildHtml('content') ?>
            <!-- [end] content -->
            </div>
        </div>
            <!-- [end] center -->
    </div>
        <!-- [end] middle -->

        <!-- [start] footer -->
    <div class="footer-container">
        <div class="footer">
        <p class="legality">
            <?= Mage::helper('install')->__('Help Us to Keep OpenMage Healthy') ?> - <a href="https://github.com/OpenMage/magento-lts/issues" id="bug_tracking_link"><strong><?= Mage::helper('install')->__('Report All Bugs') ?></strong></a> <?= Mage::helper('install')->__('(ver. %s)', Mage::getOpenMageVersion()) ?><br/>
<script type="text/javascript">
//<![CDATA[
    $('bug_tracking_link').target = "varien_external";
//]]>
</script>
            <?= Mage::helper('install')->__('Magento is a trademark of Magento Inc. Copyright &copy; %s Magento Inc.', date('Y')) ?>
        </p>
        </div>
    </div>
        <!-- [end] footer -->
    </body>
</html>
