<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */
?>
<?php
/**
 * @var Mage_Sales_Block_Order_Comments $this
 * @see Mage_Sales_Block_Order_Comments
 * @var Mage_Sales_Block_Order_Comments $this
 */
?>
<?php if ($this->hasComments()):?>
    <div class="order-additional order-comments">
        <h2 class="sub-title"><?php echo $this->getTitle() ?></h2>
        <dl class="order-about">
            <?php foreach ($this->getComments() as $_commentItem): ?>
                <dt><?php echo $this->formatDate($_commentItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                <dd><?php echo $this->escapeHtml($_commentItem->getComment()) ?></dd>
            <?php endforeach ?>
        </dl>
    </div>
<?php endif ?>
