<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?= $this->getMessagesBlock()->toHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?= $this->__('My Orders') ?></h1>
</div>
<?= $this->getPagerHtml() ?>
<?php if($_orders->getSize()): ?>
<table class="data-table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?= $this->__('Order #') ?></th>
            <th><?= $this->__('Date') ?></th>
            <th><?= $this->__('Ship To') ?></th>
            <th><span class="nobr"><?= $this->__('Order Total') ?></span></th>
            <th><span class="nobr"><?= $this->__('Order Status') ?></span></th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($_orders as $_order): ?>
        <tr>
            <td><?= $_order->getRealOrderId() ?></td>
            <td><span class="nobr"><?= $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
            <td><?= $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td><?= $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td><em><?= $_order->getStatusLabel() ?></em></td>
            <td class="a-center">
                <span class="nobr"><a href="<?= $this->getViewUrl($_order) ?>"><?= $this->__('View Order') ?></a>
                    <?php /*<span class="separator">|</span><a href="<?= $this->getTrackUrl($_order) ?>"><?= $this->__('Track Order') ?></a>&nbsp;*/ ?>
                    <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                    <span class="separator">|</span> <a href="<?= $this->getReorderUrl($_order) ?>" class="link-reorder"><?= $this->__('Reorder') ?></a>
                <?php endif ?>
                </span>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?= $this->getPagerHtml() ?>
<?php else: ?>
    <p><?= $this->__('You have placed no orders.') ?></p>
<?php endif ?>
