<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
/**
 * @see Mage_Sales_Block_Order_Totals
 * @var Mage_Sales_Block_Order_Totals $this
 */
?>
<?php foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else: ?>
    <tr class="<?php echo $_code?>">
        <td <?php echo $this->getLabelProperties()?>>
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $this->escapeHtml($_total->getLabel());?></strong>
            <?php else: ?>
            <?php echo $this->escapeHtml($_total->getLabel());?>
            <?php endif ?>
        </td>
        <td <?php echo $this->getValueProperties()?>>
            <?php if ($_total->getStrong()):?>
            <strong><?php echo $this->formatValue($_total) ?></strong>
            <?php else: ?>
            <?php echo $this->formatValue($_total) ?>
            <?php endif ?>
        </td>
    </tr>
    <?php endif ?>
<?php endforeach ?>
