<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="order-items order-details">
    <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('items', $this->getOrder())): ?>
    <script type="text/javascript">
    //<![CDATA[
    function giftMessageToogle(giftMessageIdentifier)
    {
        var link = $('order-item-gift-message-link-'+giftMessageIdentifier);
        var container = $('order-item-gift-message-'+giftMessageIdentifier);
        var row = $('order-item-row-'+giftMessageIdentifier);
        if(link.expanded) {
            link.expanded = false;
            link.removeClassName('expanded');
            if(container.hasClassName('last')) {
                row.addClassName('last');
            }
            container.hide();
        } else {
            link.expanded = true;
            link.addClassName('expanded');
            if(container.hasClassName('last')) {
                row.removeClassName('last');
            }
            container.show();
        }

        return false;
    }
    //]]>
    </script>
    <?php endif ?>
    <?php $_order = $this->getOrder() ?>
    <h2 class="table-caption"><?= $this->__('Items Ordered') ?>
        <?php if ($_order->getTracksCollection()->count()) : ?>
            <span class="separator">|</span> <a href="#" onclick="popWin('<?= $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?= Mage::helper('core')->quoteEscape($this->__('Track your order')) ?>"><?= $this->__('Track your order') ?></a>
        <?php endif ?>
    </h2>

    <?= $this->getChildHtml('order_items') ?>

    <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order', $_order) && $_order->getGiftMessageId()): ?>
    <div class="order-additional order-gift-message">
        <h2 class="sub-title"><?= $this->__('Gift Message for This Order') ?></h2>
        <?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_order); ?>
        <dl class="gift-message">
            <dt><strong><?= $this->__('From:') ?></strong> <?= $this->escapeHtml($_giftMessage->getSender()) ?></dt>
            <dt><strong><?= $this->__('To:') ?></strong> <?= $this->escapeHtml($_giftMessage->getRecipient()) ?></dt>
            <dd><?= $this->helper('giftmessage/message')->getEscapedGiftMessage($_order) ?></dd>
        </dl>
    </div>
    <?php endif ?>
    <?php $_history = $this->getOrder()->getVisibleStatusHistory() ?>
    <?php if (count($_history)): ?>
    <div class="order-additional order-comments">
        <h2 class="sub-title"><?= $this->__('About Your Order') ?></h2>
        <dl class="order-about">
            <?php foreach ($_history as $_historyItem): ?>
                <dt><?= $this->formatDate($_historyItem->getCreatedAtStoreDate(), 'medium', true) ?></dt>
                <dd><?= $this->escapeHtml($_historyItem->getComment()) ?></dd>
            <?php endforeach ?>
        </dl>
    </div>
    <?php endif ?>
    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->getBackUrl() ?>"><small>&laquo; </small><?= $this->getBackTitle() ?></a></p>
    </div>
</div>
