<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @var Mage_Paypal_Block_Adminhtml_System_Config_Payflowlink_Advanced $this
 */
?>
<div class="payflow-settings-notice">
    <strong class="important-label"><?php echo $this->__('Important: ') ?></strong>
    <?php echo $this->__('To use PayPal Payments Advanced, you must configure  your PayPal Payments Advanced account on the PayPal website.'); ?>
    <?php echo $this->__('Once you log into your PayPal Advanced account, navigate to the Service Settings - Hosted Checkout Pages - Set Up menu and set the options described below') ?>
    <ul class="options-list">
        <li><strong>AVS:</strong> No</li>
        <li><strong>CSC:</strong> No</li>
        <li><strong>Enable Secure Token:</strong> Yes</li>
    </ul>
</div>
