<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php
/**
 * @see Mage_Paypal_Block_Adminhtml_System_Config_Payflowlink_Info
 * @var Mage_Paypal_Block_Adminhtml_System_Config_Payflowlink_Info $this
 */
?>
<div class="payflow-settings-notice">
    <strong class="important-label"><?php echo $this->__('Important: ') ?></strong>
    <?php echo $this->__('To use PayPal Payflow Link, you must configure your PayPal Payflow Link account on the PayPal website.'); ?>
    <?php echo $this->__('Once you log into your PayPal Payflow Link account, navigate to the Service Settings - Hosted Checkout Pages - Set Up menu and set the options described below') ?>
    <ul class="options-list">
        <li><strong>AVS:</strong> No</li>
        <li><strong>CSC:</strong> No</li>
        <li><strong>Enable Secure Token:</strong> Yes</li>
    </ul>
</div>
