<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Captcha_Block_Captcha_Zend
 * @var Mage_Captcha_Block_Captcha_Zend $this
 */
?>
<?php $captcha = $this->getCaptchaModel() ?>
<div class="clear"></div>
<div class="captcha">
    <div class="captcha-input input-box input-left">
        <label for="captcha"><?php echo $this->__('Please type the letters from the image:') ?></label><br />
        <input type="text" name="<?php echo Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?php echo $this->getFormId()?>]" id="captcha" class="required-entry input-text validation-failed"/>
    </div>
    <div class="captcha-image input-right">
        <img id="captcha-reload" class="captcha-reload" src="<?php echo $this->getSkinUrl('images/reload.png') ?>" alt="<?php echo $this->__('Reload captcha') ?>"/>
        <img id="<?php echo $this->getFormId() ?>" width="<?php echo $this->getImgWidth() ?>" height="<?php echo $this->getImgHeight() ?>" src="<?php echo $captcha->getImgSrc() ?>" />
    </div>
</div>
<?php if ($captcha->isCaseSensitive()) :?>
<div class="captcha-note">
    <p><?php echo $this->__('<strong>Attention</strong>: Captcha is case sensitive.') ?></p>
</div>
<?php endif ?>
<script type="text/javascript">
//<![CDATA[
    document.observe('dom:loaded', function () {
        var captcha = new Captcha('<?php echo $this->getRefreshUrl() ?>', '<?php echo $this->getFormId() ?>');

        $('captcha-reload').observe('click', function () {
            captcha.refresh(this);
        });

    });
//]]>
</script>
