<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     rwd_default
 */
?>
<?php
/**
 * "Remember Me" popup template (when click on "What's this?")
 *
 */
/** @var Mage_Core_Block_Template $this */
?>
<div class="remember-me-popup">
    <div class="remember-me-popup-head">
        <h3><?php echo $this->__("What's this?"); ?></h3>
        <a href="#" class="remember-me-popup-close" title="<?php echo $this->quoteEscape($this->__('Close')) ?>"><?php echo $this->__('Close') ?></a>
    </div>
    <div class="remember-me-popup-body">
        <p><?php echo $this->__('Checking &quot;Remember Me&quot; will let you access your shopping cart on this computer when you are logged out'); ?></p>
        <div class="remember-me-popup-close-button a-right">
            <a href="#" class="remember-me-popup-close button" title="<?php echo $this->quoteEscape($this->__('Close')) ?>"><span><?php echo $this->__('Close') ?></span></a>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
function toggleRememberMePopup() {
    var formParent = jQuery(this).parents('form:first');
    formParent.find('.remember-me-box a').toggleClass('hide');
    formParent.find('.remember-me-popup').toggleClass('show');
    return false;
}
var rememberMeToggleSetup = false;
jQuery(document).ready(function(){
    if (!rememberMeToggleSetup) {
        jQuery('.remember-me-box a, .remember-me-popup a').on('click', toggleRememberMePopup);
        rememberMeToggleSetup = true;
    }
});
//]]>
</script>
