<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($this->getCartHeader()): ?>
<div class="content-header skip-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h4><?php echo $this->getCartHeader(); ?></h4></td>
        </tr>
    </table>
</div>
<?php endif ?>
<?php echo $this->getGridParentHtml() ?>
<?php if($this->canDisplayContainer()): ?>
<script type="text/javascript">
<?php echo $this->getJsObjectName() ?>cartControl = {
    removeItem: function (itemId) {
        if (!itemId) {
            alert('<?php echo Mage::helper('customer')->__('No item specified.') ?>');
            return false;
        }
        if(!confirm('<?php echo Mage::helper('customer')->__('Are you sure that you want to remove this item?') ?>')) {
            return false;
        }
        <?php echo $this->getJsObjectName() ?>.reloadParams = {'delete':itemId}
        <?php echo $this->getJsObjectName() ?>.reload();
        <?php echo $this->getJsObjectName() ?>.reloadParams = {};
        return false;
    }
};
</script>
<?php endif ?>
<br />