<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Customer_Edit_Tab_Newsletter $this */
?>
<div class="entry-edit">
<?php echo $this->getFormObject()->getHtml() ?>
</div>
<?php echo $this->getChildHtml('grid') ?>
