<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Template for block Mage_Adminhtml_Block_Customer_Edit_Tab_View
 */
?>
<div class="entry-edit">
	<div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('customer')->__('Personal Information') ?></h4></div>
	<fieldset>
        <table cellspacing="2" class="box-left">
            <tr>
                <td><strong><?php echo $this->__('Last Logged In:') ?></strong></td>
                <td><?php echo $this->getLastLoginDate() ?> (<?php echo $this->getCurrentStatus() ?>)</td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Confirmed email:') ?></strong></td>
                <td><?php echo $this->getIsConfirmedStatus() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Account Created on:') ?></strong></td>
                <td><?php echo $this->getCreateDate() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Account Created in:') ?></strong></td>
                <td><?php echo $this->getCreatedInStore() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Customer Group:') ?></strong></td>
                <td><?php echo $this->getGroupName() ?></td>
            </tr>
        </table>
		<address class="box-right">
		<strong><?php echo $this->__('Primary Billing Address') ?></strong><br/>
		<?php echo $this->getBillingAddressHtml() ?>
	</fieldset>
</div>
<?php echo $this->getSalesHtml(); ?>
<div class="clear"></div>
<br/>
<?php echo $this->getAccordionHtml() ?>