<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * Template for block Mage_Adminhtml_Block_Customer_Edit_Tab_View
 *
 * @see Mage_Adminhtml_Block_Customer_Edit_Tab_View
 * @var Mage_Adminhtml_Block_Customer_Edit_Tab_View $this
 */
?>
<?php
$lastLoginDateAdmin = $this->getLastLoginDate();
$lastLoginDateStore = $this->getStoreLastLoginDate();

$createDateAdmin    = $this->getCreateDate();
$createDateStore    = $this->getStoreCreateDate();
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('customer')->__('Personal Information') ?></h4></div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <tr>
                <td><strong><?php echo $this->__('Last Logged In:') ?></strong></td>
                <td><?php echo $lastLoginDateAdmin ?> (<?php echo $this->getCurrentStatus() ?>)</td>
            </tr>
            <?php if ($lastLoginDateAdmin != $lastLoginDateStore): ?>
            <tr>
                <td><strong><?php echo $this->__('Last Logged In (%s):', $this->getStoreLastLoginDateTimezone()) ?></strong></td>
                <td><?php echo $lastLoginDateStore ?> (<?php echo $this->getCurrentStatus() ?>)</td>
            </tr>
            <?php endif ?>
            <tr>
                <td><strong><?php echo $this->__('Confirmed email:') ?></strong></td>
                <td><?php echo $this->getIsConfirmedStatus() ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Account Created on:') ?></strong></td>
                <td><?php echo $createDateAdmin ?></td>
            </tr>
            <?php if ($createDateAdmin != $createDateStore): ?>
            <tr>
                <td><strong><?php echo $this->__('Account Created on (%s):', $this->getStoreCreateDateTimezone()) ?></strong></td>
                <td><?php echo $createDateStore ?></td>
            </tr>
            <?php endif ?>
            <tr>
                <td><strong><?php echo $this->__('Account Created in:') ?></strong></td>
                <td><?php echo $this->escapeHtml($this->getCreatedInStore()); ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Customer Group:') ?></strong></td>
                <td><?php echo $this->escapeHtml($this->getGroupName()) ?></td>
            </tr>
        </table>
        <address class="box-right">
            <strong><?php echo $this->__('Default Billing Address') ?></strong><br/>
            <?php echo $this->maliciousCodeFilter($this->getBillingAddressHtml()) ?>
        </address>
    </fieldset>
</div>
<?php echo $this->getChildHtml('', true, true); ?>
