<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /* @var $this Mage_Sales_Block_Billing_Agreements */ ?>
<div class="page-title">
    <h1><?= $this->__('Billing Agreements') ?></h1>
</div>

<?= $this->getMessagesBlock()->toHtml() ?>

<div class="billing-agreements">
    <?php $billingAgreements = $this->getBillingAgreements(); ?>
    <?php if (count($billingAgreements) > 0): ?>
        <?= $this->getChildHtml('pager') ?>
        <table id="billing-agreements" class="data-table linearize-table">
            <col />
            <col width="1" />
            <col />
            <col />
            <col />
            <col width="1" />
            <thead>
            <tr>
                <th class="reference-id"><span class="nobr"><?= $this->__('Reference ID') ?></span></th>
                <th class="status"><?= $this->__('Status') ?></th>
                <th class="created-at"><span class="nobr"><?= $this->__('Created At') ?></span></th>
                <th class="updated-at"><span class="nobr"><?= $this->__('Updated At') ?></span></th>
                <th class="payment-method"><span class="nobr"><?= $this->__('Payment Method') ?></span></th>
                <th class="actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($billingAgreements as $item): ?>
                <tr>
                    <td class="reference-id"><span class="nobr"><?= $this->getItemValue($item, 'reference_id') ?></span></td>
                    <td class="status" data-rwd-label="Status"><?= $this->getItemValue($item, 'status') ?></td>
                    <td class="created-at" data-rwd-label="Created at"><span class="nobr"><?= $this->getItemValue($item, 'created_at') ?></span></td>
                    <td class="updated-at" data-rwd-label="Updated at"><span class="nobr"><?= $this->getItemValue($item, 'updated_at') ?></span></td>
                    <td class="payment-method" data-rwd-label="Payment method"><?= $this->getItemValue($item, 'payment_method_label') ?></td>
                    <td class="actions"><a href="<?= $this->getItemValue($item, 'edit_url') ?>"><?= $this->__('View') ?></a></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('billing-agreements')</script>
    <?php else: ?>
        <p><?php echo $this->__('There are no billing agreements yet.')?></p>
    <?php endif ?>

    <?php $paymentMethods = $this->getWizardPaymentMethodOptions() ?>
    <?php if ($paymentMethods): ?>
        <div class="info-box">
            <h2 class="box-title"><?= $this->__('New Billing Agreement') ?></h2>
            <form action="<?= $this->getCreateUrl() ?>" method="post">
                <div class="box-content">
                    <p><?= $this->__('You will be redirected to the payment system website.') ?></p>
                    <ul class="form-list">
                        <li>
                            <select id="payment_method" name="payment_method">
                                <option value=""><?= $this->__('-- Please Select --') ?></option>
                                <?php foreach ($paymentMethods as $code => $title): ?>
                                    <option value="<?= $code ?>"><?= $title ?></option>
                                <?php endforeach ?>
                            </select>
                            <button type="submit" class="button"><span><span><?= $this->__('Create...') ?></span></span></button>
                        </li>
                    </ul>
                </div>
            </form>
        </div>
    <?php endif ?>

    <div class="buttons-set">
        <p class="back-link"><a href="<?= $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?= $this->__('Back') ?></a></p>
    </div>
</div>
