<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<script type="text/javascript">
var added = false, parent = <?php echo $this->getRequest()->getParam('popin' ) ? 'self.parent' : 'window.opener' ?>;
function addProduct(closeAfter) {
    if (parent!=null && !added) {
        <?php if ($this->isEdit()): ?>
        parent.superProduct.updateProduct(<?php echo $this->getProductId() ?>, <?php echo $this->getAttributesJson() ?>);
        <?php else: ?>
        parent.superProduct.addNewProduct(<?php echo $this->getProductId() ?>, <?php echo $this->getAttributesJson() ?>);
        parent.superProduct.showNoticeMessage();
        <?php endif ?>
        added = true;
    }

    if (closeAfter) {
        closeWindow();
    }
}

function closeWindow() {
    if (parent) {
        parent.focus();
    }
    <?php if ($this->getRequest()->getParam('popin')): ?>
        parent.superProduct.closePopup();
    <?php else: ?>
        window.close();
    <?php endif ?>
}

addProduct(false);
setTimeout(closeWindow, 3000);
</script>
<div class="a-center">
<?php echo $this->getCloseButtonHtml() ?>
</div>
