<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<script type="text/javascript">
//<![CDATA[

function toggleValueElement(element) {
    var disabled = false;
    if (element.value == 1) {
        // use default value
        disabled = true;
    }
    document.getElementById('plain_value').disabled = disabled;
    document.getElementById('html_value').disabled = disabled;
    if (disabled) {
        document.getElementById('plain_value').classList.add('disabled');
        document.getElementById('html_value').classList.add('disabled');
    } else {
        document.getElementById('plain_value').classList.remove('disabled');
        document.getElementById('html_value').classList.remove('disabled');
    }
}

//]]>
</script>
