<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>

<?php
/**
 * JS block for including Countries with Optional Zip
 *
 * @see Mage_Core_Block_Template
 * @var Mage_Core_Block_Template $this
 */
?>
<?php $optional_zip_countries = $this->helper('directory')->getCountriesWithOptionalZip(false) ?>
<?php if (!empty($optional_zip_countries)): ?>
    <script>
        //<![CDATA[
        optionalZipCountries = <?php echo $this->helper('core')->jsonEncode($optional_zip_countries); ?>;
        //]]>
    </script>
<?php endif ?>
