<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2023 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
/**
 * JS block for including Countries with Optional Zip
 *
 * @see Mage_Core_Block_Template
 */
?>
<?php $optional_zip_countries = $this->helper('directory')->getCountriesWithOptionalZip(false) ?>
<?php if (!empty($optional_zip_countries)): ?>
    <script>
        //<![CDATA[
        optionalZipCountries = <?php echo $this->helper('core')->jsonEncode($optional_zip_countries); ?>;
        //]]>
    </script>
<?php endif ?>
