<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Ajax_Serializer
 * @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Ajax_Serializer $this
 */
?>

<?php $_id = 'id_' . md5(microtime()) ?>
<input type="hidden" name="<?php echo $this->getInputElementName()?>"  value="" id="<?php echo $_id?>" />
<script type="text/javascript">
// create serializer controller, that will syncronize grid checkboxes with hidden input
new productLinksController('<?php echo $_id?>', <?php echo $this->getProductsJSON() ?>, <?php echo $this->getGridBlock()->getJsObjectName() ?>);
</script>
