<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2><?= $this->__('Recent Orders') ?></h2>
        <?php if(count($_orders->getItems()) > 0): ?><a href="<?= $this->getUrl('sales/order/history') ?>"><?= $this->__('View All') ?></a><?php endif ?>
    </div>
<?php if(count($_orders->getItems()) > 0): ?>
    <table class="data-table orders" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
        <thead>
            <tr>
                <th class="number"><?= $this->__('Order #') ?></th>
                <th class="date"><?= $this->__('Date') ?></th>
                <th class="ship"><?= $this->__('Ship To') ?></th>
                <th class="total"><span class="nobr"><?= $this->__('Order Total') ?></span></th>
                <th class="status"><?= $this->__('Status') ?></th>
                <th class="view">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td class="number"><?= $_order->getRealOrderId() ?></td>
                    <td class="date"><span class="nobr"><?= $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td class="ship"><?= $_order->getShippingAddress() ? $this->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td class="total"><?= $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td class="status"><em><?= $_order->getStatusLabel() ?></em></td>
                    <td class="a-center view">
                        <span class="nobr">
                        <a href="<?= $this->getViewUrl($_order) ?>"><?= $this->__('View Order') ?></a>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span class="separator">|</span> <a href="<?= $this->getReorderUrl($_order) ?>" class="link-reorder"><?= $this->__('Reorder') ?></a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?= $this->__('You have placed no orders.') ?></p>
<?php endif ?>
</div>
