<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @see Mage_Adminhtml_Block_Denied
 * @var Mage_Adminhtml_Block_Denied $this
 */
?>
<h1 class="page-heading"><?php echo $this->helper('adminhtml')->__('Access denied') ?></h1>
<?php if (!$this->hasAvailaleResources()): ?>
<p>
<?php echo $this->helper('adminhtml')->__('Please try to logout and sign in again.') ?><br/>
<?php echo $this->helper('adminhtml')->__('If this message persists, please contact the store owner.') ?>
</p>
<?php else: ?>
<p><?php echo $this->helper('adminhtml')->__('Access denied.') ?></p>
<?php endif ?>
