<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<div class="content-header">
<h3><?php echo Mage::helper('adminhtml')->__('Sorry, this feature is coming soon...') ?></h3>
</div>
<p><?php echo Mage::helper('adminhtml')->__("We're in our typing table, coding away more features for Magento. Thank you for your patience.") ?></p>
