<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /*{
    "label":"Root page layout",
    "type":"core/template",
    "children":{
        "header":{ "label":"Header", "type":"adminhtml/page_header" },
        "menu":{ "label":"Top navigation", "type":"adminhtml/page_menu" },
        "breadcrumbs":{ "label":"Breadcrumbs", "type":"adminhtml/widget_breadcrumbs" },
        "content":{ "label":"Content block", "type":"core/template" },
        "left":{ "label":"Left navigation", "type":"core/template" },
        "footer":{ "label":"Footer", "type":"adminhtml/page_footer" }
    },
    "vars":{}
}*/ ?>
<!DOCTYPE html>
<html lang="<?= $this->getLang() ?>">
<head>
<?= $this->getChildHtml('head') ?>
</head>
<body id="html-body"<?= $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<div class="wrapper-popup">
    <div class="middle" id="anchor-content">
        <div id="page:main-container">
        <?php if($this->getChildHtml('left')): ?>
            <div class="columns <?= $this->getContainerCssClass() ?>" id="page:container">
                <div id="page:left" class="side-col">
                    <?= $this->getChildHtml('left') ?>
                </div>
                <div class="main-col" id="content">
                    <div class="main-col-inner">
                        <div id="messages"><?= $this->getMessagesBlock()->toHtml() ?></div>
                        <?= $this->getChildHtml('content') ?>
                    </div>
                </div>
            </div>
      <?php else: ?>
          <div id="messages"><?= $this->getMessagesBlock()->toHtml() ?></div>
          <?= $this->getChildHtml('content') ?>
      <?php endif ?>
         </div>
    </div>
    <?php if($this->getChildHtml('footer')): ?>
    <div class="footer">
        <?= $this->getChildHtml('footer') ?>
    </div>
    <?php endif ?>
    <?= $this->getChildHtml('js') ?>
    <?= $this->getChildHtml('profiler') ?>
    <div id="loading-mask" style="display:none;">
        <div class="backdrop"></div>
        <p class="loader" id="loading_mask_loader">
            <img src="<?= $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?= Mage::helper('core')->quoteEscape(Mage::helper('adminhtml')->__('Loading...')) ?>"/><br/><?= Mage::helper('adminhtml')->__('Please wait...') ?>
        </p>
    </div>
</div>
<?= $this->getChildHtml('before_body_end') ?>
</body>
</html>
