<div class="content-header">
    <h3><?php echo $this->__('Import / Export FAQ (Frequently Asked Questions)'); ?></h3>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Import FAQ'); ?></h4>
    </div>
    <div class="fieldset ">
        Import FAQ Cantent
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Export FAQ'); ?></h4>
    </div>
    <div class="fieldset ">
        Export FAQ Cantent
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Some other FAQ'); ?></h4>
    </div>
    <div class="fieldset ">
        Some other FAQ Cantent
    </div>
</div>
