<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/** @var Mage_Oauth_Block_Customer_Token_List $this */
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Applications') ?></h1>
</div>
<?php if ($this->getCollection() && $this->count()): ?>
    <?php echo $this->getToolbarHtml() ?>
        <table class="data-table" id="my-apps-table">
            <col />
            <col width="100" align="right" />
            <col width="110" align="right" />
            <thead>
                <tr>
                    <th><?php echo $this->__('App Name') ?></th>
                    <th><?php echo $this->__('Status') ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php /** @var Mage_Oauth_Model_Token $item */ ?>
                <?php foreach ($this->getCollection() as $item) : ?>
                <tr>
                    <td><span class="app-name">
                        <?php echo $this->escapeHtml($item->getName()); ?></span></td>
                    <td><em><?php echo $this->getStatusLabel($item->getRevoked()) ?></em></td>
                    <td align="right">
                        <a href="<?php echo $this->getUpdateRevokeLink($item)?>" class="nobr"
                            onclick="return confirm('<?php echo $this->getChangeStatusConfirmMessage($item->getRevoked()) ?>')">
                            <?php echo $this->getChangeStatusLabel($item->getRevoked()) ?></a>
                        <span class="separator">|</span> <a href="<?php echo $this->getDeleteLink($item)?>" class="nobr"
                            onclick="return confirm('<?php echo $this->__('Are you sure you want to delete this application?') ?>')">
                        <?php echo $this->__('Delete') ?></a></td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
        <script type="text/javascript">
        //<![CDATA[
            decorateTable('my-apps-table');
        //]]>
        </script>
    <?php echo $this->getToolbarHtml() ?>
<?php else: ?>
    <p><?php echo $this->__('You have no applications.'); ?></p>
<?php endif ?>
