<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>
<?php
/**
 * @var Mage_Catalog_Block_Product_View_Options_Type_Default $this
 */
?>
<?php $_option = $this->getOption() ?>
<dt>
    <label><?php echo  $this->escapeHtml($_option->getTitle()) ?></label>
</dt>
