<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>
<?php
/**
 * @see Mage_Paypal_Block_Logo
 * @var Mage_Paypal_Block_Logo $this
 * @deprecated
 */
?>
<div class="paypal-logo">
    <a href="#" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('paypal')->__('Additional Options')) ?>" onclick="javascript:window.open('<?php echo $this->getAboutPaypalPageUrl() ?>','paypal','width=600,height=350,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;"><img src="<?php echo $this->escapeHtml($this->getLogoImageUrl()) ?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('paypal')->__('Additional Options')) ?>" title="<?php echo Mage::helper('paypal')->__('Additional Options') ?>" /></a>
</div>
