<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     rwd_default
 */
?>
<?php
/**
 * @var Mage_Page_Block_Html $this
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang(); ?>" id="top" class="no-js">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-popup <?php echo $this->getBodyClass()?$this->getBodyClass() : ''?>">
<div>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('content') ?>
    <?php echo $this->getChildHtml('before_body_end') ?>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
