<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Template
 * @var Mage_Adminhtml_Block_Template $this
 */
?>
<script type="text/javascript">
//<![CDATA[
    /**
     * Post form data and process response via AJAX.
     *
     * @return void
     */
    varienForm.prototype.getFilter = function()
    {
        if (document.getElementById('entity') && document.getElementById('entity').value) {
            var url = "<?php echo $this->getUrl('*/*/getFilter') ?>";
            url += ((url.slice(-1) != '/') ? '/' : '') + 'entity/' + document.getElementById('entity').value;

            fetch(url, {
                method: 'POST',
                headers: {'X-Requested-With': 'XMLHttpRequest'}
            }).then(function(response) { return response.text(); }).then(function(responseText) {
                    responseText = responseText.replace(/>\s+</g, '><');
                    document.getElementById('export_filter_grid_container').innerHTML = responseText;
                    document.getElementById('export_filter_container').style.display = '';
            });
        } else {
            document.getElementById('export_filter_container').style.display = 'none';
        }
    };

    /**
     * Continue export process after filter settings.
     *
     * return void
     */
    function getFile()
    {
        if (document.getElementById('entity') && document.getElementById('file_format')) {
            var form      = document.getElementById('export_filter_form');
            var oldAction = form.action;
            form.action   = oldAction + ((oldAction.slice(-1) != '/') ? '/' : '') + 'entity/' + document.getElementById('entity').value + '/file_format/' + document.getElementById('file_format').value;
            form.submit();
            form.action   = oldAction;
        } else {
            alert('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Invalid data')) ?>');
        }
    }
//]]>
</script>
