<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Template
 * @var Mage_Adminhtml_Block_Template $this
 */
?>
<script type="text/javascript">
//<![CDATA[
    /**
     * Post form data and process response via AJAX.
     *
     * @return void
     */
    varienForm.prototype.getFilter = function()
    {
        if ($('entity') && $F('entity')) {
            var url = "<?php echo $this->getUrl('*/*/getFilter') ?>";
            url += ((url.slice(-1) != '/') ? '/' : '') + 'entity/' + $F('entity');

            new Ajax.Request(url, {
                method:      'post',
                //parameters:  $(this.formId).serialize(),
                evalScripts: true,
                onComplete:  function(transport) {
                    var responseText = transport.responseText.replace(/>\s+</g, '><');
                    $('export_filter_grid_container').update(responseText);
                    $('export_filter_container').show();
                }
            });
        } else {
            $('export_filter_container').hide();
        }
    };

    /**
     * Continue export process after filter settings.
     *
     * return void
     */
    function getFile()
    {
        if ($('entity') && $('file_format')) {
            var form      = $('export_filter_form');
            var oldAction = form.action;
            form.action   = oldAction + ((oldAction.slice(-1) != '/') ? '/' : '') + 'entity/' + $F('entity') + '/file_format/' + $F('file_format');
            form.submit();
            form.action   = oldAction;
        } else {
            alert('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Invalid data')) ?>');
        }
    }
//]]>
</script>
