<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @var Mage_Authorizenet_Block_Directpost_Iframe $this
 */
?>
<?php
$_params = $this->getParams();
/* @var $_helper Mage_Authorizenet_Helper_Data  */
$_helper = $this->helper('authorizenet');
?>
<html>
<head>
<script type="text/javascript">
//<![CDATA[
<?php if (isset($_params['redirect'])): ?>
window.location="<?php echo $this->escapeUrl($_params['redirect']) ?>";
<?php endif ?>
<?php if (isset($_params['redirect_parent'])): ?>
window.top.location="<?php echo $this->escapeUrl($_params['redirect_parent']) ?>";
<?php endif ?>
<?php if (isset($_params['error_msg'])): ?>
window.top.directPostModel.showError(<?php echo $this->helper('core')->jsonEncode($_params['error_msg']) ?>);
<?php if (isset($_params['x_invoice_num'])): ?>
window.top.directPostModel.successUrl="<?php echo $_helper->getSuccessOrderUrl($_params) ?>";
<?php endif ?>
<?php endif ?>
//]]>
</script>
</head>
<body></body>
</html>
