<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_Authorizenet_Block_Directpost_Form
 * @var Mage_Authorizenet_Block_Directpost_Form $this 
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
    <?php echo $this->__('You will be required to enter your payment details before you place an order.') ?>
    </li>
</ul>
