<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Authorizenet_Block_Directpost_Form
 * @var Mage_Authorizenet_Block_Directpost_Form $this 
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
    <?php echo $this->__('You will be required to enter your payment details before you place an order.') ?>
    </li>
</ul>
