<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Authorizenet_Block_Directpost_Form
 * @var Mage_Authorizenet_Block_Directpost_Form $this 
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
    <?php echo $this->__('You will be required to enter your payment details before you place an order.') ?>
    </li>
</ul>
