<?php
/**
 * OpenMage
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
 ?>
<?php /* @var $this Mage_Adminhtml_Block_Customer_Edit_Tab_View_Grid_Renderer_Item */ ?>
<?php
    $product = $this->getProduct();
    $options = $this->getOptionList();
?>

<?php if (!$options): ?>
    <?php echo $this->escapeHtml($product->getName())?>
<?php else: ?>
<div class="bundle-product-options">
    <strong><?php echo $this->escapeHtml($product->getName())?></strong>
    <dl>
        <?php foreach ($options as $option) : ?>
            <dt><?php echo $this->escapeHtml($option['label']) ?></dt>
            <?php $formatedOptionValue = $this->getFormattedOptionValue($option) ?>
            <dd><?php echo $formatedOptionValue['value'] ?></dd>
        <?php endforeach ?>
    </dl>
</div>
<?php endif ?>
