<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Checkout_Block_Multishipping_Link
 * @var Mage_Checkout_Block_Multishipping_Link $this
 */
?>
<a href="<?php echo $this->getCheckoutUrl()?>" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('checkout')->__('Checkout with Multiple Addresses')); ?>"><?php echo Mage::helper('checkout')->__('Checkout with Multiple Addresses');?></a>
