<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_Checkout_Block_Multishipping_Link
 * @var Mage_Checkout_Block_Multishipping_Link $this
 */
?>
<a href="<?php echo $this->getCheckoutUrl()?>" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('checkout')->__('Checkout with Multiple Addresses')); ?>"><?php echo Mage::helper('checkout')->__('Checkout with Multiple Addresses');?></a>
