<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>
<?php
/**
 * Mustishipping state
 *
 * @see Mage_Checkout_Block_Multishipping_State
 * @var Mage_Checkout_Block_Multishipping_State $this 
 */
?>
<ul class="checkout-progress" id="checkout-progress-state">
<?php foreach ($this->getSteps() as $_step): ?>
    <li title="<?php echo $_step->getLabel() ?>"<?php if($_step->getIsActive()): ?> class="active"<?php endif ?>><span><?php echo $_step->getLabel() ?></span></li>
<?php endforeach ?>
</ul>
<script type="text/javascript">decorateGeneric($$('#checkout-progress-state li'), ['first','last']);</script>
