<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_GiftMessage_Block_Adminhtml_Sales_Order_Create_Giftoptions
 * @var Mage_GiftMessage_Block_Adminhtml_Sales_Order_Create_Giftoptions $this
 */
?>

<?php $_item = $this->getItem() ?>
<?php if ($_item): ?>
    <?php $_childHtml = trim($this->getChildHtml('', false));?>
    <?php if ($_childHtml): ?>
        <tr class="border">
            <td class="first">
                <div>
                    <strong><a class="action-link" href="#" id="gift_options_link_<?php echo $_item->getId() ?>"><?php echo Mage::helper('sales')->__('Gift Options') ?></a></strong><br/>
                </div>
                <script type="text/javascript">
                    giftOptionsTooltip.addTargetLink('gift_options_link_<?php echo $_item->getId() ?>', <?php echo $_item->getId() ?>);
                </script>
                <div id="gift_options_data_<?php echo $_item->getId() ?>">
                    <?php echo $_childHtml ?>
                </div>
            </td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td class="last"></td>
        </tr>
    <?php endif ?>
<?php endif ?>
