<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @see Mage_GiftMessage_Block_Adminhtml_Sales_Order_Create_Items
 * @var Mage_GiftMessage_Block_Adminhtml_Sales_Order_Create_Items $this
 */
?>

<?php if ($this->canDisplayGiftMessage()): ?>
    <div class="no-display">
        <div id="gift-message-form-data-<?php echo $this->getItem()->getId(); ?>">
            <?php echo $this->getFormHtml();?>
        </div>

        <?php if ($this->getMessageText()): ?>
        <div class="gift-options-tooltip-content">
            <div><strong><?php echo $this->helper('giftmessage')->__('Gift Message')?></strong>:</div>
            <div><?php echo $this->getMessageText(); ?></div>
        </div>
        <?php endif ?>
    </div>
<?php endif ?>
