<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_GiftMessage_Block_Adminhtml_Sales_Order_Create_Items
 * @var Mage_GiftMessage_Block_Adminhtml_Sales_Order_Create_Items $this
 */
?>

<?php if ($this->canDisplayGiftMessage()): ?>
    <div class="no-display">
        <div id="gift-message-form-data-<?php echo $this->getItem()->getId(); ?>">
            <?php echo $this->getFormHtml();?>
        </div>

        <?php if ($this->getMessageText()): ?>
        <div class="gift-options-tooltip-content">
            <div><strong><?php echo $this->helper('giftmessage')->__('Gift Message')?></strong>:</div>
            <div><?php echo $this->getMessageText(); ?></div>
        </div>
        <?php endif ?>
    </div>
<?php endif ?>
