<?php
/**
 * OpenMage
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<script type="text/javascript">
//<![CDATA[

function toggleValueElement(element) {
    var disabled = false;
    if (element.value == 1) {
        // use default value
        disabled = true;
    }
    $('plain_value').disabled = disabled;
    $('html_value').disabled = disabled;
    if (disabled) {
        $('plain_value').addClassName('disabled');
        $('html_value').addClassName('disabled');
    } else {
        $('plain_value').removeClassName('disabled');
        $('html_value').removeClassName('disabled');
    }
}

//]]>
</script>
