<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<script type="text/javascript">
//<![CDATA[

function toggleValueElement(element) {
    var disabled = false;
    if (element.value == 1) {
        // use default value
        disabled = true;
    }
    $('plain_value').disabled = disabled;
    $('html_value').disabled = disabled;
    if (disabled) {
        $('plain_value').addClassName('disabled');
        $('html_value').addClassName('disabled');
    } else {
        $('plain_value').removeClassName('disabled');
        $('html_value').removeClassName('disabled');
    }
}

//]]>
</script>
