<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @see Mage_Payment_Block_Info_Checkmo
 * @var Mage_Payment_Block_Info_Checkmo $this
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if($this->getInfo()->getAdditionalData()): ?>
    {{pdf_row_separator}}
    <?php if($this->getPayableTo()): ?>
        <?php echo Mage::helper('payment')->__('Make Check payable to: %s', $this->escapeHtml($this->getPayableTo())) ?>
        {{pdf_row_separator}}
    <?php endif ?>
    <?php if($this->getMailingAddress()): ?>
        <?php echo Mage::helper('payment')->__('Send Check to:') ?>
        {{pdf_row_separator}}
        <?php echo nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        {{pdf_row_separator}}
    <?php endif ?>
<?php endif ?>
