<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Payment_Block_Info_Checkmo
 * @var Mage_Payment_Block_Info_Checkmo $this
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if($this->getInfo()->getAdditionalData()): ?>
    {{pdf_row_separator}}
    <?php if($this->getPayableTo()): ?>
        <?php echo Mage::helper('payment')->__('Make Check payable to: %s', $this->escapeHtml($this->getPayableTo())) ?>
        {{pdf_row_separator}}
    <?php endif ?>
    <?php if($this->getMailingAddress()): ?>
        <?php echo Mage::helper('payment')->__('Send Check to:') ?>
        {{pdf_row_separator}}
        <?php echo nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        {{pdf_row_separator}}
    <?php endif ?>
<?php endif ?>
