<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @see Mage_Payment_Block_Info_Purchaseorder
 * @var Mage_Payment_Block_Info_Purchaseorder $this
 */
?>
<?php echo Mage::helper('payment')->__('Purchase Order Number: %s', $this->escapeHtml($this->getInfo()->getPoNumber())) ?>
    {{pdf_row_separator}}

