<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Adminhtml_Block_Store_Switcher_Form_Renderer_Fieldset
 * @var Mage_Adminhtml_Block_Store_Switcher_Form_Renderer_Fieldset $this
 */
?>
<?php $_element = $this->getElement() ?>
<?php if ($_element->getFieldsetContainerId()): ?>
<div id="<?php echo $_element->getFieldsetContainerId(); ?>">
<?php endif ?>
<?php if ($_element->getLegend()): ?>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $_element->getLegend() ?></h4>
    <div class="form-buttons"><?php echo $_element->getHeaderBar() ?></div>
</div>
<?php endif ?>
<?php if (!$_element->getNoContainer()): ?>
    <div class="fieldset <?php echo $_element->getClass() ?>" id="<?php echo $_element->getHtmlId() ?>">
<?php endif ?>
<div class="store-scope">
    <div class="tree-store-scope">
        <?php if ($_element->getComment()): ?>
            <p class="comment"><?php echo $this->escapeHtml($_element->getComment()) ?></p>
        <?php endif ?>
        <?php if ($_element->hasHtmlContent()): ?>
            <?php echo $_element->getHtmlContent(); ?>
        <?php else: ?>
        <table cellspacing="0" class="<?php echo $_element->hasTableClass() ? $_element->getTableClass() : 'form-list'?>">
            <tbody>
                <?php echo $_element->getChildrenHtml(); ?>
            </tbody>
        </table>
        <?php endif ?>
    </div>
</div>
    <?php echo $_element->getSubFieldsetHtml() ?>
<?php if (!$_element->getNoContainer()): ?>
    </div>
<?php endif ?>
<?php if ($_element->getFieldsetContainerId()): ?>
</div>
<?php endif ?>
