<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Cache_Additional $this */
?>
<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('adminhtml')->__('Additional Cache Management') ?></h3></td>
            <td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanImagesUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush Catalog Images Cache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Pregenerated product images files.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanSwatchesUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush Swatch Images Cache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Pregenerated configurable swatches image files.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanMediaUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush JavaScript/CSS Cache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Themes JavaScript and CSS files combined to one file.')?>
        </td>
    </tr>
</table>
<?php echo $this->getChildHtml(); ?>
