<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Newsletter_Template $this */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-newsletter"><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?php $title = Mage::helper('newsletter')->__('Add New Template'); ?>
                <button class="scalable add" title="<?php echo $title; ?>" onclick="window.location='<?php echo $this->getCreateUrl() ?>'"><span><span><span><?php echo $title; ?></span></span></span></button>
            </td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getChildHtml('grid') ?>
</div>
