<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="widget widget-compared">
    <div class="widget-title">
        <h2><?= $this->__('Recently Compared') ?></h2>
    </div>
    <div class="widget-products">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])); ?>
        <?php $i=0; ?>
        <ul class="products-grid products-grid--max-<?= $_columnCount ?>-col-widget">
            <?php foreach ($_products as $_product): ?>
                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif ?>">
                    <?php $_imgSize = 210; ?>
                    <a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                        <img src="<?= $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize) ?>" alt="<?= $this->stripTags($_product->getName(), null, true) ?>" />
                    </a>
                    <div class="product-info">
                        <h3 class="product-name"><a href="<?= $_product->getProductUrl() ?>" title="<?= $this->stripTags($_product->getName(), null, true) ?>)"><?= $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                        <?= $this->getPriceHtml($_product, true, '-widget-compared-grid') ?>
                        <?= $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <button type="button"
                                        title="<?= Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                                        class="button btn-cart"
                                        onclick="customFormSubmit(
                                                '<?= $this->getAddToCartUrlCustom($_product, [], false) ?>',
                                                '<?= $_params ?>',
                                                'post')">
                                    <span><span><?= $this->__('Add to Cart') ?></span></span>
                                </button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?= $this->__('Out of stock') ?></span></p>
                            <?php endif ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <?php $_wishlistUrl = $this->getAddToWishlistUrlCustom($_product, false); ?>
                                    <li>
                                        <a href="#"
                                           data-url="<?= $_wishlistUrl ?>"
                                           data-params="<?= $_params ?>"
                                           class="link-wishlist"
                                           onclick="customFormSubmit('<?= $_wishlistUrl ?>', '<?= $_params ?>', 'post')">
                                            <?= $this->__('Add to Wishlist') ?>
                                        </a>
                                    </li>
                                <?php endif ?>
                                <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)) : ?>
                                    <li>
                                        <span class="separator">|</span>
                                        <a href="#"
                                           class="link-compare"
                                           onclick="customFormSubmit('<?= $_compareUrl ?>', '<?= $_params ?>', 'post')">
                                        </a>
                                    </li>
                                <?php endif ?>
                            </ul>
                        </div>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
<?php endif ?>
