<?php
/**
 * OpenMage
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_iphone
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <div class="pager">
        <p class="amount" style="display:none;">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('%s-%s/%s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif ?>
        </p>

        <?php echo $this->getPagerHtml() ?>

    </div>

    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <div class="sort-by">
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a class="order asc" href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>">&nbsp;</a>
            <?php else: ?>
                <a class="order desc" href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>">&nbsp;</a>
            <?php endif ?>
            <label for="sort_by"><?php echo $this->__('Sort') ?></label>
            <span class="sort-by-wrap">
            <select id="sort_by" onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach ?>
            </select>
            </span>
        </div>
    </div>
    <?php endif ?>
</div>
<?php endif ?>
