<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php
/**
 * @see Mage_Paypal_Block_Adminhtml_System_Config_BmlApiWizard
 * @var Mage_Paypal_Block_Adminhtml_System_Config_BmlApiWizard $this
 */
?>
<div class="pp-buttons-container">
    <button onclick="javascript:window.open('<?php echo $this->getButtonUrl()?>', 'bmlapiwizard','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=550, height=550'); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
        <span><span><span><?php echo $this->escapeHtml($this->getButtonLabel()); ?></span></span></span>
    </button>
</div>
