<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Paygate_Block_Authorizenet_Info_Cc
 * @var Mage_Paygate_Block_Authorizenet_Info_Cc $this
 */
?>
<div class="cards-list">

<?php if (!$this->getHideTitle()): ?>
    <div class="bold"><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></div>
<?php endif ?>

<?php
    $cards = $this->getCards();
    $showCount = count($cards) > 1;
?>
    <?php foreach ($cards as $key => $card): ?>
        <?php if ($showCount): ?>
            <span><?php echo sprintf($this->__('Credit Card %s'), $key + 1); ?></span>
        <?php endif ?>

        <table class="info-table<?php if ($showCount):?> offset<?php endif ?>">
            <tbody>
            <?php foreach ($card as $_label => $_value):?>
            <tr>
                <td><?php echo $this->escapeHtml($_label)?>:</td>
                <td><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></td>
            </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endforeach ?>
</div>
