<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Review_Block_Customer_Recent
 * @var Mage_Review_Block_Customer_Recent $this
 */
?>
<?php if($this->getCollection() && $this->count()): ?>
<div class="box-account box-reviews">
    <div class="box-head">
        <h2><?php echo $this->__('My Recent Reviews') ?></h2>
        <a href="<?php echo $this->getAllReviewsUrl() ?>"><?php echo $this->__('View All Reviews') ?></a>
    </div>
    <ol id="my_recent_reviews">
    <?php $iterator = 0 ?>
    <?php foreach ($this->getCollection() as $_review): ?>
        <li class="item">
            <span class="number"><?php echo ++$iterator ?></span>
            <div class="details">
                <h3 class="product-name"><a href="<?php echo $this->getReviewUrl($_review->getReviewId()) ?>"><?php echo $this->escapeHtml($_review->getName()) ?></a></h3>
                <?php if($_review->getSum()): ?>
                    <div class="ratings">
                        <strong><?php echo $this->__('Rating:') ?></strong>
                        <div class="rating-box">
                            <div class="rating" style="width:<?php echo ($_review->getSum() / $_review->getCount()) ?>%;"></div>
                        </div>
                    </div>
                <?php endif ?>
            </div>
        </li>
    <?php endforeach ?>
    </ol>
    <script type="text/javascript">decorateList('my_recent_reviews');</script>
</div>
<?php endif ?>
