<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */


/**
 * Downloadable product links
 *
 * @see Mage_Downloadable_Block_Catalog_Product_Samples
 * @var Mage_Downloadable_Block_Catalog_Product_Samples $this 
 */
?>

<?php if ($this->hasSamples()): ?>
    <dl class="item-options">
        <dt><?php echo $this->getSamplesTitle() ?></dt>
        <?php $_samples = $this->getSamples() ?>
        <?php foreach ($_samples as $_sample): ?>
            <dd>
                <a href="<?php echo $this->getSampleUrl($_sample) ?>" <?php echo $this->getIsOpenInNewWindow()?'onclick="this.target=\'_blank\'"':''; ?>><?php echo $this->escapeHtml($_sample->getTitle()); ?></a>
            </dd>
        <?php endforeach ?>
    </dl>
<?php endif ?>
