<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * Downloadable product type
 *
 * @see Mage_Downloadable_Block_Catalog_Product_View_Type
 * @var Mage_Downloadable_Block_Catalog_Product_View_Type $this
 */
?>
<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>
    <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
<?php echo $this->getPriceHtml($_product) ?>
<?php echo $this->getChildHtml('samples') ?>
