<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<script type="text/javascript">
//<![CDATA[
var CountryModel = function() {
    this.reload = false;
    this.bindSpecificCountryRelation();
};
CountryModel.prototype = {
    bindSpecificCountryRelation : function(parentId)
    {
        if(parentId) {
            var applyCountryElements = document.querySelectorAll('#'+parentId+' .shipping-applicable-country');
        } else {
            var applyCountryElements = document.querySelectorAll('.shipping-applicable-country');
        }
        for(var i=0;i<applyCountryElements.length; i++) {
            applyCountryElements[i].addEventListener('change', this.checkSpecificCountry.bind(this));
            this.initSpecificCountry(applyCountryElements[i]);
        }

    },
    initSpecificCountry : function(element){
        var applyCountryElement = element;
        if (applyCountryElement && applyCountryElement.id) {
            var specifCountryElement  = document.getElementById(applyCountryElement.id.replace(/sallowspecific/, 'specificcountry'));
            var showMethodElement  = document.getElementById(applyCountryElement.id.replace(/sallowspecific/, 'showmethod'));
            //var specifErrMsgElement  = document.getElementById(applyCountryElement.id.replace(/sallowspecific/, 'specificerrmsg'));
            if (specifCountryElement) {
                if (applyCountryElement.value == 1) {
                   //if specific country element selected
                   specifCountryElement.disabled = false;
                   if (showMethodElement) {
                       this.showElement(showMethodElement.parentNode);
                   }
                   //specifErrMsgElement.parentNode.style.display = '';
                 } else {
                   specifCountryElement.disabled = true;
                   if (showMethodElement) {
                       this.hideElement(showMethodElement.parentNode);
                   }
                   //specifErrMsgElement.parentNode.style.display = 'none';
                }
            }
        }
    },

    checkSpecificCountry : function(event)
    {
        var applyCountryElement = event.target;
        if (applyCountryElement && applyCountryElement.id) {
            var specifCountryElement  = document.getElementById(applyCountryElement.id.replace(/sallowspecific/, 'specificcountry'));
            var showMethodElement  = document.getElementById(applyCountryElement.id.replace(/sallowspecific/, 'showmethod'));
            //var specifErrMsgElement  = document.getElementById(applyCountryElement.id.replace(/sallowspecific/, 'specificerrmsg'));
            if (specifCountryElement) {
                if (applyCountryElement.value == 1) {
                   //if specific country element selected
                   specifCountryElement.disabled = false;
                   if (showMethodElement) {
                       this.showElement(showMethodElement.parentNode);
                   }
                   //specifErrMsgElement.parentNode.style.display = '';
                 } else {
                    this.unselectSpecificCountry(specifCountryElement);
                    specifCountryElement.disabled = true;
                    if (showMethodElement) {
                        this.hideElement(showMethodElement.parentNode);
                    }
                    //specifErrMsgElement.parentNode.style.display = 'none';
                }
            }
        }
    },

    unselectSpecificCountry : function(element)
    {
        for (var i=0; i<element.options.length; i++) {
            if (element.options[i].selected) {
              element.options[i].selected=false;;
            }
        }
    },

    showElement : function(elm)
    {
        if (elm) {
            if (!elm.querySelector('.shipping-skip-show')) {
                elm.style.display = '';
            }
        }
    },

    hideElement : function(elm)
    {
        if (elm) {
            if (!elm.querySelector('.shipping-skip-hide')) {
                elm.style.display = 'none';
            }
        }
    }

}
countryApply = new CountryModel();
//]]>
</script>
