<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="page-sitemap">
    <div class="page-title">
        <h1><?= $this->getTitle() ?></h1>
    </div>
    <div id="sitemap_top_links">
        <?= $this->getChildHtml('links') ?>
    </div>
    <?= $this->getChildHtml('pager_top') ?>
    <?= $this->getChildHtml('sitemap') ?>
    <?= $this->getChildHtml('links') ?>
    <?= $this->getChildHtml('pager_bottom') ?>
</div>
