<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */
?>
<?php /** @var Mage_Sales_Block_Recurring_Profile_View $this */?>
<?php if ($this->getIsAddress()):?>

<?php foreach ($this->getRenderedInfo() as $row):?>
<address><?php echo nl2br($this->escapeHtml($this->getObjectData($row, 'value')))?></address>
<?php endforeach ?>

<?php else: ?>

<table class="info-table">
    <tbody>
        <?php foreach ($this->getRenderedInfo() as $row):?>
        <?php $isAmount = $this->getObjectData($row, 'is_amount');?>
        <tr>
            <th><?php echo $this->escapeHtml($this->getObjectData($row, 'label'))?>:</th>
            <td><?php echo $this->renderRowValue($row) ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?php endif ?>
