<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php /** @var Mage_Sales_Block_Recurring_Profile_View $this */?>
<?php if ($this->getIsAddress()):?>

<?php foreach ($this->getRenderedInfo() as $row):?>
<address><?php echo nl2br($this->escapeHtml($this->getObjectData($row, 'value')))?></address>
<?php endforeach ?>

<?php else: ?>

<table class="info-table">
    <tbody>
        <?php foreach ($this->getRenderedInfo() as $row):?>
        <?php $isAmount = $this->getObjectData($row, 'is_amount');?>
        <tr>
            <th><?php echo $this->escapeHtml($this->getObjectData($row, 'label'))?>:</th>
            <td><?php echo $this->renderRowValue($row) ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<?php endif ?>
