<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @see Mage_Payment_Block_Info_Checkmo
 * @var Mage_Payment_Block_Info_Checkmo $this
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
<?php if($this->getInfo()->getAdditionalData()): ?>
    <?php if($this->getPayableTo()): ?><br /><?php echo Mage::helper('payment')->__('Make Check payable to: %s', $this->escapeHtml($this->getPayableTo())) ?><?php endif ?>
    <?php if($this->getMailingAddress()): ?>
        <label><?php echo Mage::helper('payment')->__('Send Check to:') ?></label>
        <div class="checkmo-mailing-address">
            <?php echo nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        </div>
    <?php endif ?>
<?php endif ?>
