<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2019-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Info
 * @var Mage_Payment_Block_Info $this 
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?php echo $this->escapeHtml($_label)?>:</td>
        <td><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></td>
    </tr>
<?php endforeach ?>
</table>
<?php endif ?>

<?php echo $this->getChildHtml()?>
