<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Info
 * @var Mage_Payment_Block_Info $this 
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($_specificInfo as $_label => $_value):?>
    <tr>
        <td><?php echo $this->escapeHtml($_label)?>:</td>
        <td><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></td>
    </tr>
<?php endforeach ?>
</table>
<?php endif ?>

<?php echo $this->getChildHtml()?>
