<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @var $this Mage_Uploader_Block_Multiple|Mage_Uploader_Block_Single
 */
?>
<div id="<?= $this->getHtmlId() ?>" class="uploader">
    <div class="buttons a-right">
        <?= $this->getBrowseButtonHtml() ?>
        <?= $this->getUploadButtonHtml() ?>
    </div>
</div>
<div class="no-display" id="<?= $this->getElementId('template') ?>">
    <div id="{{id}}-container" class="file-row">
        <span class="file-info">{{name}} {{size}}</span>
        <span class="delete-button"><?= $this->getDeleteButtonHtml() ?></span>
        <span class="progress-text"></span>
        <div class="clear"></div>
    </div>
</div>
<script type="text/javascript">
    (function() {
        var uploader = new Uploader(<?= $this->getJsonConfig() ?>);

        if (varienGlobalEvents) {
            varienGlobalEvents.attachEventHandler('tabChangeBefore', uploader.onContainerHideBefore);
        }
    })();
</script>
<?= $this->getChildHtml('additional_scripts') ?>
