<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if(!$this->getScriptIncluded() && $this->getCanDisplayContainer()): ?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/giftmessage.js') ?>"></script>
<?php $this->setScriptIncluded(true); ?>
<?php endif; ?>
<?php if($this->getCanDisplayContainer()): ?>
<div id="<?php echo $this->getId() ?>">
<?php endif; ?>
<?php switch ($this->getType()): ?>
<?php case 'item': ?>
    <button class="form-button-alt listen-for-click" type="button"><span>
        <?php if($this->hasGiftMessage()): ?>
        <?php echo $this->__('Edit') ?>
        <?php else: ?>
        <?php echo $this->__('Add') ?>
        <?php endif; ?>
    </span></button>
    <?php break; ?>
<?php case 'main': ?>
    <a href="#" class="listen-for-click">
        <?php if($this->hasGiftMessage()): ?>
        <?php echo $this->__('Edit Gift Message') ?>
        <?php else: ?>
        <?php echo $this->__('Add Gift Message') ?>
        <?php endif; ?>
    </a>
    <?php break; ?>
<?php case 'address': ?>
    <a href="#" class="listen-for-click">
        <?php if($this->hasGiftMessage()): ?>
        <?php echo $this->__('Edit Gift Message') ?>
        <?php else: ?>
        <?php echo $this->__('Add Gift Message') ?>
        <?php endif; ?>
    </a>
    <?php break; ?>
<?php case 'address_item': ?>
    <button class="form-button-alt listen-for-click" type="button"><span>
        <?php if($this->hasGiftMessage()): ?>
        <?php echo $this->__('Edit') ?>
        <?php else: ?>
        <?php echo $this->__('Add') ?>
        <?php endif; ?>
    </span></button>
    <?php break; ?>
<?php endswitch ?>
<?php if($this->getCanDisplayContainer()): ?>
</div>
<script type="text/javascript">
<!--
var <?php echo $this->getJsObjectName() ?> = new GiftMessage('<?php echo $this->getId() ?>');
<?php echo $this->getJsObjectName() ?>.url = '<?php echo $this->getEditUrl() ?>';
//-->
</script>
<?php endif; ?>