<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div id="answers_container">
<?php if( !$answers ): ?>
<?php else: ?>
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('poll')->__('Assigned Answers') ?></h4>
    </div>
    <?php foreach($answers->getItems() as $_item): ?>
        <fieldset id="poll_answer_fieldset_<?php echo $_item->getId() ?>">
        <table cellspacing="0" class="form-list" style="width:100%;">
            <tr>
                <td class="label"><?php echo Mage::helper('poll')->__('Answer Title:') ?> <span class="required">*</span></td>
                <td class="value"><input id="answer_<?php echo $_item->getId() ?>" name="answer[<?php echo $_item->getId() ?>][title]" value="<?php echo $_item->getAnswerTitle() ?>" class="required-entry input-text" type="text" /></td>
            </tr>
            <tr>
                <td class="label"><?php echo Mage::helper('poll')->__('Votes Count:') ?> <span class="required">*</span></td>
                <td class="value"><?php echo $this->getDeleteButtonHtml() ?>
                    <input id="answer_votes_<?php echo $_item->getId() ?>" name="answer[<?php echo $_item->getId() ?>][votes]" value="<?php echo $_item->getVotesCount() ?>" class="required-entry validate-not-negative-number input-text" type="text" />
                </td>
             </tr>
        </table>
        <input type="hidden" id="id_poll_answer_fieldset_<?php echo $_item->getId() ?>" value="<?php echo $_item->getId() ?>" />
        </fieldset>
    <?php endforeach; ?>
<?php endif; ?>
</div>
<?php echo $this->getAddButtonHtml(); ?>

<script type="text/javascript">
    var lastId = 0;
    var answer = function() {
        return {
            del : function(obj) {
                if( confirm('<?php echo Mage::helper('poll')->__('Are you sure you want to delete it?') ?>') ) {
                    fieldSet = obj.up('fieldset');
                    if( $('id_' + fieldSet.id) ) {
                        var itemId = $('id_' + fieldSet.id).value;
                        var newElement = document.createElement('input');
                        newElement.type = 'hidden';
                        newElement.value = itemId;
                        newElement.name = 'deleteAnswer[]';
                        $('answers_container').appendChild(newElement);
                    }
                    fieldSet.remove();
                }
            },

            add : function(obj) {
                var newElement = document.createElement('div');
                newElement.innerHTML = this.getTemplate();
                $('answers_container').appendChild(newElement);
            },

            getTemplate : function() {
                var id = this.createId();
                return  '<fieldset id="poll_answer_fieldset_' + id + '">'
                       +'<table cellspacing="0" class="form-list" style="width:100%;">'
                       +'<tr>'
                       +    '<td class="label"><?php echo Mage::helper('poll')->__('Answer Title:') ?> <span class="required">*</span></td>'
                       +    '<td><input id="answer_' + id + '" name="answer[' + id + '][title]" value="" class="required-entry input-text" type="text" /></td>'
                       +'</tr>'
                       +'<tr>'
                       +    '<td class="label"><?php echo Mage::helper('poll')->__('Votes Count:') ?> <span class="required">*</span></td>'
                       +    '<td><?php echo $this->getDeleteButtonHtml() ?><input id="answer_votes_' + id + '" name="answer[' + id + '][votes]" value="0" class="required-entry validate-not-negative-number input-text" type="text" /></td>'
                       +'</tr>'
                       +'</table>'
                       +'<input type="hidden" id="id_poll_answer_fieldset_' + id + '" value="' + id + '" />'
                       +'</fieldset>';
            },

            createId : function () {
                return --lastId;
            }
        }
    }();
</script>
