<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php 
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body <?php echo $this->getBodyClass()?'class="'.$this->getBodyClass().'"':'' ?>>
<div class="wrapper">
<?php /*<p class="demo-notice"><?php echo $this->__('This is a demo store. Any orders placed through this store will not be honored or fulfilled.') ?></p> */ ?>
        <!-- [start] header -->
        <div class="header">
            <?php echo $this->getChildHtml('header') ?>
        </div>
        <!-- [end] header -->

        <!-- [start] middle -->
            <div class="middle-container">
                <div class="middle col-2-right-layout">
        <!-- [start] center -->
                    <div id="main" class="col-main account-main">
                <!-- [start] global messages -->
                    <?php echo $this->getChildHtml('global_messages') ?>
                <!-- [end] global messages -->

                    <!-- [start] content -->
                            <?php echo $this->getChildHtml('content') ?>
                    <!-- [end] content -->

                    </div>
        <!-- [end] center -->

        <!-- [start] right -->
                    <div class="col-right side-col account-side">
                            <?php echo $this->getChildHtml('right') ?>
                    </div>
        <!-- [end] right -->

                </div>
            </div>
        <!-- [end] middle -->

        <!-- [start] footer -->
        <div class="footer-container">
                    <div class="footer">
            <?php echo $this->getChildHtml('footer') ?>
                        </div>
        </div>
        <!-- [end] footer -->

<?php echo $this->getChildHtml('before_body_end') ?>
</div>
</body>
</html>