<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
  <?php echo $this->getChildHtml('head') ?>
</head>
<body class="page-popup<?php echo !$this->getBodyClass()?' '.$this->getBodyClass():'' ?>">
<div>
  <div><img src="<?php echo $this->getPrintLogoUrl()?$this->getPrintLogoUrl():$this->getSkinUrl('images/logo_print.gif') ?>" alt="<?php echo $this->__('Magento Commerce Demo Store') ?>" /></div>
  <?php echo $this->getChildHtml('content') ?>
  <div class="clear"></div>
  <div class="button-set">
    <button onclick="window.close();" class="form-button"><span><?php echo $this->__('Close Window') ?></span></button>
  </div>
</div>
</body>
</html>