<?php

/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Open Software License (OSL 3.0)
 * @package    Mage_Shipping
 */

/**
 * @package    Mage_Shipping
 *
 * @method Mage_Sales_Model_Order_Shipment getOrderShipment()
 * @method float getPackageWeight()
 * @method string getRecipientAddressCity()
 * @method string getRecipientAddressCountryCode()
 * @method int getRecipientAddressPostalCode()
 * @method string getRecipientAddressStateOrProvinceCode()
 * @method string getRecipientAddressStreet()
 * @method string getRecipientAddressStreet1()
 * @method string getRecipientAddressStreet2()
 * @method string getRecipientContactCompanyName()
 * @method string getRecipientContactPersonFirstName()
 * @method string getRecipientContactPersonLastName()
 * @method string getRecipientContactPersonName()
 * @method int getRecipientContactPhoneNumber()
 * @method string getShipperAddressCity()
 * @method string getShipperAddressCountryCode()
 * @method int getShipperAddressPostalCode()
 * @method string getShipperAddressStateOrProvinceCode()
 * @method string getShipperAddressStreet()
 * @method string getShipperAddressStreet1()
 * @method string getShipperAddressStreet2()
 * @method string getShipperContactCompanyName()
 * @method string getShipperContactPersonFirstName()
 * @method string getShipperContactPersonLastName()
 * @method string getShipperContactPersonName()
 * @method int getShipperContactPhoneNumber()
 * @method string getShippingMethod()
 * @method $this setBaseCurrencyCode(string $value)
 * @method $this setOrderShipment(Mage_Sales_Model_Order_Shipment $orderShipment)
 * @method $this setPackages(int $value)
 * @method $this setPackageWeight(float $value)
 * @method $this setRecipientAddressCity(string $value)
 * @method $this setRecipientAddressCountryCode(string $value)
 * @method $this setRecipientAddressPostalCode(int $value)
 * @method $this setRecipientAddressRegionCode(string $value)
 * @method $this setRecipientAddressStateOrProvinceCode(string $value)
 * @method $this setRecipientAddressStreet(string $value)
 * @method $this setRecipientAddressStreet1(string $value)
 * @method $this setRecipientAddressStreet2(string $value)
 * @method $this setRecipientContactCompanyName(string $value)
 * @method $this setRecipientContactPersonFirstName(string $value)
 * @method $this setRecipientContactPersonLastName(string $value)
 * @method $this setRecipientContactPersonName(string $value)
 * @method $this setRecipientContactPhoneNumber(int $value)
 * @method $this setRecipientEmail(string $value)
 * @method $this setShipperAddressCity(string $value)
 * @method $this setShipperAddressCountryCode(string $value)
 * @method $this setShipperAddressPostalCode(int $value)
 * @method $this setShipperAddressStateOrProvinceCode(string $value)
 * @method $this setShipperAddressStreet(string $value)
 * @method $this setShipperAddressStreet1(string $value)
 * @method $this setShipperAddressStreet2(string $value)
 * @method $this setShipperContactCompanyName(string $value)
 * @method $this setShipperContactPersonFirstName(string $value)
 * @method $this setShipperContactPersonLastName(string $value)
 * @method $this setShipperContactPersonName(string $value)
 * @method $this setShipperContactPhoneNumber(int $value)
 * @method $this setShipperEmail(string $value)
 * @method $this setShippingMethod(string $value)
 * @method $this setStoreId(int $value)
 */
class Mage_Shipping_Model_Shipment_Request extends Varien_Object {}
