<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
/**
 * Calendar localization script. Should be put into page header.
 *
 * @see Mage_Core_Block_Html_Calendar
 */
?>

<script type="text/javascript">
//<![CDATA[
enUS = <?php echo $enUS?>; // en_US locale reference
Calendar._DN = <?= $days['wide'] ?>; // full day names
Calendar._SDN = <?= $days['abbreviated'] ?>; // short day names
Calendar._FD = <?= $firstDay ?>; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
Calendar._MN = <?= $months['wide'] ?>; // full month names
Calendar._SMN = <?= $months['abbreviated'] ?>; // short month names
Calendar._am = <?= $am ?>; // am/pm
Calendar._pm = <?= $pm ?>;

// tooltips
Calendar._TT = {};
Calendar._TT["INFO"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('About the calendar')) ?>";

Calendar._TT["ABOUT"] =
"<?= Mage::helper('core')->jsQuoteEscape($this->__('DHTML Date/Time Selector')) ?>\n" +
"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('For latest version visit: %s', 'http://www.dynarch.com/projects/calendar/')) ?>\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('Distributed under GNU LGPL. See %s for details.', 'http://gnu.org/licenses/lgpl.html')) ?>" +
"\n\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('Date selection:')) ?>\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('- Use the %s, %s buttons to select year', '\\xab', '\xbb')) ?>\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('- Use the %s, %s buttons to select month', '\u2039', '\u203a')) ?>\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('- Hold mouse button on any of the above buttons for faster selection.')) ?>";
Calendar._TT["ABOUT_TIME"] = "\n\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('Time selection:')) ?>\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('- Click on any of the time parts to increase it')) ?>\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('- or Shift-click to decrease it')) ?>\n" +
"<?= Mage::helper('core')->jsQuoteEscape($this->__('- or click and drag for faster selection.')) ?>";

Calendar._TT["PREV_YEAR"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Prev. year (hold for menu)')) ?>";
Calendar._TT["PREV_MONTH"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Prev. month (hold for menu)')) ?>";
Calendar._TT["GO_TODAY"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Go Today')) ?>";
Calendar._TT["NEXT_MONTH"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Next month (hold for menu)')) ?>";
Calendar._TT["NEXT_YEAR"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Next year (hold for menu)')) ?>";
Calendar._TT["SEL_DATE"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Select date')) ?>";
Calendar._TT["DRAG_TO_MOVE"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Drag to move')) ?>";
Calendar._TT["PART_TODAY"] = ' (' + <?= $today ?> + ')';

// the following is to inform that "%s" is to be the first day of week
Calendar._TT["DAY_FIRST"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Display %s first', '%s')) ?>";

// This may be locale-dependent. It specifies the week-end days, as an array
// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
// means Monday, etc.
Calendar._TT["WEEKEND"] = <?= $weekendDays ?>;

Calendar._TT["CLOSE"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Close')) ?>";
Calendar._TT["TODAY"] = <?= $today ?>;
Calendar._TT["TIME_PART"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('(Shift-)Click or drag to change value')) ?>";

// date formats
Calendar._TT["DEF_DATE_FORMAT"] = <?= $defaultFormat ?>;
Calendar._TT["TT_DATE_FORMAT"] = <?= $toolTipFormat ?>;

Calendar._TT["WK"] = <?= $week ?>;
Calendar._TT["TIME"] = "<?= Mage::helper('core')->jsQuoteEscape($this->__('Time:')) ?>";

CalendarDateObject._LOCAL_TIMZEONE_OFFSET_SECONDS = <?= $this->getTimezoneOffsetSeconds() ?>;
CalendarDateObject._SERVER_TIMZEONE_SECONDS = <?= $this->getStoreTimestamp() ?>;

//]]>
</script>
