<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     rwd_default
 */
?>
<?php
/**
 * @see Mage_Paypal_Block_Bml_Banners
 * @var Mage_Paypal_Block_Bml_Banners $this 
 */
?>
<div class="bml-ad large">
<script type="text/javascript" data-pp-pubid="<?php echo $this->escapeHtml($this->getPublisherId()) ?>" data-pp-placementtype="<?php echo $this->escapeHtml($this->getSize()) ?>"> (function (d, t) {
    "use strict";
    var s = d.getElementsByTagName(t)[0], n = d.createElement(t);
    n.src = "//paypal.adtag.where.com/merchant.js";
    s.parentNode.insertBefore(n, s);
}(document, "script"));
</script>
</div>
<div class="bml-ad small">
    <script type="text/javascript" data-pp-pubid="<?php echo $this->escapeHtml($this->getPublisherId()) ?>" data-pp-placementtype="300x50"> (function (d, t) {
            "use strict";
            var s = d.getElementsByTagName(t)[0], n = d.createElement(t);
            n.src = "//paypal.adtag.where.com/merchant.js";
            s.parentNode.insertBefore(n, s);
        }(document, "script"));
    </script>
</div>
