<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2018-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Downloadable_Block_Checkout_Cart_Item_Renderer
 * @var Mage_Downloadable_Block_Checkout_Cart_Item_Renderer $this
 */
?>
<h3 class="product-name"><a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a></h3>
<!-- item custom options -->
<?php if ($_options = $this->getOptionList()):?>
<dl class="item-options">
    <?php foreach ($_options as $_option) : ?>
    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif ?>><?php echo $_formatedOptionValue['value'] ?>
        <?php if (isset($_formatedOptionValue['full_view'])): ?>
        <div class="truncated_full_value">
            <dl class="item-options">
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
            </dl>
        </div>
        <?php endif ?>
    </dd>
    <?php endforeach ?>
</dl>
<?php endif ?>
<!-- / -->
    <!-- downloadable -->
    <?php if ($links = $this->getLinks()): ?>
    <dl class="item-options">
        <dt><?php echo $this->escapeHtml($this->getLinksTitle()); ?></dt>
        <?php foreach ($links as $link): ?>
            <dd><?php echo $this->escapeHtml($link->getTitle()); ?></dd>
        <?php endforeach ?>
    </dl>
    <?php endif ?>
    <!-- EOF downloadable -->
