<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="dashboard">
    <div class="page-title">
        <h1><?= $this->__('My Dashboard') ?></h1>
    </div>
    <?= $this->getMessagesBlock()->toHtml() ?>
    <?= $this->getChildHtml('hello') ?>
    <?= $this->getChildHtml('top') ?>
    <div class="box-account box-info">
        <div class="box-head">
            <h2><?= $this->__('Account Information') ?></h2>
        </div>
        <?php /* Extensions placeholder */ ?>
        <?= $this->getChildHtml('customer.account.dashboard.extra') ?>
        <?= $this->getChildHtml('info') ?>
    </div>
    <?= $this->getChildHtml('address') ?>
    <?= $this->getChildHtml('info1') ?>
    <?= $this->getChildHtml('info2') ?>
</div>
