<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/** @var Mage_Checkout_Block_Onepage_Progress $this */
?>
<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Payment Method') ?><span class="changelink"> <span class="separator">|</span> <a
        href="#payment"
        onclick="checkout.changeSection('opc-payment'); return false;"><?php echo $this->__('Change') ?></a></span>
</dt>
<dd class="complete">
    <?php echo $this->getPaymentHtml() ?>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Payment Method') ?>
</dt>
<?php endif ?>
