<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Checkout_Block_Onepage_Progress $this */
?>
<?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
<?php $completeClass = $this->getCheckout()->getStepData('shipping', 'complete') ? 'complete' : ''; ?>
<dt class="<?php echo $completeClass ?>">
    <?php echo $this->__('Shipping Address') ?> <span class="changelink"><span class="separator">|</span> <a
        href="#payment"
        onclick="checkout.changeSection('opc-shipping');return false;"><?php echo $this->__('Change') ?></a></span>
</dt>
<dd class="<?php echo $completeClass ?>">
    <?php if ($this->getCheckout()->getStepData('shipping', 'complete')): ?>
    <address><?php echo $this->getShipping()->format('html') ?></address>
    <?php endif ?>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Shipping Address') ?>
</dt>
<?php endif ?>
