<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_Centinel_Block_Authentication_Complete
 * @var Mage_Centinel_Block_Authentication_Complete $this
 */
?>
<?php if ($this->getIsProcessed()):?>
    <?php if ($this->getIsSuccess()):?>
        <script type="text/javascript">
            //<![CDATA[
                window.parent.CentinelAuthenticateController.success();
            //]]>
        </script>
    <?php else: ?>
        <h4><?php echo $this->__('Verification Failed');?></h4>
        <p><?php echo $this->__('The card has failed verification with the issuer bank.')?> <strong><?php echo $this->__('Order cannot be placed.')?></strong></p>
    <?php endif ?>
<?php else: ?>
    <h4><?php echo $this->__('Verification cannot be processed');?></h4>
    <p><?php echo $this->__('There has been wrong payment information submitted or the time limit has expired. Please, try again.')?> <strong><?php echo $this->__('Order cannot be placed.')?></strong></p>
<?php endif ?>
