<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Centinel_Block_Authentication_Complete
 * @var Mage_Centinel_Block_Authentication_Complete $this
 */
?>
<?php if ($this->getIsProcessed()):?>
    <?php if ($this->getIsSuccess()):?>
        <script type="text/javascript">
            //<![CDATA[
                window.parent.CentinelAuthenticateController.success();
            //]]>
        </script>
    <?php else: ?>
        <h4><?php echo $this->__('Verification Failed');?></h4>
        <p><?php echo $this->__('The card has failed verification with the issuer bank.')?> <strong><?php echo $this->__('Order cannot be placed.')?></strong></p>
    <?php endif ?>
<?php else: ?>
    <h4><?php echo $this->__('Verification cannot be processed');?></h4>
    <p><?php echo $this->__('There has been wrong payment information submitted or the time limit has expired. Please, try again.')?> <strong><?php echo $this->__('Order cannot be placed.')?></strong></p>
<?php endif ?>
