<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Centinel_Block_Authentication_Start
 * @var Mage_Centinel_Block_Authentication_Start $this
 */
?>
<form name="validation_form" id="validation_form" action="<?php echo $this->getAcsUrl();?>" method="post">
    <fieldset>
        <input type="hidden" name="PaReq" value="<?php echo $this->getPaReq()?>" />
        <input type="hidden" name="TermUrl" value="<?php echo $this->getTermUrl()?>" />
        <input type="hidden" name="MD" value="<?php echo $this->getMd()?>" />
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
window.onload = function(){
    document.getElementById('validation_form').submit();
};
//]]>
</script>
