<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php /** @var Mage_Core_Block_Template $this */ ?>
<script type="text/javascript">
//<![CDATA[
validateOptionsCallback = function (elmId, result){
    var container = document.getElementById(elmId).closest('ul.options-list');
    if (!container) {
        return;
    }
    if (result == 'failed') {
        container.classList.remove('validation-passed');
        container.classList.add('validation-failed');
    } else {
        container.classList.remove('validation-failed');
        container.classList.add('validation-passed');
    }
}

productConfigure.opConfig = {};

var DateOption = function() {};
DateOption.prototype = {

    getDaysInMonth: function(month, year)
    {
        var curDate = new Date();
        if (!month) {
            month = curDate.getMonth();
        }
        if (2 == month && !year) { // leap year assumption for unknown year
            return 29;
        }
        if (!year) {
            year = curDate.getFullYear();
        }
        return 32 - new Date(year, month - 1, 32).getDate();
    },

    reloadMonth: function(event)
    {
        var selectEl = event.findElement();
        var idParts = selectEl.id.split("_");
        if (idParts.length != 3) {
            return false;
        }
        var optionIdPrefix = idParts[0] + "_" + idParts[1];
        var month = parseInt(document.getElementById(optionIdPrefix + "_month").value);
        var year = parseInt(document.getElementById(optionIdPrefix + "_year").value);
        var dayEl = document.getElementById(optionIdPrefix + "_day");

        var days = this.getDaysInMonth(month, year);

        //remove days
        for (var i = dayEl.options.length - 1; i >= 0; i--) {
            if (dayEl.options[i].value > days) {
                dayEl.remove(dayEl.options[i].index);
            }
        }

        // add days
        var lastDay = parseInt(dayEl.options[dayEl.options.length-1].value);
        for (i = lastDay + 1; i <= days; i++) {
            this.addOption(dayEl, i, i);
        }
    },

    addOption: function(select, text, value)
    {
        var option = document.createElement('OPTION');
        option.value = value;
        option.text = text;

        if (select.options.add) {
            select.options.add(option);
        } else {
            select.appendChild(option);
        }
    }
};
productConfigure.opConfig.dateOption = new DateOption();
//]]>
</script>
