<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Button $this */
?>

<?php if($this->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="save_and_share" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Share Wishlist')) ?>" class="button btn-share"><span><span><?php echo $this->__('Share Wishlist') ?></span></span></button>
<?php endif ?>
