<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/** @var Mage_Wishlist_Block_Customer_Wishlist_Button $this */
?>

<?php if($this->getWishlist()->getItemsCount()): ?>
    <button type="submit" name="save_and_share" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Share Wishlist')) ?>" class="button btn-share"><span><span><?php echo $this->__('Share Wishlist') ?></span></span></button>
<?php endif ?>
