<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_System_Convert_Gui_Edit_Tab_Upload $this */
?>
<h4 class="icon-head head-edit-form fieldset-legend">Upload File</h4>
<div id="messages">
    <ul class="messages">
        <li class="notice-msg">
            <ul>
                <li><?php echo $this->__('Your server PHP settings allow you to upload files not more than %s at a time. Please modify post_max_size (currently is %s) and upload_max_filesize (currently is %s) values in php.ini if you want to upload larger files.', $this->getDataMaxSize(), $this->getPostMaxSize(), $this->getUploadMaxSize())?></li>
            </ul>
        </li>
        <li class="notice-msg">
            <ul>
                <li><?php echo $this->__('Make sure that data encoding in the file is consistent and saved in one of supported encodings (UTF-8 or ANSI).')?></li>
            </ul>
        </li>
    </ul>
</div>
<fieldset>
        <legend>Upload File</legend>
        <span class="field-row">
            <label for="file_1">File 1:</label>
            <input type="file" id="file_1" name="file_1" />
        </span>
        <span class="field-row">
            <label for="file_2">File 2:</label>
            <input type="file" id="file_2" name="file_2" />
        </span>
        <span class="field-row">
            <label for="file_2">File 3:</label>
            <input type="file" id="file_3" name="file_3" />
        </span>
</fieldset>
