<h4 class="icon-head head-edit-form fieldset-legend">Upload File</h4>
<fieldset>
        <legend>Upload File</legend>
        <span class="field-row">
            <label for="file_1">File 1:</label>
            <input type="file" id="file_1" name="file_1" />
        </span>
        <span class="field-row">
            <label for="file_2">File 2:</label>
            <input type="file" id="file_2" name="file_2" />
        </span>
        <span class="field-row">
            <label for="file_2">File 3:</label>
            <input type="file" id="file_3" name="file_3" />
        </span>
</fieldset>