<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->getHeader() ?></h3></td>
            <td class="form-buttons">
                <?php if($this->getTagId()): ?>
                    <?php echo $this->getDeleteButtonHtml() ?>
                <?php endif; ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="tag_edit_form">
    <?php echo $this->getChildHtml('tagForm'); ?>
</form>
<script type="text/javascript" language="javascript">
    var tagForm = new varienForm('tag_edit_form');

    function tagDelete(){
        if(confirm('<?php echo Mage::helper('tag')->__('Are you sure that you want to delete this tag?') ?>')){
            location.href = '<?php echo $this->getDeleteUrl() ?>'
        }
    }
</script>
