<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Tag_Pending $this */
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:80%;"><h3 class="<?php echo $this->getHeaderCssClass() ?>"><?php echo $this->getHeaderHtml(); ?></h3></td>
        <td class="form-buttons"><?php echo $this->getCreateButtonHtml(); ?></td>
    </tr>
</table>
</div>
<div id="tag_frame">
    <?php echo $this->getGridHtml() ?>
</div>
