<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_CatalogInventory_Block_Qtyincrements
 * @var Mage_CatalogInventory_Block_Qtyincrements $this 
 */
?>
<?php if ($this->getProductQtyIncrements()) : ?>
    <div class="product-pricing">
        <?php echo $this->__('%s is available for purchase in increments of %s', $this->getProductName(), $this->getProductQtyIncrements()) ?>
    </div>
<?php endif ?>
