<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_GiftMessage_Block_Message_Form
 * @var Mage_GiftMessage_Block_Message_Form $this
 */
?>
<?php echo $this->helper('core/js')->includeScript('mage/adminhtml/giftmessage.js') ?>
<?php if(!$this->getSaveMode()): ?>
<form action="<?php echo $this->getSaveUrl() ?>" id="message-form" method="post" class="a-left">
    <?php echo $this->getBlockHtml('formkey')?>
    <?php echo $this->getFormHtml(); ?>
    <?php echo $this->getSaveButtonHtml() ?>
    <?php echo $this->getCancelButtonHtml() ?>
    <?php if($this->getMessage()->getGiftMessageId()): ?>
    <?php echo $this->getRemoveButtonHtml() ?>
    <?php endif ?>
</form>
<?php elseif($this->getSaveMode() == 'save'): ?>
<h3><?php echo Mage::helper('giftmessage')->__('The gift message has been saved') ?></h3>
<br /><?php echo $this->getCloseButtonHtml() ?>
<?php else: ?>
<h3><?php echo Mage::helper('giftmessage')->__('The gift message has been removed') ?></h3>
<br /><?php echo $this->getCloseButtonHtml() ?>
<?php endif ?>
<script type="text/javascript">
<!--
<?php if(!$this->getSaveMode()): ?>
    var giftMessageWindowObject = new GiftMessageWindow('<?php echo $this->getUniqueId() ?>','message-form', '<?php echo $this->getRemoveUrl() ?>');
    giftMessageWindowObject.confirmMessage = '<?php echo $this->getEscapedForJs(Mage::helper('giftmessage')->__('Are you sure?')) ?>';
<?php else: ?>
    var giftMessageWindowObject = new GiftMessageWindow('<?php echo $this->getUniqueId() ?>', null, '<?php echo $this->getRemoveUrl() ?>');
    Event.observe(window, 'load', function(evt) {
        giftMessageWindowObject.updateParent('<?php echo $this->getEditUrl() ?>', '<?php echo $this->getButtonUrl() ?>');
    });
<?php endif ?>
//-->
</script>
