<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @see Mage_GiftMessage_Block_Message_Helper
 * @var Mage_GiftMessage_Block_Message_Helper $this
 */
?>
<?php if($this->getType()!== 'main' && !$this->getScriptIncluded() && $this->getCanDisplayContainer()): ?>
<?php echo $this->helper('core/js')->includeScript('mage/adminhtml/giftmessage.js') ?>
<?php $this->setScriptIncluded(true); ?>
<?php endif ?>
<?php if($this->getCanDisplayContainer()): ?>
<div id="<?php echo $this->getId() ?>">
<?php endif ?>
<?php switch ($this->getType()): ?>
<?php case 'item': ?>
    <a class="listen-for-click" href="#">
        <?php if($this->hasGiftMessage()): ?>
        <?php echo Mage::helper('giftmessage')->__('Edit') ?>
        <?php else: ?>
        <?php echo Mage::helper('giftmessage')->__('Add') ?>
        <?php endif ?>
    </a>
    <?php break ?>
<?php case 'order_item': ?>
    <a class="listen-for-click" href="#">
        <?php if($this->hasGiftMessage()): ?>
        <?php echo Mage::helper('giftmessage')->__('Edit') ?>
        <?php else: ?>
        <?php echo Mage::helper('giftmessage')->__('Add') ?>
        <?php endif ?>
    </a>
    <?php break ?>
<?php case 'main': ?>
        <?php if($this->hasGiftMessage()): ?>
            <?php if($_giftMessage=$this->getMessage()): ?>
            <span class="field-row">
                <label><?php echo Mage::helper('giftmessage')->__('From') ?></label>
                <?php echo $this->escapeHtml($_giftMessage->getSender()) ?>
            </span>
            <span class="field-row">
                <label><?php echo Mage::helper('giftmessage')->__('To') ?></label>
                <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?>
            </span>
            <span class="field-row">
                <label><?php echo Mage::helper('giftmessage')->__('Message') ?></label>
                 <div class="f-left"><?php echo $this->prepareAsIs($_giftMessage->getMessage()) ?></div>
            </span>
            <?php endif ?>
        <?php echo $this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Edit'), 'edit') ?>
        <?php else: ?>
        <?php echo $this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Add'), 'add') ?>
        <?php endif ?>
    <?php break ?>
<?php case 'order': ?>
        <?php if($this->hasGiftMessage()): ?>
            <?php if($_giftMessage=$this->getMessage()): ?>

            <span class="field-row">
                <label><?php echo Mage::helper('giftmessage')->__('From') ?></label>
                <?php echo $this->escapeHtml($_giftMessage->getSender()) ?>
            </span>
            <span class="field-row">
                <label><?php echo Mage::helper('giftmessage')->__('To') ?></label>
                <?php echo $this->escapeHtml($_giftMessage->getRecipient()) ?>
            </span>
            <span class="field-row">
                <label><?php echo Mage::helper('giftmessage')->__('Message') ?></label>
                <div class="f-left"><?php echo $this->prepareAsIs($_giftMessage->getMessage()) ?></div>
            </span>

            <?php endif ?>
        <?php echo $this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Edit'), 'edit') ?>
        <?php else: ?>
        <?php echo $this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Add'), 'add') ?>
        <?php endif ?>
    <?php break ?>
<?php endswitch ?>
<?php if($this->getCanDisplayContainer()): ?>
</div>
<script type="text/javascript">
var <?php echo $this->getJsObjectName() ?> = new GiftMessage('<?php echo $this->getId() ?>');
<?php echo $this->getJsObjectName() ?>.url = '<?php echo $this->getEditUrl() ?>';
</script>
<?php endif ?>
