<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if($this->getType()!== 'main' && !$this->getScriptIncluded() && $this->getCanDisplayContainer()): ?>
<?= $this->helper('core/js')->includeScript('mage/adminhtml/giftmessage.js') ?>
<?php $this->setScriptIncluded(true); ?>
<?php endif ?>
<?php if($this->getCanDisplayContainer()): ?>
<div id="<?= $this->getId() ?>">
<?php endif ?>
<?php switch ($this->getType()): ?>
<?php case 'item': ?>
    <a class="listen-for-click" href="#">
        <?php if($this->hasGiftMessage()): ?>
        <?= Mage::helper('giftmessage')->__('Edit') ?>
        <?php else: ?>
        <?= Mage::helper('giftmessage')->__('Add') ?>
        <?php endif ?>
    </a>
    <?php break ?>
<?php case 'order_item': ?>
    <a class="listen-for-click" href="#">
        <?php if($this->hasGiftMessage()): ?>
        <?= Mage::helper('giftmessage')->__('Edit') ?>
        <?php else: ?>
        <?= Mage::helper('giftmessage')->__('Add') ?>
        <?php endif ?>
    </a>
    <?php break ?>
<?php case 'main': ?>
        <?php if($this->hasGiftMessage()): ?>
            <?php if($_giftMessage=$this->getMessage()): ?>
            <span class="field-row">
                <label><?= Mage::helper('giftmessage')->__('From') ?></label>
                <?= $this->escapeHtml($_giftMessage->getSender()) ?>
            </span>
            <span class="field-row">
                <label><?= Mage::helper('giftmessage')->__('To') ?></label>
                <?= $this->escapeHtml($_giftMessage->getRecipient()) ?>
            </span>
            <span class="field-row">
                <label><?= Mage::helper('giftmessage')->__('Message') ?></label>
                 <div class="f-left"><?= $this->prepareAsIs($_giftMessage->getMessage()) ?></div>
            </span>
            <?php endif ?>
        <?= $this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Edit'), 'edit') ?>
        <?php else: ?>
        <?= $this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Add'), 'add') ?>
        <?php endif ?>
    <?php break ?>
<?php case 'order': ?>
        <?php if($this->hasGiftMessage()): ?>
            <?php if($_giftMessage=$this->getMessage()): ?>

            <span class="field-row">
                <label><?= Mage::helper('giftmessage')->__('From') ?></label>
                <?= $this->escapeHtml($_giftMessage->getSender()) ?>
            </span>
            <span class="field-row">
                <label><?= Mage::helper('giftmessage')->__('To') ?></label>
                <?= $this->escapeHtml($_giftMessage->getRecipient()) ?>
            </span>
            <span class="field-row">
                <label><?= Mage::helper('giftmessage')->__('Message') ?></label>
                <div class="f-left"><?= $this->prepareAsIs($_giftMessage->getMessage()) ?></div>
            </span>

            <?php endif ?>
        <?= $this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Edit'), 'edit') ?>
        <?php else: ?>
        <?= $this->getWidgetButtonHtml(Mage::helper('giftmessage')->__('Add'), 'add') ?>
        <?php endif ?>
    <?php break ?>
<?php endswitch ?>
<?php if($this->getCanDisplayContainer()): ?>
</div>
<script type="text/javascript">
var <?= $this->getJsObjectName() ?> = new GiftMessage('<?= $this->getId() ?>');
<?= $this->getJsObjectName() ?>.url = '<?= $this->getEditUrl() ?>';
</script>
<?php endif ?>
