<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_ConfigurableSwatches_Block_Catalog_Layer_State_Swatch
 * @var Mage_ConfigurableSwatches_Block_Catalog_Layer_State_Swatch $this
 */
?>
<?php
$_filter = $this->getFilter();
$_label = $this->stripTags($_filter->getLabel());

$_swatchInnerWidth = $this->getSwatchInnerWidth();
$_swatchInnerHeight = $this->getSwatchInnerHeight();
$_swatchOuterWidth = $this->getSwatchOuterWidth();
$_swatchOuterHeight = $this->getSwatchOuterHeight();

$_lineHeight = $_swatchOuterHeight + 2;

$_swatchUrl = $this->getSwatchUrl();
?>

<li class="swatch-current">
    <?php
    $clearLinkUrl = $_filter->getClearLinkUrl();
    if ($clearLinkUrl): ?>
        <a  class="btn-previous" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Previous')) ?>"><?php echo $this->__('Previous') ?></a>
        <a  class="btn-remove" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>" href="<?php echo $clearLinkUrl ?>"><?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></a>
    <?php else: ?>
        <a  class="btn-remove" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove This Item')) ?>"><?php echo $this->__('Remove This Item') ?></a>
    <?php endif ?>
    <span class="label" style="line-height: <?php echo $_lineHeight; ?>px;"><?php echo $this->__($_filter->getName()) ?>:</span>
    <span class="value" style="line-height: <?php echo $_lineHeight; ?>px;">
        <span class="swatch-link" style="height:<?php echo $_swatchOuterHeight ?>px; width:<?php echo $_swatchOuterWidth ?>px;">
            <span class="swatch-label" style="height:<?php echo $_swatchInnerHeight ?>px; width:<?php echo $_swatchInnerWidth ?>px; line-height:<?php echo $_swatchInnerHeight ?>px;">
                <img src="<?php echo $_swatchUrl; ?>" alt="<?php echo $_label; ?>" title="<?php echo $_label ?>" width="<?php echo $_swatchInnerWidth ?>" height="<?php echo $_swatchInnerHeight ?>" />
            </span>
        </span>
    </span>
</li>
