<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php $_item = $this->getItem() ?>
<tr>
    <td align="left" valign="top" style="font-size:11px; padding:3px 9px;">
        <strong><?= $this->escapeHtml($_item->getName()) ?></strong>
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?= $option['label'] ?></em></strong></dt>
            <dd style="margin:0; padding:0 0 0 9px;"><?= nl2br($option['value']) ?></dd>
            <?php endforeach ?>
        </dl>
        <?php endif ?>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif ?>
        <?= $this->escapeHtml($_item->getDescription()) ?>
    </td>
    <td align="left" valign="top" style="font-size:11px; padding:3px 9px;"><?= $this->escapeHtml($this->getSku($_item)) ?></td>
    <td align="center" valign="top" style="font-size:11px; padding:3px 9px;"><?= $_item->getQty()*1 ?></td>
</tr>
