<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Checkout_Block_Cart_Totals
 */
?>
<?php if ($this->getTotals()): ?>
<tfoot>
    <?php $_colspan = $this->helper('tax')->displayCartBothPrices() ? 5 : 3; ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()):?>
    <tr>
        <td class="a-right" colspan="<?php echo $_colspan; ?>">
            <small><?php echo $this->helper('sales')->__('Grand Total to be Charged') ?></small>
        </td>
        <td class="a-right">
            <small><?php echo $this->displayBaseGrandtotal() ?></small>
        </td>
    </tr>
    <?php endif ?>
</tfoot>
<?php endif ?>
