<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Options $this */
?>
<div class="entry-edit custom-options product-custom-options">
    <div id="dynamic-price-warrning" style="display:none">
        <ul class="messages">
            <li class="error-msg">
                <ul>
                    <li><?php echo $this->__('Bundle with dynamic pricing cannot include custom defined options. Options will not be saved.') ?></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('catalog')->__('Custom Options') ?></h4>
        <div class="right"><?php echo $this->getAddButtonHtml() ?></div>
    </div>

    <div id="product_options_container" class="box">
        <div id="product_options_container_top"></div>
        <?php echo $this->getOptionsBoxHtml() ?>
    </div>
</div>

<script type="text/javascript">
// re-bind form elements onchange
varienWindowOnload(true);
//show error message
if ($('price_type')) {
    if ($('price_type').value == '0' && $('dynamic-price-warrning')) {
        $('dynamic-price-warrning').show();
    }
}
</script>
