<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Order_View_Tab_History $this */
?>
<div class="entry-edit">
    <fieldset>
        <ul class="note-list">
        <?php foreach ($this->getFullHistory() as $_item): ?>
            <li>
                <strong><?php echo $this->getItemCreatedAt($_item) ?></strong>
                <?php echo $this->getItemCreatedAt($_item, 'time') ?><span class="separator">|</span>
                <?php if ($this->getItemTitle($_item)): ?>
                <strong><?php echo $this->getItemTitle($_item) ?></strong>
                <span class="separator">|</span>
                <?php endif ?>
                <small>
                    <?php echo $this->helper('sales')->__('Customer') ?>
                    <strong class="subdue">
                    <?php if ($this->isCustomerNotificationNotApplicable($_item)): ?>
                        <?php echo $this->helper('sales')->__('Notification Not Applicable') ?>
                    <?php elseif ($this->isItemNotified($_item)): ?>
                        <?php echo $this->helper('sales')->__('Notified') ?>
                        <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16px" height="16px" alt="" />
                    <?php else: ?>
                        <?php echo $this->helper('sales')->__('Not Notified') ?>
                    <?php endif ?>
                    </strong>
                </small>
                <?php if ($_comment = $this->getItemComment($_item)): ?>
                    <br/><?php echo $_comment ?>
                <?php endif ?>
            </li>
        <?php endforeach ?>
        </ul>
    </fieldset>
</div>
