<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<table cellspacing="0">
<tr>
<td><label for="coupons:code"><?php echo Mage::helper('sales')->__('Apply Coupon Code') ?></label>
<input type="text" class="input-text" id="coupons:code" value="" name="coupon_code" style="width:100px"/></td>
<td>&nbsp;<?php echo $this->getButtonHtml(Mage::helper('sales')->__('Apply'), 'order.applyCoupon($F(\'coupons:code\'))') ?></td>
</tr>
</table>
<?php if($this->getCouponCode()): ?>
    <br/>
    <strong><?php echo $this->getCouponCode() ?></strong>
    [<a href="#" onclick="order.applyCoupon('');return false;" title="<?php echo Mage::helper('sales')->__('Remove Coupon Code') ?>"><?php echo Mage::helper('sales')->__('Remove') ?></a>]
<?php endif; ?>