<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */
/**
 * @var Mage_Checkout_Block_Onepage_Shipping_Method_Additional $this
 */
?>
<?php if (!$this->getQuote()->isVirtual() && $this->helper('core')->isModuleOutputEnabled('Mage_GiftMessage')): ?>
    <?php echo $this->helper('giftmessage/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
<?php endif ?>
