<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Bundle_Block_Catalog_Product_View_Type_Bundle
 * @var Mage_Bundle_Block_Catalog_Product_View_Type_Bundle $this
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()); ?>
<?php if ($_product->isSaleable()):?>
    <?php if (count($_options)): ?>
        <dl>
        <?php foreach ($_options as $_option): ?>
            <?php if (!$_option->getSelections()): ?>
                <?php continue; ?>
            <?php endif ?>
            <?php echo $this->getOptionHtml($_option) ?>
        <?php endforeach ?>
        </dl>
    <?php else: ?>
        <p><?php echo $this->__('No options of this product are available.') ?></p>
    <?php endif ?>
<?php endif ?>
