<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Cache_Additional $this */
?>
<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('adminhtml')->__('Additional Cache Management') ?></h3></td>
            <td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanImagesUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush Catalog Images Cache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Pregenerated product images files.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanSwatchesUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush Swatch Images Cache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Pregenerated configurable swatches image files.')?>
        </td>
    </tr>
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanMediaUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush JavaScript/CSS Cache') ?></span></span></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('Themes JavaScript and CSS files combined to one file.')?>
        </td>
    </tr>
</table>
<?php echo $this->getChildHtml(); ?>
