<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Cache_Notifications $this */
?>
<?php $_processes = $this->getCacheTypesForRefresh()?>
<?php if($_processes):?>
<div class="notification-global">
    <strong><?php echo $this->helper('adminhtml')->__('One or more of the Cache Types are invalidated:') ?></strong>
    <?php echo implode(', ', $_processes)?>.
    <?php echo $this->helper('index')->__('Click here to go to <a href="%s">Cache Management</a> and refresh cache types.', $this->getManageUrl());?>
</div>
<?php endif ?>
