<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php
/**
 * @see Mage_Catalog_Block_Product_View
 * @var Mage_Catalog_Block_Product_View $this
 */
$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();
?>
<?php if (count($_tierPrices) > 0): ?>
    <ul class="tier-prices product-pricing">
    <?php foreach($_tierPrices as $_price): ?>
        <li><?php echo $this->__('Buy %1$s with %2$s discount each', $_price['price_qty'], '<strong class="benefit">'.($_price['price']*1).'%</strong>') ?></li>
    <?php endforeach ?>
    </ul>
<?php endif ?>
