<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Downloadable_Block_Adminhtml_Sales_Items_Column_Downloadable_Name $this */
?>

<?php if ($_item = $this->getItem()): ?>
    <h5 class="title"><?php echo $_item->getName() ?></h5>
    <div><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->escapeHtml($this->getSku()))); ?></div>
    <?php if ($this->getOrderOptions()): ?>
        <dl class="item-options">
        <?php foreach ($this->getOrderOptions() as $_option): ?>
            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
            <dd>
            <?php if (isset($_option['custom_view']) && $_option['custom_view']): ?>
                <?php echo $_option['value'];?>
            <?php else: ?>
                <?php echo Mage::helper('core/string')->truncate($_option['value'], 55, '', $_remainder);?>
                <?php if ($_remainder):?>
                    ... <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_remainder ?></span>
                    <script type="text/javascript">
                    $('<?php echo $_id ?>').hide();
                    $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
                    $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});
                    </script>
                <?php endif ?>
            <?php endif ?>
            </dd>
        <?php endforeach ?>
        </dl>
    <?php endif ?>
    <?php if ($this->getLinks()): ?>
        <dl class="item-options">
            <dt><?php echo $this->escapeHtml($this->getLinksTitle()); ?></dt>
            <?php foreach ($this->getLinks()->getPurchasedItems() as $_link): ?>
                <dd><?php echo $this->escapeHtml($_link->getLinkTitle()); ?></dd>
            <?php endforeach ?>
        </dl>
    <?php endif ?>
    <?php echo $this->escapeHtml($_item->getDescription()) ?>
<?php endif ?>
