<!--
<tr>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php echo $this->getTotal()->getTitle() ?>
    </td>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
        <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
    </td>
</tr>
-->
<?php global $taxIter; $taxIter++; ?>
<?php if ($this->helper('tax')->displayFullSummary()): ?>
<?php $isTop = 1; ?>
            <?php foreach ($this->getTotal()->getFullInfo() as $info): ?>
                <?php $percent = $info['percent']; ?>
                <?php $amount = $info['amount']; ?>
                <?php $rates = $info['rates']; ?>
                <?php $isFirst = 1; ?>

                <?php foreach ($rates as $rate): ?>
                <tr class="tax-details-<?php echo $taxIter; ?> tax-details<?php if ($isTop): echo ' tax-details-first'; endif; ?>" style="display:none;">
                    <td class="a-right" style="<?php echo $this->getTotal()->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
                        <?php echo $rate['title']; ?> - <?php echo $rate['percent']; ?>%<br />
                    </td>
                    <?php if ($isFirst): ?>
                        <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right" rowspan="<?php echo count($rates); ?>">
                            <?php echo $this->helper('checkout')->formatPrice($amount); ?>
                        </td>
                    <?php endif; ?>
                </tr>
                <?php $isFirst = 0; ?>
                <?php $isTop = 0; ?>
                <?php endforeach; ?>
            <?php endforeach; ?>
<?php endif;?>
<tr<?php if ($this->helper('tax')->displayFullSummary()): ?> class="tax-total" onclick="expandDetails(this, '.tax-details-<?php echo $taxIter;?>')"<?php endif; ?>>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <div class="tax-collapse"><?php echo $this->getTotal()->getTitle() ?></div>
        <?php else: ?>
            <?php echo $this->getTotal()->getTitle() ?>
        <?php endif;?>
    </td>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right"><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></td>
</tr>