<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php
/**
 * @var Mage_Usa_Block_Adminhtml_Dhl_Unitofmeasure $this
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function changeDimensions()
    {
        var dimensionUnit = '(<?php echo $this->getInch(); ?>)';
        var dhlintUnitOfMeasureNote = '<?php echo $this->getDivideOrderWeightNoteLbp(); ?>';
        if (document.getElementById("carriers_dhlint_unit_of_measure").value == "K") {
            dimensionUnit = '(<?php echo $this->getCm(); ?>)';
            dhlintUnitOfMeasureNote = '<?php echo $this->getDivideOrderWeightNoteKg(); ?>';
        }
        document.querySelector('[for="carriers_dhlint_height"]').innerHTML = '<?php echo $this->getHeight(); ?> ' + dimensionUnit;
        document.querySelector('[for="carriers_dhlint_depth"]').innerHTML = '<?php echo $this->getDepth(); ?> ' + dimensionUnit;
        document.querySelector('[for="carriers_dhlint_width"]').innerHTML = '<?php echo $this->getWidth(); ?> ' + dimensionUnit;

        var divideEl = document.getElementById('carriers_dhlint_divide_order_weight');
        divideEl.nextElementSibling.querySelector('*').innerHTML = dhlintUnitOfMeasureNote;
    }
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("carriers_dhlint_unit_of_measure").addEventListener("change", changeDimensions);
        changeDimensions();
    });
    //]]>
</script>
