<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @var Mage_Paypal_Block_Adminhtml_System_Config_Payflowlink_Advanced $this
 */
?>
<div class="payflow-settings-notice">
    <strong class="important-label"><?php echo $this->__('Important: ') ?></strong>
    <?php echo $this->__('To use PayPal Payments Advanced, you must configure  your PayPal Payments Advanced account on the PayPal website.'); ?>
    <?php echo $this->__('Once you log into your PayPal Advanced account, navigate to the Service Settings - Hosted Checkout Pages - Set Up menu and set the options described below') ?>
    <ul class="options-list">
        <li><strong>AVS:</strong> No</li>
        <li><strong>CSC:</strong> No</li>
        <li><strong>Enable Secure Token:</strong> Yes</li>
    </ul>
</div>
