<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     rwd_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if($this->getItemCount()): ?>
<?php $_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])); ?>
<div class="crosssell">
    <h2><?= $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    <ul id="crosssell-products-list" class="products-grid products-grid--max-3-col">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
            <div class="product-info">
                <a class="product-image" href="<?= $_item->getProductUrl() ?>" title="<?= $this->escapeHtml($_item->getName()) ?>">
                    <img src="<?= $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(210) ?>" alt="<?= $this->escapeHtml($_item->getName()) ?>" />
                </a>
                <h3 class="product-name"><a href="<?= $_item->getProductUrl() ?>"><?= $this->escapeHtml($_item->getName()) ?></a></h3>
                <?= $this->getPriceHtml($_item, true) ?>
                <div class="actions">
                    <button type="button"
                            title="<?= Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                            class="button btn-cart"
                            onclick="customFormSubmit(
                                    '<?= $this->getAddToCartUrlCustom($_item, [], false) ?>',
                                    '<?= $_params ?>',
                                    'post')">
                        <span><span><?= $this->__('Add to Cart') ?></span></span>
                    </button>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <?php $_wishlistUrl = $this->getAddToWishlistUrlCustom($_item, false); ?>
                            <li>
                                <a href="#"
                                   data-url="<?= $_wishlistUrl ?>"
                                   data-params="<?= $_params ?>"
                                   class="link-wishlist"
                                   onclick="customFormSubmit('<?= $_wishlistUrl ?>', '<?= $_params ?>', 'post')">
                                    <?= $this->__('Add to Wishlist') ?>
                                </a>
                            </li>
                        <?php endif ?>
                        <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_item, false)) : ?>
                            <li>
                                <span class="separator">|</span>
                                <a href="#"
                                   class="link-compare"
                                   onclick="customFormSubmit('<?= $_compareUrl ?>', '<?= $_params ?>', 'post')">
                                    <?= $this->__('Add to Compare') ?>
                                </a>
                            </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach ?>
    </ul>
    <?php // <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script> ?>
</div>
<?php endif ?>
