<?php
/**
 * OpenMage
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @deprecated  after 1.4.0.0-alpha3
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<?php if($orders->getSize()): ?>
<table class="data-table" id="my-orders-table" >
    <thead>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <!--<th class="a-center">Shipped To</th>-->
            <th><?php echo $this->__('Total') ?></th>
            <th><?php echo $this->__('Status') ?></th>
            <th><?php echo $this->__('Details') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($orders as $order): ?>
        <tr>
            <td><?php echo $order->getRealOrderId() ?>&nbsp;</td>
            <td><?php echo date("D, j M, Y", strtotime($order->getCreatedAt())) ?>&nbsp;</td>
            <!--<td class="a-center">{$page.orders[io].customer}</td>-->
            <td><?php echo $order->getGrandTotal() ?>&nbsp;</td>
            <td><?php echo $order->getStatus() ?>&nbsp;</td>
            <td><a href="<?php echo $this->getUrl('customer/order/view', ['order'=>$order->getOrderId()]) ?>"><?php echo $this->__('View Order') ?></a>&nbsp;</td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders yet.') ?></p>
<?php endif ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
