<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php 
/**
 * Category layered navigation
 * 
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
    <div class="box layered-nav">
        <div class="head">
            <h3><?php echo $this->__('Shop by') ?></h3>
        </div>

        <div class="border-creator">
        <?php echo $this->getStateHtml() ?>
        <?php if($this->canShowOptions()): ?>
            <div class="narrow-by">
                <h4><?php echo $this->__('Shopping Options') ?></h4>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount()): ?>
                <dt><?php echo $_filter->getName() ?></dt>
                <dd>
                <?php echo $_filter->getHtml() ?>
                </dd>
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
            </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
<!-- [ends] .browse-by // -->
