<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_Payment_Block_Form_Banktransfer
 * @var Mage_Payment_Block_Form_Banktransfer $this
 */
?>
<?php if ($instructions = $this->getInstructions()): ?>
    <ul class="form-list checkout-agreements" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content">
                <?php echo nl2br($instructions) ?>
            </div>
        </li>
    </ul>
<?php endif ?>
