<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Payment_Block_Form_Cashondelivery
 * @var Mage_Payment_Block_Form_Cashondelivery $this
 */
?>
<?php if ($this->getInstructions()): ?>
    <ul class="form-list checkout-agreements" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li>
            <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content">
                <?php echo nl2br($this->getInstructions()) ?>
            </div>
        </li>
    </ul>
<?php endif ?>
