<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Payment_Block_Form_Checkmo
 * @var Mage_Payment_Block_Form_Checkmo $this
 */
?>
<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()): ?>
    <ul class="form-list checkmo-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <?php if ($this->getMethod()->getPayableTo()): ?>
        <li>
            <label><?php echo $this->__('Make Check payable to:') ?></label>
            <?php echo $this->escapeHtml($this->getMethod()->getPayableTo()) ?>
        </li>
        <?php endif ?>
        <?php if ($this->getMethod()->getMailingAddress()): ?>
        <li>
            <label><?php echo Mage::helper('payment')->__('Send Check to:') ?></label>
            <address class="checkmo-mailing-address">
                <?php echo nl2br($this->escapeHtml($this->getMethod()->getMailingAddress())) ?>
            </address>
        </li>
        <?php endif ?>
    </ul>
<?php endif ?>
