<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Payment_Block_Form_Purchaseorder
 * @var Mage_Payment_Block_Form_Purchaseorder $this
 */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <label for="po_number" class="required"><em>*</em><?php echo $this->__('Purchase Order Number') ?></label>
        <div class="input-box">
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Purchase Order Number')) ?>" class="input-text required-entry" value="<?php echo $this->escapeHtml($this->getInfoData('po_number')) ?>" />
        </div>
    </li>
</ul>
