<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2018 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2020-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <title><?= Mage::helper('adminhtml')->__('Log into OpenMage Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?= $this->getSkinUrl('login.css') ?>" media="all" />
    <link rel="icon" href="<?= $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?= $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
    <script type="text/javascript" src="<?= $this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->getJsUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->getJsUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
    <script type="text/javascript" src="<?= $this->getJsUrl('mage/captcha.js') ?>"></script>
</head>
<body id="page-login">
    <div class="login-container">
        <div class="login-box">
            <form method="post" action="<?= $this->getUrl('adminhtml') ?>" id="loginForm">
                <div class="login-form">
                    <input name="form_key" type="hidden" value="<?= $this->getFormKey() ?>" />
                    <h2><?= Mage::helper('adminhtml')->__('Log in to Admin Panel') ?></h2>
                    <div id="messages">
                        <?= $this->getMessagesBlock()->toHtml() ?>
                    </div>
                    <div class="input-box input-left">
                        <label for="username"><?= Mage::helper('adminhtml')->__('User Name:') ?></label><br />
                        <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" autofocus="autofocus" />
                    </div>
                    <div class="input-box input-right">
                        <label for="login"><?= Mage::helper('adminhtml')->__('Password:') ?></label><br />
                        <input type="password" id="login" name="login[password]" value="" class="required-entry input-text" />
                    </div>
                    <?= $this->getChildHtml('form.additional.info') ?>
                    <div class="clear"></div>
                    <div class="form-buttons">
                        <a class="left" href="<?= Mage::helper('adminhtml')->getUrl('adminhtml/index/forgotpassword', ['_nosecret' => true]) ?>"><?= Mage::helper('adminhtml')->__('Forgot your password?') ?></a>
                        <input type="submit" class="form-button" value="<?= Mage::helper('core')->quoteEscape(Mage::helper('adminhtml')->__('Login')) ?>" title="<?= Mage::helper('core')->quoteEscape(Mage::helper('adminhtml')->__('Login')) ?>" />
                    </div>
                </div>
                <p class="legal"><?= Mage::helper('adminhtml')->__('Powered by OpenMage') ?></p>
            </form>
            <div class="bottom"></div>
            <script type="text/javascript">
                var loginForm = new varienForm('loginForm');
            </script>
        </div>
    </div>
</body>
</html>
