<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
USAGE:

Simple:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->toHtml() ?>

For checkout/onepage/billing.phtml:

<?php echo $this->getLayout()->createBlock('customer/widget_dob')
   ->setDate($this->getCustomer()->getDob())
   ->setFieldIdFormat('billing:%s')
   ->setFieldNameFormat('billing[%s]')
   ->toHtml() ?>

NOTE: Regarding styles - if we leave it this way, we'll move it to boxes.css
      Alternatively we could calculate widths automatically using block input parameters.
*/
?>

<style type="text/css">
.customer-dob .input-box { width:60px !important; }
.customer-dob input { width:50px !important; }
.customer-dob small { color:#888; font-size:10px; }
</style>

<div class="customer-dob">

    <label for="<?php echo $this->getFieldId('day')?>">
        <?php echo $this->__('Date of Birth') ?>
        <?php if ($this->isRequired()):?><span class="required">*</span><?php endif ?>
    </label>
    <div class="clear"></div>

    <div class="input-box dob-day">
        <input type="text"
            id="<?php echo $this->getFieldId('day')?>"
            name="<?php echo $this->getFieldName('day')?>"
            value="<?php echo $this->getDay() ?>"
            title="<?php echo $this->__('Day') ?>"
            class="input-text validate-custom"
            <?php echo $this->getFieldParams() ?> />
        <br />
        <small><?php echo $this->__('DD') ?></small>
    </div>

    <div class="input-box dob-month">
        <input type="text"
            id="<?php echo $this->getFieldId('month')?>"
            name="<?php echo $this->getFieldName('month')?>"
            value="<?php echo $this->getMonth() ?>"
            title="<?php echo $this->__('Month') ?>"
            class="input-text validate-custom"
            <?php echo $this->getFieldParams() ?> />
        <br />
        <small><?php echo $this->__('MM') ?></small>
    </div>

    <div class="input-box dob-year">
        <input type="text"
            id="<?php echo $this->getFieldId('year')?>"
            name="<?php echo $this->getFieldName('year')?>"
            value="<?php echo $this->getYear() ?>"
            title="<?php echo $this->__('Year') ?>"
            class="input-text validate-custom"
            <?php echo $this->getFieldParams() ?> />
        <br />
        <small><?php echo $this->__('YYYY') ?></small>
    </div>

    <div class="dob-full" style="display:none;">
        <input type="hidden"
            id="<?php echo $this->getFieldId('dob')?>"
            name="<?php echo $this->getFieldName('dob')?>" />
    </div>

    <div style="opacity: 0.999999; display:none;" class="validation-advice"></div>
</div>

<script type="text/javascript">
var customer_dob = new Varien.DOB('.customer-dob', <?php echo $this->isRequired() ? 'true' : 'false' ?>);
</script>