<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if($this->isContentMode()): ?>
    <div class="category-head">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed right"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h2><?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?></h2>
    </div>
    <?php if($_imageUrl=$this->getCurrentCategory()->getImageUrl()): ?>
        <p><img src="<?php echo $_imageUrl ?>" alt="<?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?>" width="475" /></p>
    <?php endif; ?>
    <?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
        <p class="category-description"><?php echo $_description ?></p>
    <?php endif; ?>
    <?php echo $this->getCmsBlockHtml() ?>
<?php elseif($this->isMixedMode()): ?>
    <div class="category-head">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed right"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h2><?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?></h2>
    </div>
    <?php if($_imageUrl=$this->getCurrentCategory()->getImageUrl()): ?>
        <p><img src="<?php echo $_imageUrl ?>" alt="<?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?>" width="475" /></p>
    <?php endif; ?>
    <?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
        <p class="category-description"><?php echo $_description ?></p>
    <?php endif; ?>
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <div class="category-head">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-feed right"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h2><?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?></h2>
    </div>
    <?php if($_imageUrl=$this->getCurrentCategory()->getImageUrl()): ?>
        <p><img src="<?php echo $_imageUrl ?>" alt="<?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?>" width="475" /></p>
    <?php endif; ?>
    <?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
        <p class="category-description"><?php echo $_description ?></p>
    <?php endif; ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>