<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
/** @var Mage_Paypal_Block_Payflow_Link_Iframe $this */
?>
<div id="iframe-warning" class="warning-message">
    <?php echo $this->__('Please do not refresh the page until you complete payment.') ?>
</div>
<iframe id="payflow-link-iframe" style="display:none;" scrolling="no" frameborder="0" border="0"
        src="<?php echo $this->getFrameActionUrl() ?>" height="610" width="100%"></iframe>
<script type="text/javascript">
//<![CDATA[
var headers = $$('#' + checkout.accordion.container.readAttribute('id') + ' .section');
headers.each(function(header) {
    header.removeClassName('allow');
});
$('payflow-link-iframe').observe('load', function(){
    $('payflow-link-iframe').show();
    $('iframe-warning').show();
    checkout.loadWaiting = 'review';
    checkout.setLoadWaiting(false);
    if (checkout.accordion.currentSection == 'opc-review') {
        $('checkout-review-submit').hide();
    }
});
//]]>
</script>
