<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @var Mage_Paypal_Block_Payflow_Link_Form $this
 */
?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none" class="form-list">
    <li>
    <?php echo $this->__('You will be required to enter your payment details after you place an order.') ?>
    </li>
</ul>
