<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @var Mage_Paypal_Block_Payflow_Link_Iframe $this
 */
?>
<html>
<head>
<script type="text/javascript">
//<![CDATA[
    if (window.top == window.self) {
        window.location = "<?php echo $this->getUrl('checkout/cart') ?>";
    }
    var window_top = window.top;
<?php if ($this->getGotoSection()): ?>
    var checkout_steps;

    try{
        checkout_steps = window.top.checkout.steps
    }catch(e){
        window_top.location="<?php echo $this->getUrl('checkout/cart') ?>";
    }

    for (var s = 0; s < checkout_steps.length; s++) {
        if (checkout_steps[s] == '<?php echo $this->getGotoSection() ?>') {
            break;
        }
        if (window_top.document.getElementById('opc-' + checkout_steps[s])) {
            window_top.document.getElementById('opc-' + checkout_steps[s]).addClassName('allow');
        }
    }
    window_top.checkout.gotoSection("<?php echo $this->getGotoSection() ?>");
    window_top.document.getElementById('checkout-review-submit').show();
    window_top.document.getElementById('iframe-warning').hide();
    <?php if ($this->getErrorMsg()): ?>
        alert('<?php echo $this->jsQuoteEscape($this->getErrorMsg()) ?>');
    <?php endif ?>
<?php elseif ($this->getGotoSuccessPage()) : ?>
    window_top.location="<?php echo $this->getUrl('checkout/onepage/success') ?>";
<?php else: ?>
    window_top.location="<?php echo $this->getUrl('checkout/cart') ?>";
<?php endif ?>
//]]>
</script>
</head>
<body></body>
</html>
