<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<?php if ($this->getChildHtml()): ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('sales')->__('Gift Options') ?></h4>
    </div>
    <fieldset>
        <?php echo $this->getChildHtml() ?>
    </fieldset>
</div>
<?php endif ?>
