<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Template $this */
?>
<?php if ($this->getChildHtml()): ?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo Mage::helper('sales')->__('Gift Options') ?></h4>
    </div>
    <fieldset>
        <?php echo $this->getChildHtml() ?>
    </fieldset>
</div>
<?php endif ?>
