<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Order_Totalbar $this */
?>
<?php if(count($this->getTotals()) > 0): ?>
<div class="box">
    <div class="entry-edit">
        <table border="0" cellspacing="0" width="100%">
            <tr>
            <?php foreach( $this->getTotals() as $_total ): ?>
                <td class="a-center">
                    <div <?php if ($_total['grand']): ?>class="grand-total"<?php endif ?>>
                        <?php echo $_total['label'] ?><br />
                        <?php echo $_total['value'] ?>
                    </div>
                </td>
            <?php endforeach ?>
            </tr>
        </table>
    </div>
</div>
<?php endif ?>
