<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Widget_View_Container
 * @var Mage_Adminhtml_Block_Widget_View_Container $this
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getViewHtml() ?>
