<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Adminhtml_Block_Widget_View_Container
 * @var Mage_Adminhtml_Block_Widget_View_Container $this
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getViewHtml() ?>
