<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php
/**
 * @see Mage_Paypal_Block_Adminhtml_System_Config_Fieldset_Hint
 * @var Mage_Paypal_Block_Adminhtml_System_Config_Fieldset_Hint $this
 */
?>
<?php if ($this->getHelpLink()): ?>
    <div class="paypal-payment-notice">
        <?php echo Mage::helper('paypal')->__('Not sure what PayPal payment method to use? Click <a href="%s" target="_blank">here</a> to learn more.', $this->getHelpLink()); ?>
    </div>
<?php endif ?>
