<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script type="text/javascript">
function install(type)
{
    $('run_iframe').style.display = 'block';
    $(type+'_form').submit();
}
</script>
<div class="content-header">
	<table cellspacing="0">
		<tr>
			<td><h3><?php echo $this->getTitle() ?></h3></td><td class="form-buttons"><?php echo $this->getBackButtonHtml() ?></td>
		 </tr>
	</table>
</div>
<div class="entry-edit">
    <form action="<?php echo $this->getUploadInstallUrl() ?>" method="post" id="local_form" enctype="multipart/form-data" target="run_iframe">
        
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Upload Local File") ?></h4>
    </div>
        <fieldset>
            <legend><?php echo $this->__("Upload Local File") ?></legend>

            <table class="" cellspacing="5">
                <tbody>
                    <tr><th><?php echo $this->__("Upload local file:") ?></th><td><input type="file" name="local"/></td></tr>
                </tbody>
            </table>

            <?php echo $this->getUploadButtonHtml() ?><br/>
        </fieldset>
    </form>

    <form action="<?php echo $this->getRemoteInstallUrl() ?>" method="post" id="remote_form" enctype="multipart/form-data" target="run_iframe">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Download Remote File") ?></h4>
    </div>
        <fieldset>
            <legend><?php echo $this->__("Download Remote File") ?></legend>

            <table class="" cellspacing="5">
                <tbody>
                    <tr><th><?php echo $this->__("Remote URL:") ?></th><td><input name="remote" class="input-text"/></td></tr>
                </tbody>
            </table>

            <?php echo $this->getRemoteButtonHtml() ?><br/>
        </fieldset>
    </form>

    <iframe id="run_iframe" name="run_iframe" src="<?php echo $this->getUrl('*/*/install') ?>" frameborder=0 style="display:none; width:100%; height:400px;"></iframe>
</div>