<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_GiftMessage_Block_Adminhtml_Sales_Order_View_Items
 * @var Mage_GiftMessage_Block_Adminhtml_Sales_Order_View_Items $this
 */
?>

<?php if ($this->canDisplayGiftmessage()): ?>
<div id="gift-message-form-data-<?php echo $this->getItem()->getId(); ?>" class="no-display">
    <form id="<?php echo $this->getFieldId('form') ?>" action="<?php echo $this->getSaveUrl() ?>">
        <input type="hidden" id="<?php echo $this->getFieldId('type') ?>" name="<?php echo $this->getFieldName('type') ?>" value="order_item" />
        <input type="hidden" id="<?php echo $this->getFieldId('sender') ?>" name="<?php echo $this->getFieldName('sender') ?>" value="<?php echo $this->getSender() ?>" />
        <input type="hidden" id="<?php echo $this->getFieldId('recipient') ?>" name="<?php echo $this->getFieldName('recipient') ?>"  value="<?php echo $this->getRecipient() ?>" />
        <input type="hidden" id="<?php echo $this->getFieldId('message') ?>" name="<?php echo $this->getFieldName('message') ?>"  value="<?php echo $this->getMessageText() ?>" />
    </form>

    <?php if ($this->getMessageText()): ?>
    <div class="gift-options-tooltip-content">
        <div><strong><?php echo $this->helper('giftmessage')->__('Gift Message')?></strong>: </div>
        <div><?php echo $this->getMessageText() ?></div>
    </div>
    <?php endif ?>
</div>
<?php endif ?>
