<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<?php /** @var Mage_Sales_Block_Adminhtml_Recurring_Profile_View_Tab_Info $this */ ?>

<?php for ($i = 1; $i <= 5; $i++):?>
    <?php $infoBlocks = $this->getChildGroup("info_blocks_row_{$i}"); ?>
    <?php if ($infoBlocks):?>
<div>
        <?php for ($j = 1; $j <= 2; $j++):?>
            <?php foreach ($infoBlocks as $alias => $block):?>
<?php if ($j == $this->getObjectData($block, 'view_column')):?>
    <div class="box-<?php echo $j == 1 ? 'left' : 'right'?>">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head"><?php echo $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></h4>
            </div>
            <div class="fieldset">
                <?php $html = $this->getChildHtml($alias) ?>
                <?php echo ($html ? $html : $this->__('No information available.')) ; ?>
            </div>
        </div>
    </div>
<?php endif ?>
            <?php endforeach ?>
        <?php endfor ?>
    <div class="clear"></div>
</div>
    <?php endif ?>
<?php endfor ?>
