#!/bin/bash

## Description: run PHPCodeSniffer
## Usage: phpcs
## Example: ddev phpcs <path-to-files>

[ -d .cache ] || mkdir .cache
php vendor/bin/phpcs -s -p --standard=.phpcs.dist.xml --cache=.cache/.phpcs.result.cache --report=full,summary "$@"
