#!/bin/bash

## Description: run rector
## Usage: rector
## Example: ddev rector <path-to-files>

if [ -f vendor/sreichel/openmage-rector/rector.php ]; then
  cp -n vendor/sreichel/openmage-rector/rector.php rector.php
fi
php vendor/bin/rector process "$@"
