#!/bin/bash

## Description: create Vendor Patches
## Usage: vendor-patches
## Example: ddev vendor-patches

php vendor/bin/vendor-patches generate --patches-file=patches.json --patches-folder=.vendor-patches "$@"
