<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Dashboard_Sales $this */
?>
<?php if(count($this->getTotals()) > 0): ?>
            <?php foreach( $this->getTotals() as $_total ): ?>
            <div class="entry-edit">
                <div class="entry-edit-head"><h4><?php echo $_total['label'] ?></h4></div>
                <fieldset class="a-center bold">
                    <span class="nowrap" style="font-size:18px;"><?php echo $_total['value'] ?><span style="font-size:14px; color:#686868;"><?php echo $_total['decimals'] ?></span></span>
                </fieldset>
            </div>
            <?php endforeach ?>
<?php endif ?>
