<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Dashboard_Totals $this */
?>
<?php if(count($this->getTotals()) > 0): ?>
<div class="box" id="dashboard_diagram_totals">
    <div class="entry-edit">
        <table cellspacing="0" width="100%">
            <tr>
            <?php foreach( $this->getTotals() as $_total ): ?>
                <td class="a-center bold">
                    <span><?php echo $_total['label'] ?></span><br />
                    <span class="nowrap" style="font-size:18px; color:#EA7601;"><?php echo $_total['value'] ?><span style="font-size:14px; color:#DE8946;"><?php echo $_total['decimals'] ?></span></span>
                </td>
            <?php endforeach ?>
            </tr>
        </table>
    </div>
</div>
<?php endif ?>
