<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @package     Errors
 */
?>
<!-- [start] center -->
    <div id="main" class="col-main">
    <!-- [start] content -->
        <div class="page-title">
            <h1>Service Temporarily Unavailable</h1>
        </div>
        <p>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.</p>
    <!-- [end] content -->
    </div>
<!-- [end] center -->
