<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title><?php echo $pageTitle?></title>
<base href="<?php echo $baseUrl ?>errors/" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="*" />
<link rel="stylesheet" href="<?php echo $skinUrl ?>/css/styles.css" type="text/css" />
<link rel="icon" href="<?php echo $skinUrl ?>/images/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $skinUrl ?>/images/favicon.ico" type="image/x-icon" />
</head>
<body>
    <div class="wrapper">
        <div class="page">
            <div class="header-container">
                <div class="header">
                    <a href="<?php echo $baseUrl?>" title="Magento Commerce" class="logo"><img src="<?php echo $skinUrl ?>/images/logo.gif" alt="Magento Commerce" /></a>
                </div>
            </div>
            <div class="main-container">
                <div class="main col1-layout">
                    <?php require_once MAGE_ERRORS_TEMPLATE_FILE; ?>
                </div>
            </div>
            <div class="footer-container">
                <div class="footer">
                    <address class="copyright">Magento is a trademark of Irubin Consulting Inc. DBA Varien. Copyright &copy; 2009 Irubin Consulting Inc.</address>
                </div>
            </div>
        </div>
    </div>
</body>
</html>