<div class="col-main">
    <div class="page-title">
        <h2>There has been an error processing your request.</h2>
    </div>
    <?php if ($showSentMsg): ?>
    <ul class="messages">
        <li class="success-msg">
            <ul>
                <li>Your message was submitted and will be responded as soon as possible. Thank you for reporting.</li>
            </ul>
        </li>
    </ul>
    <?php endif; ?>
    <?php if ($showSendForm): ?>
    <ul class="messages">
        <li class="note-msg">
            <ul>
                <li>We are currently experiencing some technical issues. We apologize for the inconvenience and will contact you shortly to resolve the issue. To help us serve you please fill in the form below.</li>
            </ul>
        </li>
    </ul>
        <?php if ($showErrorMsg): ?>
    <ul class="messages">
        <li class="error-msg">
            <ul>
                <li>Please fill all required fields with valid information</li>
            </ul>
        </li>
    </ul>
        <?php endif; ?>
    <form action="<?php echo "?id={$reportId}&amp;s={$store}" ?>" method="post" id="form-validate">
        <fieldset class="fieldset">
            <input type="hidden" name="error_hash" value="<?php echo $errorHash ?>" />
            <h3>Personal Information</h3>
            <ul class="form-list group-select">
                <li class="fields">
                    <div class="field">
                        <label for="firstname" class="required"><em>*</em>First Name</label>
                        <span class="input-box"><input type="text" name="firstname" id="firstname" value="<?php echo $firstName ?>" title="First Name" class="required-entry input-text" /></span>
                    </div>
                    <div class="field">
                        <label for="lastname" class="required"><em>*</em>Last Name </label>
                        <span class="input-box"><input type="text" name="lastname" id="lastname" value="<?php echo $lastName ?>" title="Last Name" class="required-entry input-text" /></span>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="firstname" class="required"><em>*</em>Email Address</label>
                        <span class="input-box"><input type="text" name="email" id="email_address" value="<?php echo $email ?>" title="Email Address" class="validate-email required-entry input-text" /></span>
                    </div>
                    <div class="field">
                        <label for="firstname">Telephone</label>
                        <span class="input-box"><input type="text" name="telephone" id="telephone" value="<?php echo $telephone ?>" title="Telephone" class="input-text" /></span>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <label for="firstname">Comment</label>
                        <span class="input-box"><textarea name="comment" cols="5" rows="3"><?php echo $comment ?></textarea></span>
                    </div>
                </li>
            </ul>
        </fieldset>
        <div class="buttons-set form-buttons btn-only">
            <button name="submit" class="button" type="submit"><span><span>Submit</span></span></button>
        </div>
        <p class="required">* Required Fields</p>
    </form>
    <?php endif; ?>
    <?php if ($action == 'print'): ?>
    <div class="trace-container">
        <div class="trace">
            <pre><?php echo $reportData[0] ?><br />
<strong>Trace:</strong>
<?php echo htmlspecialchars($reportData[1]) ?><br /></pre>
        </div>
    </div>
    <?php endif; ?>
</div>
