<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($_info = $this->getInfo()): ?>
<!--<?php echo $this->__('Name on the Card: %s', $this->getInfo()->getCcOwner()) ?><br />-->
<?php echo $this->__('Credit Card Type: %s', $this->getCcTypeName()) ?><br />
<?php echo $this->__('Credit Card Number: xxxx-%s', $this->getInfo()->getCcLast4()) ?><br />
<?php echo $this->__('Expiration Date: %s/%s', $this->getCcExpMonth(), $this->getInfo()->getCcExpYear()) ?><br />
<?php if($this->getInfo()->getCcSsIssue()): ?>
<?php echo $this->__("Switch/Solo card issue number: %s", $this->getInfo()->getCcSsIssue()) ?><br />
<?php endif; ?>
<?php if($this->getInfo()->getCcSsStartYear()): ?>
<?php echo $this->__('Switch/Solo card start Date: %s/%s', $this->getCcStartMonth(), $this->getInfo()->getCcSsStartYear()) ?>
<?php endif; ?>
<?php endif; ?>