<?php
/**
 * OpenMage
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     default_iphone
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Store switcher template
 *
 * @see Mage_Core_Block_Store_Switcher
 */
?>
<?php if(count($this->getGroups())>1): ?>
    <li id="store-switcher">
        <a href="#"><?php echo $this->__('Selected Store') ?>: <span id="current-store"></span></a>
        <ol class="switcher-options" style="display:none;">
            <?php foreach ($this->getGroups() as $_group): ?>
            <?php $_selected = ($_group->getId() == $this->getCurrentGroupId()) ? ' class="selected"' : '' ?>
            <li<?php echo $_selected ?>>
                <a href="<?php echo $_group->getCurrentUrl() ?>"><?php echo $this->escapeHtml($_group->getName()) ?></a>
            </li>
            <?php endforeach ?>
        </ol>
    </li>
<?php endif ?>
