<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_CatalogInventory_Block_Stockqty_Default
 * @var Mage_CatalogInventory_Block_Stockqty_Default $this 
 */
?>
<?php if($this->isMsgVisible()): ?>
    <p class="availability-only">
        <span title="<?php echo $this->__('Only %s left', ($this->getStockQty())) ?>"><?php echo $this->__('Only %s left', "<strong>{$this->getStockQty()}</strong>") ?></span>
    </p>
<?php endif ?>
