<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
$_item = $this->getItem();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
$_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()]));
$_deleteUrl = $this->getDeleteUrlCustom(false);
?>
<tr>
<td><a href="<?= $this->getProductUrl() ?>" class="product-image"
       title="<?= $this->escapeHtml($this->getProductName()) ?>"><img
            src="<?= $this->getProductThumbnail()->resize(75) ?>"
            alt="<?= $this->escapeHtml($this->getProductName()) ?>"/></a></td>
<td>
    <h2 class="product-name"><a
            href="<?= $this->getProductUrl() ?>"><?= $this->escapeHtml($this->getProductName()) ?></a>
    </h2>
    <?php if ($_options = $this->getOptionList()): ?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif ?>><?= $_formatedOptionValue['value'] ?>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <div class="truncated_full_value">
                            <dl class="item-options">
                                <dt><?= $this->escapeHtml($_option['label']) ?></dt>
                                <dd><?= $_formatedOptionValue['full_view'] ?></dd>
                            </dl>
                        </div>
                    <?php endif ?>
                </dd>
            <?php endforeach ?>
        </dl>
    <?php endif ?>
    <!-- downloadable -->
    <?php if ($links = $this->getLinks()): ?>
        <dl class="item-options">
            <dt><?= $this->escapeHtml($this->getLinksTitle()) ?></dt>
            <?php foreach ($links as $link): ?>
                <dd><?= $this->escapeHtml($link->getTitle()) ?></dd>
            <?php endforeach ?>
        </dl>
    <?php endif ?>
    <!-- EOF downloadable -->

    <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <div class="shopping-cart-item-message <?= $message['type'] ?>">
                * <?= $this->escapeHtml($message['text']) ?>
            </div>
        <?php endforeach ?>
    <?php endif ?>
</td>
<td class="a-center">
    <a href="<?= $this->getConfigureUrl() ?>"
       title="<?= Mage::helper('core')->quoteEscape($this->__('Edit item parameters')) ?>"><?= $this->__('Edit') ?></a>
</td>
<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
    <td class="a-center">
        <a href="<?= $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()) ?>"
           class="link-wishlist"><?= $this->__('Move') ?></a>
    </td>
<?php endif ?>
<?php if ($canApplyMsrp): ?>
    <td class="a-right"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif ?>>
        <span class="cart-price">
            <span class="cart-msrp-unit"><?= $this->__('See price before order confirmation.') ?></span>
            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
            <a id="<?= $helpLinkId ?>" href="#"
               class="map-help-link"><?= $this->__("What's this?") ?></a>
            <script type="text/javascript">
                Catalog.Map.addHelpLink($('<?= $helpLinkId ?>'), "<?= Mage::helper('core')->jsQuoteEscape($this->__("What's this?")) ?>");
            </script>
        </span>
    </td>
<?php else: ?>


    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="a-right">
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, [1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <div class="cart-tax-total"
                 onclick="taxToggle('eunit-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                <div class="cart-price">
                    <?php endif ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()) ?>
                    <?php else: ?>
                        <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                    <?php endif ?>

                </div>


                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="eunit-item-tax-details<?= $_item->getId() ?>"
                         style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php endif ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total"
                             onclick="taxToggle('eunit-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?= Mage::helper('weee')->__('Total') ?>
                                : <?= $this->helper('checkout')->formatPrice($_item->getCalculationPrice() + $_item->getWeeeTaxAppliedAmount() + $_item->getWeeeTaxDisposition()) ?></span>
                        </div>
                    <?php endif ?>
                <?php endif ?>
        </td>
    <?php endif ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td>
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($_item, [1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
            <div class="cart-tax-total"
                 onclick="taxToggle('unit-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                <?php else: ?>
                <div class="cart-price">
                    <?php endif ?>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)) ?>
                    <?php else: ?>
                        <?= $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxDisposition()) ?>
                    <?php endif ?>

                </div>
                <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                    <div class="cart-tax-info" id="unit-item-tax-details<?= $_item->getId() ?>"
                         style="display:none;">
                        <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                            <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                                <span class="weee"><?= $tax['title'] ?>
                                    : <?= Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'], true, true) ?></span>
                            <?php endforeach ?>
                        <?php endif ?>
                    </div>

                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <div class="cart-tax-total"
                             onclick="taxToggle('unit-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                            <span class="weee"><?= Mage::helper('weee')->__('Total incl. tax') ?>
                                : <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getWeeeTaxInclTax($_item)) ?></span>
                        </div>
                    <?php endif ?>
                <?php endif ?>
        </td>
    <?php endif ?>
<?php endif ?>
<td class="a-center">
    <input name="cart[<?= $_item->getId() ?>][qty]" value="<?= $this->getQty() ?>" size="4"
           title="<?= Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty"
           data-cart-item-id="<?= $this->jsQuoteEscape($_item->getSku()) ?>" maxlength="12"/>
</td>
<?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="a-right">
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, [1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
        <div class="cart-tax-total"
             onclick="taxToggle('esubtotal-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
            <div class="cart-price">
                <?php endif ?>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-msrp-subtotal">--</span>
                <?php else: ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?= $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()) ?>
                    <?php else: ?>
                        <?= $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                    <?php endif ?>
                <?php endif ?>

            </div>
            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                <div class="cart-tax-info" id="esubtotal-item-tax-details<?= $_item->getId() ?>"
                     style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php endif ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total"
                         onclick="taxToggle('esubtotal-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?= Mage::helper('weee')->__('Total') ?>
                            : <?= $this->helper('checkout')->formatPrice($_item->getRowTotal() + $_item->getWeeeTaxAppliedRowAmount() + $_item->getWeeeTaxRowDisposition()) ?></span>
                    </div>
                <?php endif ?>
            <?php endif ?>
    </td>
<?php endif ?>
<?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td>
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php if (Mage::helper('weee')->typeOfDisplay($_item, [1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
        <div class="cart-tax-total"
             onclick="taxToggle('subtotal-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
            <div class="cart-price">
                <?php endif ?>

                <?php if ($canApplyMsrp): ?>
                    <span class="cart-msrp-subtotal">--</span>
                <?php else: ?>
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, [0, 1, 4], 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?>
                    <?php else: ?>
                        <?= $this->helper('checkout')->formatPrice($_incl - $_item->getWeeeTaxRowDisposition()) ?>
                    <?php endif ?>
                <?php endif ?>

            </div>


            <?php if (Mage::helper('weee')->getApplied($_item)): ?>

                <div class="cart-tax-info" id="subtotal-item-tax-details<?= $_item->getId() ?>"
                     style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
                            <span class="weee"><?= $tax['title'] ?>
                                : <?= Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'], true, true) ?></span>
                        <?php endforeach ?>
                    <?php endif ?>
                </div>

                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                    <div class="cart-tax-total"
                         onclick="taxToggle('subtotal-item-tax-details<?= $_item->getId() ?>', this, 'cart-tax-total-expanded');">
                        <span class="weee"><?= Mage::helper('weee')->__('Total incl. tax') ?>
                            : <?= $this->helper('checkout')->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)) ?></span>
                    </div>
                <?php endif ?>
            <?php endif ?>
    </td>
<?php endif ?>
    <td class="a-center product-cart-remove">
        <a href="#"
           title="<?= Mage::helper('core')->quoteEscape($this->__('Remove Item')) ?>"
           class="btn-remove btn-remove2"
           onclick="customFormSubmit('<?= $_deleteUrl ?>', '<?= $_params ?>', 'post')">
            <?= $this->__('Remove Item') ?>
        </a>
    </td>
</tr>
