<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<script type="text/javascript">
//<![CDATA[
function saveAndContinueEdit(){
    disableElements('save');
    var activeTab = product_attribute_tabsJsTabs.activeTab.id;
    if (editForm.submit(document.getElementById('edit_form').action+'back/edit/tab/' + activeTab) == false) {
        enableElements('save');
     }
    varienGlobalEvents.attachEventHandler('formValidateAjaxComplete', function (){
        enableElements('save');
    });
}

function saveAttribute(){
    disableElements('save');
    if (editForm.submit() == false){
        enableElements('save');
    }
    varienGlobalEvents.attachEventHandler('formValidateAjaxComplete', function (){
        enableElements('save');
    });
}

function toggleApplyVisibility(select) {
    if (document.getElementById(select).value == 1) {
        document.getElementById(select).nextElementSibling.classList.remove('no-display');
        document.getElementById(select).nextElementSibling.classList.remove('ignore-validate');

    } else {
        document.getElementById(select).nextElementSibling.classList.add('no-display');
        document.getElementById(select).nextElementSibling.classList.add('ignore-validate');
        var options = document.getElementById(select).nextElementSibling.options;
        for( var i=0; i < options.length; i++) {
            options[i].selected = false;
        }
    }
}

function checkOptionsPanelVisibility(){
    if(document.getElementById('matage-options-panel')){
        var panel = document.getElementById('matage-options-panel');
        if(document.getElementById('frontend_input') && (document.getElementById('frontend_input').value=='select' || document.getElementById('frontend_input').value=='multiselect')){
            panel.style.display = '';
        }
        else {
            panel.style.display = 'none';
        }
    }
}

function bindAttributeInputType()
{
    checkOptionsPanelVisibility();
    switchDefaultValueField();
    checkIsConfigurableVisibility();
    if(document.getElementById('frontend_input') && (document.getElementById('frontend_input').value=='select' || document.getElementById('frontend_input').value=='multiselect' || document.getElementById('frontend_input').value=='price')){
        if(document.getElementById('is_filterable') && !document.getElementById('is_filterable').getAttribute('readonly')){
            document.getElementById('is_filterable').disabled = false;
        }
        if(document.getElementById('is_filterable_in_search') && !document.getElementById('is_filterable_in_search').getAttribute('readonly')){
            document.getElementById('is_filterable_in_search').disabled = false;
        }
        if(document.getElementById('backend_type') && document.getElementById('backend_type').options){
            for(var i=0;i<document.getElementById('backend_type').options.length;i++){
                if(document.getElementById('backend_type').options[i].value=='int') document.getElementById('backend_type').selectedIndex = i;
            }
        }
    }
    else {
        if(document.getElementById('is_filterable')){
            document.getElementById('is_filterable').selectedIndex=0;
            document.getElementById('is_filterable').disabled = true;
        }
        if(document.getElementById('is_filterable_in_search')){
            document.getElementById('is_filterable_in_search').disabled = true;
        }
    }

    if (document.getElementById('frontend_input') && (document.getElementById('frontend_input').value=='multiselect'
        || document.getElementById('frontend_input').value=='gallery'
        || document.getElementById('frontend_input').value=='textarea')) {
        if (document.getElementById('used_for_sort_by')) {
            document.getElementById('used_for_sort_by').disabled = true;
        }
    }
    else {
        if (document.getElementById('used_for_sort_by') && !document.getElementById('used_for_sort_by').getAttribute('readonly')) {
            document.getElementById('used_for_sort_by').disabled = false;
        }
    }

    setRowVisibility('is_wysiwyg_enabled', false);
    setRowVisibility('is_html_allowed_on_front', false);

    switch (document.getElementById('frontend_input').value) {
        case 'textarea':
            setRowVisibility('is_wysiwyg_enabled', true);
            if(document.getElementById('is_wysiwyg_enabled').value == '0'){
                setRowVisibility('is_html_allowed_on_front', true);
                document.getElementById('is_html_allowed_on_front').disabled = false;
            }
            document.getElementById('frontend_class').value = '';
            document.getElementById('frontend_class').disabled = true;
            break;
        case 'text':
            setRowVisibility('is_html_allowed_on_front', true);
            document.getElementById('is_html_allowed_on_front').disabled = false;

            if (!document.getElementById('frontend_class').getAttribute('readonly')) {
                document.getElementById('frontend_class').disabled = false;
            }
            break;
        case 'select':
        case 'multiselect':
            setRowVisibility('is_html_allowed_on_front', true);
            document.getElementById('is_html_allowed_on_front').disabled = false;
            break;
        default:
            document.getElementById('frontend_class').value = '';
            document.getElementById('frontend_class').disabled = true;
    }

    switchIsFilterable();
}

function switchIsFilterable()
{
    if (document.getElementById('is_filterable')) {
        if (document.getElementById('is_filterable').selectedIndex == 0) {
            document.getElementById('position').disabled = true;
        } else {
            if (!document.getElementById('position').getAttribute('readonly')){
                document.getElementById('position').disabled = false;
            }
        }
    }
}

function disableApplyToValue(value)
{
    var applyToSelect = document.getElementById('apply_to');
    for (i=0;i<applyToSelect.options.length;i++) {
        if (value == applyToSelect.options[i].value) {
            applyToSelect.options[i].disabled = true;
            applyToSelect.options[i].selected = false;
        }
    }
}

function switchDefaultValueField()
{
    if (!document.getElementById('frontend_input')) {
        return;
    }

    var currentValue = document.getElementById('frontend_input').value;

    var defaultValueTextVisibility = false;
    var defaultValueTextareaVisibility = false;
    var defaultValueDateVisibility = false;
    var defaultValueYesnoVisibility = false;
    var scopeVisibility = true;

    switch (currentValue) {
        case 'select':
            optionDefaultInputType = 'radio';
            break;

        case 'multiselect':
            optionDefaultInputType = 'checkbox';
            break;

        case 'date':
            defaultValueDateVisibility = true;
            break;

        case 'boolean':
            defaultValueYesnoVisibility = true;
            break;

        case 'textarea':
            defaultValueTextareaVisibility = true;
            break;

        case 'media_image':
            defaultValueTextVisibility = false;
            break;
        case 'price':
            scopeVisibility = false;
        default:
            defaultValueTextVisibility = true;
            break;
    }

    var applyToSelect = document.getElementById('apply_to');
    switch (currentValue) {
        <?php foreach (Mage::helper('catalog')->getAttributeDisabledTypes() as $type=>$disabled): ?>
            case '<?php echo $type; ?>':
            <?php foreach ($disabled as $one): ?>
                disableApplyToValue('<?php echo $one; ?>');
            <?php endforeach ?>
            break;
        <?php endforeach ?>
        default:
        for (i=0;i<applyToSelect.options.length;i++) {
            applyToSelect.options[i].disabled = false;
        }
        break;
    }

    switch (currentValue) {
        case 'media_image':
            document.getElementById('front_fieldset').previousElementSibling.style.display = 'none'; void(0);
            document.getElementById('front_fieldset').style.display = 'none';

            setRowVisibility('is_required', false);
            setRowVisibility('is_unique', false);
            setRowVisibility('frontend_class', false);
        break;

        <?php foreach (Mage::helper('catalog')->getAttributeHiddenFields() as $type=>$fields): ?>
            case '<?php echo $type; ?>':
                <?php foreach ($fields as $one): ?>
                    <?php if ($one == '_front_fieldset'): ?>
                        document.getElementById('front_fieldset').previousElementSibling.style.display = 'none'; void(0);
                        document.getElementById('front_fieldset').style.display = 'none';
                    <?php elseif ($one == '_default_value'): ?>
                        defaultValueTextVisibility =
                        defaultValueTextareaVisibility =
                        defaultValueDateVisibility =
                        defaultValueYesnoVisibility = false;
                    <?php elseif ($one == '_scope'): ?>
                        scopeVisibility = false;
                    <?php else: ?>
                        setRowVisibility('<?php echo $one; ?>', false);
                    <?php endif ?>
                <?php endforeach ?>
            break;
        <?php endforeach ?>

        default:
            document.getElementById('front_fieldset').previousElementSibling.style.display = '';
            document.getElementById('front_fieldset').style.display = '';
            setRowVisibility('is_required', true);
            setRowVisibility('is_unique', true);
            setRowVisibility('frontend_class', true);
            setRowVisibility('is_configurable', true);
        break;
    }

    setRowVisibility('default_value_text', defaultValueTextVisibility);
    setRowVisibility('default_value_textarea', defaultValueTextareaVisibility);
    setRowVisibility('default_value_date', defaultValueDateVisibility);
    setRowVisibility('default_value_yesno', defaultValueYesnoVisibility);
    setRowVisibility('is_global', scopeVisibility);

    var elems = document.getElementsByName('default[]');
    for (var i = 0; i < elems.length; i++) {
        elems[i].type = optionDefaultInputType;
    }
}

function setRowVisibility(id, isVisible)
{
    if (document.getElementById(id)) {
        var td = document.getElementById(id).parentNode;
        var tr = td.parentNode;

        if (isVisible) {
            tr.style.display = '';
        } else {
            tr.blur();
            tr.style.display = 'none';
        }
    }
}

function checkIsConfigurableVisibility()
{
    if (!document.getElementById('is_configurable') || !document.getElementById('is_global') || !document.getElementById('frontend_input')) return;
    if (document.getElementById('is_global').value==1 && document.getElementById('frontend_input').value=='select') {
        setRowVisibility('is_configurable', true);
    } else {
        setRowVisibility('is_configurable', false);
    }
}

function updateRequriedOptions()
{
    if (document.getElementById('frontend_input').value=='select' && document.getElementById('is_required').value==1) {
        document.getElementById('option-count-check').classList.add('required-options-count');
    } else {
        document.getElementById('option-count-check').classList.remove('required-options-count');
    }
}

if(document.getElementById('frontend_input')){
    document.getElementById('frontend_input').addEventListener('change', updateRequriedOptions);
    document.getElementById('frontend_input').addEventListener('change', bindAttributeInputType);
    document.getElementById('is_global').addEventListener('change', checkIsConfigurableVisibility);
}

if (document.getElementById('is_filterable')) {
    document.getElementById('is_filterable').addEventListener('change', switchIsFilterable);
}

if (document.getElementById('is_required')) {
    document.getElementById('is_required').addEventListener('change', updateRequriedOptions);
}
bindAttributeInputType();
//]]>
</script>
