<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div id="<?= $this->getHtmlId() ?>">
<table cellspacing="0" cellpadding="0" class="massaction">
<tr>
    <td><?php if ($this->getUseSelectAll()):?>
        <a href="#" onclick="return <?= $this->getJsObjectName() ?>.selectAll()"><?= $this->__('Select All') ?></a>
        <span class="separator">|</span>
        <a href="#" onclick="return <?= $this->getJsObjectName() ?>.unselectAll()"><?= $this->__('Unselect All') ?></a>
        <span class="separator">|</span>
        <?php endif ?>
        <a href="#" onclick="return <?= $this->getJsObjectName() ?>.selectVisible()"><?= $this->__('Select Visible') ?></a>
        <span class="separator">|</span>
        <a href="#" onclick="return <?= $this->getJsObjectName() ?>.unselectVisible()"><?= $this->__('Unselect Visible') ?></a>
        <span class="separator">|</span>
        <strong id="<?= $this->getHtmlId() ?>-count">0</strong> <?= $this->__('items selected') ?>
    </td>
    <td>
        <div class="right">
            <div class="entry-edit">
                <?php if ($this->getHideFormElement() !== true):?>
                <form action="" id="<?= $this->getHtmlId() ?>-form" method="post">
                <?php endif ?>
                    <?php echo $this->getBlockHtml('formkey')?>
                    <fieldset>
                        <span class="field-row">
                            <label for="<?= $this->getHtmlId() ?>-select"><?= $this->__('Actions') ?></label>
                            <select id="<?= $this->getHtmlId() ?>-select" class="required-entry select absolute-advice local-validation">
                                <option value=""></option>
                                <?php foreach($this->getGroupedItems() as $key => $group): ?>
                                    <?php if ($key === 'default'): ?>
                                        <?php foreach($group as $_item): ?>
                                            <option value="<?= $_item->getId() ?>"<?= ($_item->getSelected() ? ' selected="selected"' : '')?>><?php echo $_item->getLabel() ?></option>
                                        <?php endforeach ?>
                                    <?php elseif ($key === 'grouped'): ?>
                                        <?php foreach($group as $label => $_massGroup): ?>
                                            <optgroup label="<?= $this->quoteEscape($label) ?>">
                                                <?php foreach($_massGroup as $_item): ?>
                                                    <option value="<?= $_item->getId() ?>"<?= ($_item->getSelected() ? ' selected="selected"' : '')?>><?php echo $_item->getLabel() ?></option>
                                                <?php endforeach ?>
                                            </optgroup>
                                        <?php endforeach ?>
                                    <?php endif ?>
                                <?php endforeach ?>
                            </select>
                        </span>
                        <span class="outer-span" id="<?= $this->getHtmlId() ?>-form-hiddens"></span>
                        <span class="outer-span" id="<?= $this->getHtmlId() ?>-form-additional"></span>
                        <span class="field-row">
                            <?= $this->getApplyButtonHtml() ?>
                        </span>
                    </fieldset>
                <?php if ($this->getHideFormElement() !== true):?>
                </form>
                <?php endif ?>
            </div>

            <div class="no-display">
            <?php foreach($this->getItems() as $_item): ?>
                <div id="<?= $this->getHtmlId() ?>-item-<?= $_item->getId() ?>-block">
                    <?= $_item->getAdditionalActionBlockHtml() ?>
                </div>
            <?php endforeach ?>
            </div>
        </div>
    </td>
</tr>
</table>
<?php if(!$this->getParentBlock()->canDisplayContainer()): ?>
<script type="text/javascript">
    <?= $this->getJsObjectName() ?>.setGridIds('<?= $this->getGridIdsJson() ?>');
</script>
<?php endif ?>
</div>
