<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-tax"><?php echo $header ?></h3></td>
            <td class="form-buttons">
                <button class="scalable add" onclick="window.location.href='<?php echo $createUrl ?>'"><span><span><span><?php echo Mage::helper('tax')->__('Add New Tax Rule') ?></span></span></span></button>
            </td>
        </tr>
    </table>
</div>
