<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-tax"><?php echo $header ?></h3></td>
            <td class="form-buttons">
                <button class="scalable add" onclick="window.location.href='<?php echo $createUrl ?>'"><span><span><span><?php echo Mage::helper('tax')->__('Add New Tax Rule') ?></span></span></span></button>
            </td>
        </tr>
    </table>
</div>
