<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3><?php echo $header ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getBackButtonHtml(); ?>
                <?php echo $this->getResetButtonHtml(); ?>
                <?php echo $this->getSaveButtonHtml(); ?>
                <?php echo $this->getDeleteButtonHtml(); ?>
            </td>
        </tr>
    </table>
</div>
<?php if( $form ): ?>
<?php echo $form->toHtml(); ?>
<script type="text/javascript">
    var wigetForm = new varienForm('<?php echo $form->getForm()->getId() ?>');
</script>
<?php endif ?>
