<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */
?>
<?php
/**
 * @var Mage_Page_Block_Template_Container $this
 */
?>
<div class="page-title">
    <h1><?php echo $this->getTitle() ?></h1>
</div>
<?php echo $this->getChildHtml() ?>
