<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?= $this->getFormInitScripts() ?>
<div class="content-header">
    <?= $this->getHeaderHtml() ?>
    <p class="content-buttons form-buttons"><?= $this->getButtonsHtml('header') ?></p>
</div>
<?php if( !$this->isSingleStoreMode() ): ?>
    <?= $this->getStoreSwitcherHtml() ?>
<?php endif ?>

<form action="<?= $this->getSaveUrl() ?>" method="post" id="edit_form">
    <?= $this->getFormHtml() ?>

    <?= $this->getTagAssignAccordionHtml() ?>

<script type="text/javascript">
    function saveAndContinueEdit(url) {
        var tagForm = new varienForm('edit_form');
        tagForm.submit(url);
    }
</script>

</form>

<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="content-buttons form-buttons"><?= $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif ?>
<script type="text/javascript">
    var editForm = new varienForm('edit_form', '<?= $this->getValidationUrl() ?>');
</script>
<?= $this->getFormScripts() ?>
<?= $this->getAcordionsHtml() ?>
