<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Core_Block_Template
 * @var Mage_Core_Block_Template $this
 */
?>
<div class="block block-banner">
    <div class="block-content">
        <?php if(strtolower(substr($this->getLinkUrl(), 0, 4)) === 'http'): ?>
            <a href="<?php echo $this->getLinkUrl() ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__($this->getImgAlt())) ?>">
        <?php elseif($this->getLinkUrl()): ?>
            <a href="<?php echo $this->getUrl($this->getLinkUrl()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__($this->getImgAlt())) ?>">
        <?php endif ?>
            <img src="<?php echo $this->getSkinUrl($this->getImgSrc()) ?>"<?php if(!$this->getLinkUrl()): ?> title="<?php echo Mage::helper('core')->quoteEscape($this->__($this->getImgAlt())) ?>"<?php endif ?> alt="<?php echo Mage::helper('core')->quoteEscape($this->__($this->getImgAlt())) ?>" />
        <?php if($this->getLinkUrl()): ?>
        </a>
        <?php endif ?>
    </div>
</div>
