<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/**
 * @see Mage_Install_Block_State
 * @var Mage_Install_Block_State $this
 */
?>
<div style="border:1px solid #ccc; background:#f6f6f6;">
    <h2 style="margin-bottom:0; border-bottom:1px solid #ccc; padding:4px 10px; color:#3c5974; font-size:1.4em;"><?php echo $this->__('Installation') ?></h2>
<ol style="padding:10px; border-top:1px solid #fff;">
<?php foreach($steps as $_step): ?>
    <li <?php if($_step->getActive()): ?>style="color:green; font-weight:bold; "<?php endif ?>><?php echo $this->__($_step->getCode()) ?></li>
<?php endforeach ?>
</ol>
</div>

<br/>
<p>
    <?php echo $this->__('Having trouble installing OpenMage?') ?>
    <?php echo $this->__('Check out our') ?> <a href="https://www.openmage.org/magento-lts/install.html" id="installation_guide_link"><?php echo $this->__('Installation Guide') ?></a>
    <script type="text/javascript">
        $('installation_guide_link').target = "installation_guide";
    </script>
</p>
