<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Catalog_Product_Edit_Tab_Options_Type_Select $this */
?>

<script type="text/javascript">
//<![CDATA[
OptionTemplateSelect = '<table class="border" cellpadding="0" cellspacing="0">'+
        '<input type="hidden" class="required-option-select-type-rows" name="validation_{{option_id}}_result" value="" >'+
        '<thead>'+
        '<tr class="headings">'+
            '<th class="type-title"><?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('Title')) ?> <span class="required">*</span></th>'+
            <?php if ($this->getCanReadPrice() !== false) : ?>
            '<th class="type-price"><?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('Price')) ?></th>' +
            '<th class="type-type"><?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('Price Type')) ?></th>' +
            <?php endif ?>
            '<th class="type-sku"><?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('SKU')) ?></th>'+
            '<th class="type-order"><?php echo Mage::helper('core')->jsQuoteEscape(Mage::helper('catalog')->__('Sort Order')) ?></th>'+
            '<th class="type-butt last">&nbsp;</th>'+
        '</tr>'+
        '</thead>'+
        '<tbody id="select_option_type_row_{{option_id}}">'+
        '</tbody>'+
        '<tfoot>'+
        '<tr>'+
        '<td colspan="100" class="a-right"><?php echo $this->getAddButtonHtml() ?></td>'+
        '</tr>'+
        '</tfoot>'+
    '</table>';

OptionTemplateSelectRow = '<tr id="product_option_{{id}}_select_{{select_id}}">'+
            '<td>'+
            '<input type="hidden" name="product[options][{{id}}][values][{{select_id}}][option_type_id]" value="{{option_type_id}}">'+
            '<input type="hidden" id="product_option_{{id}}_select_{{select_id}}_is_delete" name="product[options][{{id}}][values][{{select_id}}][is_delete]" value="">'+
            '<input type="text" class="required-entry input-text select-type-title" id="product_option_{{id}}_select_{{select_id}}_title" name="product[options][{{id}}][values][{{select_id}}][title]" value="{{title}}">{{checkboxScopeTitle}}</td>'+
            <?php if ($this->getCanReadPrice() !== false) : ?>
            '<td><input type="text" class="input-text validate-number product-option-price" id="product_option_{{id}}_select_{{select_id}}_price" name="product[options][{{id}}][values][{{select_id}}][price]" value="{{price}}"<?php if ($this->getCanEditPrice() === false) : ?> disabled="disabled"<?php endif ?>></td>' +
            '<td><?php echo $this->getPriceTypeSelectHtml() ?>{{checkboxScopePrice}}</td>' +
            <?php else: ?>
            '<input type="hidden" id="product_option_{{id}}_select_{{select_id}}_price" name="product[options][{{id}}][values][{{select_id}}][price]">' +
            '<input type="hidden" name="product[options][{{id}}][values][{{select_id}}][price_type]" id="product_option_{{id}}_select_{{select_id}}_price_type">' +
            <?php endif ?>
            '<td><input type="text" class="input-text" name="product[options][{{id}}][values][{{select_id}}][sku]" value="{{sku}}"></td>'+
            '<td><input type="text" class="validate-zero-or-greater input-text" name="product[options][{{id}}][values][{{select_id}}][sort_order]" value="{{sort_order}}"></td>'+
            '<td class="last"><span title="Delete row"><?php echo $this->getDeleteButtonHtml() ?></span></td>'+
        '</tr>';

selectOptionType = {
    div : 'select_option_type_row',
    itemCount : 0,
    templateSyntax : /(^|.|\r|\n)({{(\w+)}})/,
    templateText : OptionTemplateSelectRow,
    add : function(data) {
        var _syntax = this.templateSyntax;
        this.template = { evaluate: function(obj) { return selectOptionType.templateText.replace(new RegExp(_syntax.source, 'g'), function(m, p1, p2, p3) { return p1 + (obj[p3] !== undefined ? obj[p3] : ''); }); } };

        if (data.target || data.srcElement) {//data is Event (work in IE and Firefox)
            element = data.target.closest('button');
            optionId = element.getAttribute('id').replace('add_select_row_button_', '');
            data = {};
            data.option_type_id = '-1';
            data.select_id = this.itemCount;
        } else {
            optionId = data.option_id;
            data.select_id = data.option_type_id;
            this.itemCount = data.item_count;
        }

        data.id  = optionId;

        var targetEl = document.getElementById(this.div+'_'+data.id);
        targetEl.insertAdjacentHTML('beforeend', this.template.evaluate(data));

        var rowSelector = '#product_option_'+data.id+'_select_'+data.select_id;
        var inputs = document.querySelectorAll(rowSelector+' input, '+rowSelector+' select, '+rowSelector+' textarea');
        inputs.forEach(function(el) { el.addEventListener('change', el.setHasChanges.bind(el)); });
        var buttons = document.querySelectorAll(rowSelector+' button');
        buttons.forEach(function(el) { el.addEventListener('click', el.setHasChanges.bind(el));  });

        if (data.checkboxScopeTitle) {
            //set disabled
            if (document.getElementById('product_option_'+data.id+'_select_'+data.select_id+'_title') && data.scopeTitleDisabled) {
                document.getElementById('product_option_'+data.id+'_select_'+data.select_id+'_title').disabled = true;
            }
        }
        if (data.checkboxScopePrice) {
            //set disabled
            if (document.getElementById('product_option_'+data.id+'_select_'+data.select_id+'_price') && data.scopePriceDisabled) {
                document.getElementById('product_option_'+data.id+'_select_'+data.select_id+'_price').disabled = true;
                document.getElementById('product_option_'+data.id+'_select_'+data.select_id+'_price_type').disabled = true;
            }
        }

        if (data.price_type) {
            Array.from(document.getElementById('product_option_'+data.id+'_select_'+data.select_id+'_price_type').options).forEach(function(option){
                if (option.value==data.price_type) option.selected = true;
            });
        }

        this.itemCount++;
        this.bindRemoveButtons();
    },
    remove : function(event){
        var element = event.target.closest('tr');

        if(element){
            document.getElementById(element.getAttribute('id')+'_is_delete').value = '1';
            element.classList.add('no-display');
            element.classList.add('ignore-validate');
            element.style.display = 'none';
        }
    },
    bindRemoveButtons : function(){
        var buttons = document.querySelectorAll('.delete-select-row');
        for(var i=0;i<buttons.length;i++){
            if(!buttons[i].binded){
                buttons[i].binded = true;
                buttons[i].addEventListener('click', this.remove.bind(this));
            }
        }
    },
    bindAddButton : function()
    {
        var buttons = document.querySelectorAll('.add-select-row');
        for(var i=0;i<buttons.length;i++){
            if(!buttons[i].binded){
                buttons[i].binded = true;
                buttons[i].addEventListener('click', this.add.bind(this));
            }
        }
    }
}

if (document.getElementById('option_panel_type_select')) {
    document.getElementById('option_panel_type_select').remove();
}

selectOptionType.bindRemoveButtons();

Validation.addAllThese([
    ['required-option-select-type-rows', <?php echo $this->helper('core')->jsonEncode(Mage::helper('catalog')->__('Please add rows to option.')); ?>, function(v, elm) {
            var optionContainerElm = elm.closest('div.grid');
            var selectTypesFlag = false;
            selectTypeElements = document.querySelectorAll('#'+optionContainerElm.id+' .select-type-title');
            selectTypeElements.forEach(function(elm){
                if (elm.id && elm.closest('tr').style.display !== 'none') {
                    selectTypesFlag = true;
                }
            });
            elm.advaiceContainer = optionContainerElm.id+'_advice';
        return selectTypesFlag;
}]]);

if(document.getElementById('add_select_row_button')){
    document.getElementById('add_select_row_button').addEventListener('click', selectOptionType.add.bind(selectOptionType));
}
//]]>
</script>
