<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     rwd_default
 */

/**
 * @see Mage_Bundle_Block_Catalog_Product_View_Type_Bundle
 * @var Mage_Bundle_Block_Catalog_Product_View_Type_Bundle $this
 */
?>
<?php $_product = $this->getProduct() ?>

<?php if ($_product->isSaleable()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var skipTierPricePercentUpdate = true;
        var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
        var taxCalcMethod = "<?php echo Mage::helper('tax')->getConfig()->getAlgorithm($_product->getStore()) ?>";
        var CACL_UNIT_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_UNIT_BASE ?>";
        var CACL_ROW_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_ROW_BASE ?>";
        var CACL_TOTAL_BASE = "<?php echo Mage_Tax_Model_Calculation::CALC_TOTAL_BASE ?>";
        //]]>
    </script>
<?php endif ?>
