<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     rwd_default
 */
?>
<?php
/**
 * @see Mage_Paypal_Block_Logo
 * @var Mage_Paypal_Block_Logo $this 
 * @deprecated
 */
?>
<div class="paypal-logo">
    <!-- PayPal Logo -->
        <a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;">
            <img src="https://www.paypalobjects.com/webstatic/mktg/logo/bdg_now_accepting_pp_2line_w.png" border="0" alt="Now accepting PayPal">
        </a>
        <div class="label">
            <a href="https://www.paypal.com/webapps/mpp/how-paypal-works">How PayPal Works</a>
        </div>
        <!-- PayPal Logo -->
</div>
