<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_Rating_Block_Entity_Detailed
 * @var Mage_Rating_Block_Entity_Detailed $this
 */
?>
<p class="no-rating"><a href="#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
