<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>
<?php
/**
 * Template for displaying product price at rss feeds pages
 *
 * @var Mage_Catalog_Block_Product_Price $this
 */

/** @var Mage_Catalog_Model_Product $_product */
$_product = $this->getProduct();
?>
<div class="price-box map-info">

    <?php if ($this->helper('catalog')->canApplyMsrp($_product)): ?>
        <a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('Click for price'); ?></a>
    <?php endif ?>
</div>
