<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * Template for displaying product price at product view page, gift registry and wishlist
 *
 * @var Mage_Catalog_Block_Product_Price $this
 */
?>
<?php
    /** @var Mage_Core_Helper_Data $_coreHelper */
    $_coreHelper = $this->helper('core');
    /** @var Mage_Catalog_Helper_Data $_catalogHelper */
    $_catalogHelper = $this->helper('catalog');

    /** @var Mage_Catalog_Model_Product $_product */
    $_product = $this->getProduct();
    $_id = $_product->getId();
    $_msrpPrice = '';
    $priceElementIdPrefix = $this->getPriceElementIdPrefix() ? $this->getPriceElementIdPrefix() : 'product-price-';
?>
    <div class="price-box map-info">
    <?php $_price = $this->helper('tax')->getPrice($_product, $_product->getMsrp()) ?>
        <?php if($_product->getMsrp()): ?>
            <?php $_msrpPrice = $_coreHelper->currency($_product->getMsrp(),true,true) ?>
            <span class="old-price" ><?php echo $_msrpPrice ?></span>
        <?php endif ?>

        <?php if ($_catalogHelper->isShowPriceOnGesture($_product)): ?>
            <?php $priceElementId = $priceElementIdPrefix . $_id . $this->getIdSuffix(); ?>
            <span id="<?php echo $priceElementId ?>" style="display:none"></span>
            <?php $popupId = 'msrp-popup-' . $_id . $_coreHelper->getRandomString(20); ?>
            <a href="#" id="<?php echo($popupId);?>"><?php echo $this->__('Click for price'); ?></a>
            <script type="text/javascript">
                Event.observe(window, 'load', function() {
                    var priceElement = $("<?php echo $priceElementId ?>"),
                        realPrice = <?php echo $this->getRealPriceJs($_product) ?>,
                        priceHtml = realPrice.stripScripts();

                    priceElement.innerHTML = priceHtml;
                    realPrice.evalScripts();
                    var originalOptionPriceReload;
                    if (typeof(optionsPrice) != 'undefined' && optionsPrice && optionsPrice.reload) {
                        originalOptionPriceReload = optionsPrice.reload;
                        Product.OptionsPrice.prototype.reload = function() {
                            if (originalOptionPriceReload) {
                                originalOptionPriceReload.call(this);
                            }
                            if ($('<?php echo $popupId ?>') == Catalog.Map.active) {
                                Element.update(
                                    $('map-popup-price'),
                                    $("<?php echo $priceElementId ?>").innerHTML
                                );
                            }
                        }
                        optionsPrice.reload();
                    }
                });

                Catalog.Map.addHelpLink(
                    $('<?php echo $popupId ?>'),
                    "<?php echo $this->escapeHtml($_product->getName()) ?>",
                    $("<?php echo $priceElementId ?>"),
                    '<?php echo $_msrpPrice ?>',
                    "<?php echo $_product->isSalable() ? $this->getAddToCartUrlCustom($_product, [], false) : '' ?>"
                );
            </script>
        <?php else: ?>
            <span class="msrp-price-hide-message">
                <?php echo $_catalogHelper->getMsrpPriceMessage($_product) ?>
            </span>
        <?php endif ?>

        <?php $helpLinkId = 'msrp-help-' . $_id . $_coreHelper->getRandomString(20); ?>
        <a href="#" id="<?php echo($helpLinkId);?>"><?php echo $this->__("What's this?"); ?></a>
        <script type="text/javascript">
            Catalog.Map.addHelpLink(
                $('<?php echo $helpLinkId ?>'),
                '<?php echo Mage::helper('core')->jsQuoteEscape($this->__("What's this?")); ?>'
            );
        </script>
    </div>
