<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if ($_item = $this->getItem()): ?>
<table cellspacing="0" class="qty-table">
    <tr>
        <td><?= Mage::helper('sales')->__('Ordered') ?></td>
        <td><strong><?= $_item->getQtyOrdered()*1 ?></strong></td>
    </tr>
    <?php if ((float) $_item->getQtyInvoiced()): ?>
    <tr>
        <td><?= Mage::helper('sales')->__('Invoiced') ?></td>
        <td><strong><?= $_item->getQtyInvoiced()*1 ?></strong></td>
    </tr>
    <?php endif ?>
    <?php if ((float) $_item->getQtyShipped()): ?>
    <tr>
        <td><?= Mage::helper('sales')->__('Shipped') ?></td>
        <td><strong><?= $_item->getQtyShipped()*1 ?></strong></td>
    </tr>
    <?php endif ?>
    <?php if ((float) $_item->getQtyRefunded()): ?>
    <tr>
        <td><?= Mage::helper('sales')->__('Refunded') ?></td>
        <td><strong><?= $_item->getQtyRefunded()*1 ?></strong></td>
    </tr>
    <?php endif ?>
    <?php if ((float) $_item->getQtyCanceled()): ?>
    <tr>
        <td><?= Mage::helper('sales')->__('Canceled') ?></td>
        <td><strong><?= $_item->getQtyCanceled()*1 ?></strong></td>
    </tr>
    <?php endif ?>
</table>
<?php endif ?>
