<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Payment_Block_Info_Checkmo
 * @var Mage_Payment_Block_Info_Checkmo $this
 */
?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php if($this->getInfo()->getAdditionalData()): ?>
    {{pdf_row_separator}}
    <?php if($this->getPayableTo()): ?>
        <?php echo Mage::helper('payment')->__('Make Check payable to: %s', $this->escapeHtml($this->getPayableTo())) ?>
        {{pdf_row_separator}}
    <?php endif ?>
    <?php if($this->getMailingAddress()): ?>
        <?php echo Mage::helper('payment')->__('Send Check to:') ?>
        {{pdf_row_separator}}
        <?php echo nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        {{pdf_row_separator}}
    <?php endif ?>
<?php endif ?>
