<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2022-2024 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/** @var Mage_Adminhtml_Block_Sales_Items_Renderer_Configurable $this */
?>
<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?php echo $this->getColumnHtml($_item, 'configurable_name') ?></td>
    <td class="a-center last"><?php echo $_item->getQty()*1 ?></td>
</tr>
