<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     base_default
 */

/**
 * @see Mage_Downloadable_Block_Checkout_Success
 * @var Mage_Downloadable_Block_Checkout_Success $this
 */
?>
<?php if ($this->getOrderHasDownloadable()): ?>
    <?php echo Mage::helper('downloadable')->__('Go to <a href="%s">My Downloadable Products</a>', $this->getDownloadableProductsUrl()) ?>
<?php endif ?>
