<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Downloadable_Block_Checkout_Success
 * @var Mage_Downloadable_Block_Checkout_Success $this
 */
?>
<?php if ($this->getOrderHasDownloadable()): ?>
    <?php echo Mage::helper('downloadable')->__('Go to <a href="%s">My Downloadable Products</a>', $this->getDownloadableProductsUrl()) ?>
<?php endif ?>
