<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Api_Tab_Roleinfo
 * @var Mage_Adminhtml_Block_Api_Tab_Roleinfo $this
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-permissions-role"><?php echo ($this->getRoleId() > 0) ? ($this->__('Edit Role') . " '{$this->escapeHtml($this->getRoleInfo()->getRoleName())}'") : $this->__('Add New Role') ?></h3></td>
            <td class="form-buttons">
            <?php echo $this->getBackButtonHtml() ?>
            <?php echo $this->getResetButtonHtml() ?>
            <?php echo $this->getDeleteButtonHtml() ?>
            <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<form action="<?php echo $this->getUrl('*/*/saverole') ?>" method="post" id="role_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
    var roleForm = new varienForm('role_edit_form');
</script>
