<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Api_Users
 * @var Mage_Adminhtml_Block_Api_Users $this
 */
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3><?php echo $this->__('Users') ?></h3></td>
        <td class="a-right">
        <button class="scalable add" onclick="window.location='<?php echo $this->getAddNewUrl() ?>'"><span><span><span><?php echo $this->__('Add New User') ?></span></span></span></button>
        </td>
    </tr>
</table>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>

