version: "3.7"

services:
  apache:
    image: openmage/php-dev:7.3-apache
    hostname: ${HOST_NAME:-openmage-7f000001.nip.io}
    user: "33333:33333"
    ports:
      - "${HOST_PORT:-80}:80"
    volumes:
      - ../..:/var/www/html
    environment:
      - ENABLE_SENDMAIL=true
      - XDEBUG_CONFIG=remote_connect_back=1 remote_enable=1 idekey=phpstorm
      - MAGE_IS_DEVELOPER_MODE=1
    links:
      - mysql

  cron:
    image: openmage/php-dev:7.3-cli
    working_dir: /var/www/html
    command: /run-cron.sh
    user: www-data
    volumes:
      - ../..:/var/www/html
    environment:
      - ENABLE_SENDMAIL=true
    links:
      - mysql

  cli:
    image: openmage/php-dev:7.3-apache
    working_dir: /var/www/html
    command: /bin/true
    user: "33333:33333"
    volumes:
      - ../..:/var/www/html
#    environment:
#      - AWS_ACCESS_KEY_ID=00000000000000000000
#      - AWS_SECRET_ACCESS_KEY=0000000000000000000000000000000000000000
#      - AWS_REGION=eu-west-1
#      - AWS_BUCKET=magedbm
#      - AWS_MEDIA_BUCKET=magemm
    links:
      - mysql
      - "apache:${HOST_NAME:-openmage-7f000001.nip.io}"

  mysql:
    image: mysql:5.7
    ports:
      - 3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=openmage
      - MYSQL_PASSWORD=openmage
      - MYSQL_DATABASE=openmage
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
