<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     rwd_default
 */
?>
<?php
/**
 * @see Mage_Payment_Block_Info
 * @var Mage_Payment_Block_Info $this 
 */
?>
<p class="subtitle"><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<dl class="payment-info">
    <?php foreach ($_specificInfo as $_label => $_value):?>
        <dt><?php echo $this->escapeHtml($_label)?></dt>
        <dd><?php echo nl2br(implode("\n", $this->getValueAsArray($_value, true)))?></dd>
    <?php endforeach ?>
</dl>
<?php endif ?>

<?php echo $this->getChildHtml()?>
