<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */

/**
 * @see Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Remove
 * @var Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Remove $this
 */
?>
<a href="#"
   class="btn-remove btn-remove2"
   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove Item')) ?>"
   onclick="if (confirmRemoveWishlistItem()) {
                customFormSubmit(
                    '<?php echo $this->getItemRemoveUrlCustom($this->getItem(), false) ?>',
                    '<?php echo $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])) ?>',
                    'post'
                )
            }">
    <?php echo $this->__('Remove item') ?>
</a>
