<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     rwd_default
 */

/**
 * @see Mage_Customer_Block_Account_Changeforgotten
 * @var Mage_Customer_Block_Account_Changeforgotten $this
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Reset a Password'); ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml(); ?>
<form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate" class="scaffold-form">
    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey(); ?>" />
    <div class="fieldset" style="margin-top: 70px;">
        <p class="required"><?php echo $this->__('* Required Fields'); ?></p>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>
                    <div class="input-box">
                        <?php $minPasswordLength = $this->getMinPasswordLength(); ?>
                        <input type="password"
                               class="input-text required-entry validate-password min-pass-length-<?php echo $minPasswordLength; ?>"
                               name="password"
                               id="password"
                               autocomplete="new-password" />
                        <p class="form-instructions">
                            <?php echo Mage::helper('customer')->__('The minimum password length is %s', $minPasswordLength); ?>
                        </p>
                    </div>
                </div>
                <div class="field">
                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" autocomplete="new-password" />
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>" class="button"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
