<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2022 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php if($this->getTitle()): ?>
    <h3><?= $this->getTitle() ?></h3>
<?php endif ?>
<?php if($this->getTabs()): ?>
<ul id="<?= $this->getId() ?>" class="tabs config-tabs">
<?php foreach ($this->getTabs() as $_tab): ?>
    <?php if($_tab->getSections()): ?>
    <li <?php if ($_tab->getClass()): ?>class="<?= $_tab->getClass() ?>"<?php endif ?>>
        <dl>
        <dt class="label" style=""><?= $_tab->getLabel() ?></dt>
        <?php $_iterator = 1; ?>
        <?php foreach ($_tab->getSections() as $_section): ?>
            <dd>
                <a href="<?= $_section->getUrl() ?>" class="<?= $_section->getClass() ?><?php if($_section->getId()==$this->getActiveSection()): ?> active<?php endif ?> <?= $_section->getIsLast()?'last':'' ?>">
                    <span <?php if($_tab->getId()==$this->getActiveTab()): ?>class="active"<?php endif ?>>
                        <?= $_section->getLabel() ?>
                    </span>
                </a>
            </dd>
            <?php $_iterator++ ; ?>
        <?php endforeach ?>
        </dl>
    </li>
    <?php endif ?>
<?php endforeach ?>
</ul>
<?php endif ?>
