<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_System_Config_Tabs $this */
?>
<?php if($this->getTitle()): ?>
    <h3><?php echo $this->getTitle() ?></h3>
<?php endif ?>
<?php if($this->getTabs()): ?>
<ul id="<?php echo $this->getId() ?>" class="tabs config-tabs">
<?php foreach ($this->getTabs() as $_tab): ?>
    <?php if($_tab->getSections()): ?>
    <li <?php if ($_tab->getClass()): ?>class="<?php echo $_tab->getClass() ?>"<?php endif ?>>
        <dl>
        <dt class="label" style=""><?php echo $_tab->getLabel() ?></dt>
        <?php $_iterator = 1; ?>
        <?php foreach ($_tab->getSections() as $_section): ?>
            <dd>
                <a href="<?php echo $_section->getUrl() ?>" id="section-<?php echo $_section->getId() ?>" class="<?php echo $_section->getClass() ?><?php if($_section->getId()==$this->getActiveSection()): ?> active<?php endif ?> <?php echo $_section->getIsLast()?'last':'' ?>">
                    <span <?php if($_tab->getId()==$this->getActiveTab()): ?>class="active"<?php endif ?>>
                        <?php echo $_section->getLabel() ?>
                    </span>
                </a>
            </dd>
            <?php $_iterator++ ; ?>
        <?php endforeach ?>
        </dl>
    </li>
    <?php endif ?>
<?php endforeach ?>
</ul>
<?php endif ?>
