<?php
/**
 * OpenMage
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available at https://opensource.org/license/afl-3-0-php
 *
 * @category    design
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2023 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Adminhtml_Block_Widget_Tabs
 * @var Mage_Adminhtml_Block_Widget_Tabs $this
 */
?>
<!-- <?php if($this->getTitle()): ?>
    <h3><?= $this->getTitle() ?></h3>
<?php endif ?> -->
<?php if(!empty($tabs)): ?>
<ul id="<?= $this->getId() ?>" class="tabs-horiz">
<?php foreach ($tabs as $_tab): ?>
    <li>
        <a href="<?= $this->getTabUrl($_tab)?>" id="<?php echo $this->getTabId($_tab) ?>" title="<?= $this->getTabTitle($_tab) ?>" class="tab-item-link <?= $this->getTabClass($_tab) ?><?php if (preg_match('/\s?ajax\s?/', $this->getTabClass($_tab))) {?> notloaded<?php }?>">
            <span><span class="changed" title="<?= Mage::helper('core')->quoteEscape($this->__('The information in this tab has been changed.')) ?>"></span><span class="error" title="<?= Mage::helper('core')->quoteEscape($this->__('This tab contains invalid data. Please solve the problem before saving.')) ?>"></span><?= $this->getTabLabel($_tab) ?></span>
        </a>
        <div id="<?= $this->getTabId($_tab) ?>_content" style="display:none"><?= $this->getTabContent($_tab) ?></div>
    </li>
<?php endforeach ?>
</ul>
<script type="text/javascript">

    <?= $this->getId() ?>JsTabs = new varienTabs('<?= $this->getId() ?>', '<?= $this->getDestElementId() ?>', '<?= $this->getActiveTabId() ?>', <?php echo $this->getAllShadowTabs()?>);
</script>
<?php endif ?>
