<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Tax_Rate_Form $this */
?>
<div class="entry-edit">
    <?php echo $this->getFormHtml() ?>
</div>
<?php echo $this->getChildHtml('form_after');?>
<script type="text/javascript">
var updater = new RegionUpdater('tax_country_id', 'tax_region', 'tax_region_id', <?php echo Mage::helper('directory')->getRegionJsonByStore() ?>, 'disable');
</script>
