<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   default_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if ($_products = $this->getProducts()): ?>
<p><?php echo $this->__('You are receiving this notification because you subscribed to receive alerts when the following products are back in stock:') ?></p>
<table>
<?php foreach ($_products as $_product): ?>
    <tr>
        <td width="80"><a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $_product->getThumbnailUrl() ?>" border="0" align="left" height="75" width="75" /></a></td>
        <td>
            <div><a href="<?php echo $_product->getProductUrl() ?>"><b><?php echo $this->htmlEscape($_product->getName()) ?></b></a></div>
            <?php if ($shortDescription = $_product->getShortDescription()): ?>
            <p><small><?php echo $shortDescription ?></small></p>
            <?php endif; ?>
            <p><b><?php echo $this->__('Price:') ?></b> <?php echo Mage::helper('core')->currency($_product->getPrice()) ?>
            <?php if ($_product->getPrice() != $_product->getFinalPrice()): ?>
            <br /><b><?php echo $this->__('Special price:') ?></b> <font color="red"><?php echo Mage::helper('core')->currency($_product->getFinalPrice()) ?></font>
            <?php endif; ?></p>
            <p><small><a href="<?php echo $this->getProductUnsubscribeUrl($_product->getId()) ?>"><?php echo $this->__('Click here not to receive alerts for this product') ?></a></small></p>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<p><a href="<?php echo $this->getUnsubscribeUrl() ?>"><?php echo $this->__('Unsubscribe from all stock alerts') ?></a></p>
<?php endif; ?>