<?php
/**
 * OpenMage
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magento.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (http://www.magento.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @see Mage_Reports_Block_Product_Viewed
 */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<?php $_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])); ?>
<div class="widget widget-viewed">
    <div class="widget-title">
        <h2><?php echo $this->__('Recently Viewed') ?></h2>
    </div>
    <div class="widget-products">
        <ol class="products-list">
        <?php $i=0; foreach ($_products as $_product): ?>
            <li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(85) ?>" width="85" height="85" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                <div class="product-shop">
                    <div class="f-fix">
                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php echo $this->getPriceHtml($_product, true, '-widget-viewed-list') ?>
                        <?php if($_product->isSaleable()): ?>
                            <button type="button"
                                    title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                                    class="button btn-cart"
                                    onclick="customFormSubmit(
                                            '<?php echo $this->getAddToCartUrlCustom($_product, [], false) ?>',
                                            '<?php echo $_params ?>',
                                            'post')">
                                <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                            </button>
                        <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li>
                                    <a href="#"
                                       class="link-wishlist"
                                       onclick="customFormSubmit(
                                               '<?php echo $this->getAddToWishlistUrlCustom($_product, false) ?>',
                                               '<?php echo $_params ?>',
                                               'post')">
                                        <?php echo $this->__('Add to Wishlist') ?>
                                    </a>
                                </li>
                            <?php endif ?>
                            <?php if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)) : ?>
                                <li>
                                    <span class="separator">|</span>
                                    <a href="#"
                                       class="link-compare"
                                       onclick="customFormSubmit(
                                               '<?php echo $_compareUrl ?>',
                                               '<?php echo $_params ?>',
                                               'post')">
                                        <?php echo $this->__('Add to Compare') ?>
                                    </a>
                                </li>
                            <?php endif ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
    </div>
</div>
<?php endif ?>
