name: DDEV

on:
  push:
  pull_request:
  workflow_call:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  test:
    name: DDEV cypress
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Setup DDEV
        uses: ddev/github-action-setup-ddev@v1
        with:
          autostart: false

      # install DDEV configuration
      - run: ddev config --project-type=magento --php-version=8.1 --webserver-type=nginx-fpm

      # install composer dependencies
      - run: ddev composer install

      # install openmage
      - run: ddev openmage-install -s -q

      # install cypress-addon
      - run: ddev add-on get tyler36/ddev-cypress

      # start ddev
      - run: ddev start

        # run cypress
      - run: ddev cypress-run
