name: "PHP Security Check"

on:
  # For testing only
  # Allow manually triggering the workflow.
  # Trigger automatically every Monday on midnight
  pull_request_target:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  php_security:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db

      - name: Check for vulnerabilities
        uses: symfonycorp/security-checker-action@v4
