name: XML Validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@master
    - name: "Validate XMLs"
      uses: anyone-developer/anyone-validate-xml@master
      with:
        file-extension: ".xml"
        ignore-directories: ".git"
        read-path: "."
