name: XML Validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@master
    - name: "test"
      run: "pwd; ls -lah;"
    - name: "Install xmllint"
      run: "apt -y install libxml2-utils"
    - name: "Validate XMLs"
      run: "find . -type f -iname '*.xml' | xargs -I '{}' xmllint --noout '{}'"
