<?php

/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Open Software License (OSL 3.0)
 * @package    Mage_Paypal
 */

/**
 * @see Mage_Paypal_Block_Info
 * @var Mage_Paypal_Block_Info $this
 */
?>
<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php if ($this->getTransactionId()): ?>
    <p><?php echo $this->__('Transaction ID: %s', $this->escapeHtml($this->getTransactionId())) ?></p>
<?php endif; ?>