<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     base_default
 */
?>
<?php if($this->getItemCollection()->getSize()): ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('This product is also part of bundle(s)') ?></h2>
    <table class="products-grid" id="bundle-product-table">
    <?php // $this->setColumnCount(4); // uncomment this line if you want to have another number of columns ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <tr>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_bundle=$this->getIterableItem()): ?>
            <td>
                <a href="<?php echo $_bundle->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_bundle->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_bundle, 'small_image')->resize(125) ?>" width="125" height="125" alt="<?php echo $this->escapeHtml($_bundle->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?php echo $_bundle->getProductUrl() ?>"><?php echo $this->escapeHtml($_bundle->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_bundle, true) ?>
                <?php echo $this->getReviewsSummaryHtml($_bundle) ?>
            </td>
            <?php else: ?>
            <td class="empty">&nbsp;</td>
            <?php endif ?>
        <?php endfor ?>
        </tr>
    <?php endfor ?>
    </table>
    <script type="text/javascript">decorateTable('bundle-product-table')</script>
</div>
<?php endif ?>
