<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/**
 * @see Mage_Adminhtml_Block_Template
 * @var Mage_Adminhtml_Block_Template $this
 */
?>
<ul>
<?php foreach ($items as $item): ?>
    <li id="<?php echo $item['id'] ?>" url="<?php echo $item['url'] ?>">
        <div style="float:right; color:red; font-weight:bold;">[<?php echo $item['type'] ?>]</div>
        <strong><?php echo $this->escapeHtml($item['name']) ?></strong><br/>
        <span class="informal"><?php echo $this->escapeHtml($item['description']) ?></span>
    </li>
<?php endforeach ?>
</ul>
