<?php
/**
 * This file is part of OpenMage.
 * For copyright and license information, please view the COPYING.txt file that was distributed with this source code.
 *
 * @category    design
 * @package     default_default
 */

/** @var Mage_Adminhtml_Block_Sales_Items_Renderer_Configurable $this */
?>
<?php $_item = $this->getItem() ?>
<tr class="border">
    <td><?php echo $this->getColumnHtml($_item, 'configurable_name') ?></td>
    <td class="a-center last"><?php echo $_item->getQty()*1 ?></td>
</tr>
