<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     default_default
 * @copyright   Copyright (c) 2006-2020 Magento, Inc. (https://www.magento.com)
 * @copyright   Copyright (c) 2021-2025 The OpenMage Contributors (https://www.openmage.org)
 * @license     https://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/**
 * @see Mage_Adminhtml_Block_Permissions_Buttons
 * @var Mage_Adminhtml_Block_Permissions_Buttons $this
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;">
                <h3>
                  <?php if($this->getUser()->getUserId()): ?>
                  <?php $_userName = $this->getUser()->getFirstname() . ' ' . $this->getUser()->getLastname() ?>
                  <?php echo $this->__("Edit User '%s'", $_userName) ?>
                  <?php else: ?>
                  <?php echo $this->__('Add New User') ?>
                  <?php endif ?>
                </h3>
            </td>
            <td class="form-buttons">
            <?php echo $this->getBackButtonHtml() ?>
            <?php echo $this->getResetButtonHtml() ?>
            <?php echo $this->getDeleteButtonHtml() ?>
            <?php echo $this->getSaveButtonHtml() ?>
   </table>
</div>
<form action="<?php echo $this->getUrl('*/*/saveuser') ?>" method="post" id="user_edit_form">
    <?php echo $this->getBlockHtml('formkey')?>
</form>
<script type="text/javascript">
    var userForm = new varienForm('user_edit_form');
</script>
