<?php
/**
 * @copyright  For copyright and license information, read the COPYING.txt file.
 * @link       /COPYING.txt
 * @license    Academic Free License (AFL 3.0)
 * @package     rwd_default
 */

/**
 * @var Mage_Reports_Block_Product_Compared $this
 */
?>
<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="widget widget-compared">
    <div class="block block-list">
        <div class="block-title">
            <strong><span><?php echo $this->__('Recently Compared') ?></span></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $this->getNameInLayout(); ?>
            <ol class="mini-products-images-list" id="widget-compared-<?php echo $suffix; ?>">
            <?php $i = 0; foreach ($_products as $_product): ?>
                <li class="item">
                    <?php $_imgSize = 310; // Images will be displayed at roughly this size when viewed at less than the medium breakpoint ?>
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($_imgSize) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                </li>
            <?php endforeach ?>
            </ol>
            <script type="text/javascript">decorateList('widget-compared-<?php echo $suffix; ?>', 'none-recursive')</script>
        </div>
    </div>
</div>
<?php endif ?>
